### Machine translated by `cargo zng l10n`, 5aa5aba347d7702ff4b24bfea056e5e698e399dec4c11b3ec2bac3e5eb947249

### Auto generated by `cargo zng l10n`

COPY_CMD =
    .name = Kopier

CUT_CMD =
    .name = Klip

PASTE_CMD =
    .name = Sæt ind