### Machine translated by `cargo zng l10n`, 3e9db6ab8a9dbbac14d31c68f744c15e88fd79703c907e34ad6ccc8a803d4847

### Auto generated by `cargo zng l10n`

CLOSE_CMD =
    .info = Închide fereastra
    .name = Închidere

EXCLUSIVE_FULLSCREEN_CMD =
    .info = Comută modul ecran complet exclusiv pentru fereastră
    .name = Ecran complet exclusiv

FULLSCREEN_CMD =
    .info = Comută modul ecran complet pentru fereastră
    .name = Ecran complet

MAXIMIZE_CMD =
    .info = Maximizează fereastra
    .name = Maximizare

MINIMIZE_CMD =
    .info = Minimizează fereastra
    .name = Minimizare

RESTORE_CMD =
    .info = Restabilește fereastra la starea anterioară neminimizată sau la starea normală
    .name = Restaurare