### Machine translated by `cargo zng l10n`, 08fd454f1bfe552e85c1338a6842b18e91dd13c7e3b2949c8b5dc77f1e0c9f8c

### Auto generated by `cargo zng l10n`

info =
    .install = Πού πρέπει να εγκατασταθεί το {$app};
    .update-repair-uninstall = Πού είναι εγκατεστημένο το {$app}.

# $bytes is already formatted e.g.: 900kB or 50MB.
min-required-space = Απαιτείται τουλάχιστον {$bytes} ελεύθερου χώρου στον δίσκο.

reset-label = Προεπιλεγμένη τοποθεσία

select-label = Επιλογή τοποθεσίας

title =
    .install = Επιλογή τοποθεσίας εγκατάστασης
    .uninstall = Τοποθεσία εγκατάστασης