### Machine translated by `cargo zng l10n`, 86bb0abb6293e164ae596c4745cba0db2da828923ef8061ed99c7bf5ccfa9ddd

### Auto generated by `cargo zng l10n`

default-info =
    .create-shortcut = Δημιουργία συντόμευσης
    .extract-files = Εξαγωγή αρχείων
    .register-uninstaller = Εγγραφή απεγκαταστάτη
    .remove-files = Αφαίρεση αρχείων
    .remove-shortcut = Αφαίρεση συντόμευσης
    .unregister-uninstaller = Κατάργηση εγγραφής απεγκαταστάτη

info =
    .install = Παρακαλώ περιμένετε όσο το {$app} εγκαθίσταται στον υπολογιστή σας.
    .repair = Παρακαλώ περιμένετε όσο το {$app} επιδιορθώνεται στον υπολογιστή σας.
    .uninstall = Παρακαλώ περιμένετε όσο το {$app} απεγκαθίσταται από τον υπολογιστή σας.
    .update = Παρακαλώ περιμένετε όσο το {$app} ενημερώνεται στον υπολογιστή σας.

title =
    .install = Εγκατάσταση
    .repair = Επιδιόρθωση
    .uninstall = Απεγκατάσταση
    .update = Ενημέρωση