### Machine translated by `cargo zng l10n`, 2abd48f76a022e01c465074590f32305b520f65b9a52b2a63373e4df86ad2381

### Auto generated by `cargo zng l10n`

action-run =
    .info = Exécuter {$app}

message =
    .install = L'assistant a installé {$app} version {$version} sur votre ordinateur.
    .repair = L'assistant a réparé l'installation de {$app} version {$version} sur votre ordinateur.
    .uninstall = L'assistant a désinstallé {$app} version {$version} de votre ordinateur.
    .update = L'assistant a mis à jour {$app} de {$current_version} à {$new_version} sur votre ordinateur.

title =
    .install = {$app} Installé
    .repair = {$app} Réparé
    .uninstall = {$app} Désinstallé
    .update = {$app} Mis à jour