### Machine translated by `cargo zng l10n`, 08fd454f1bfe552e85c1338a6842b18e91dd13c7e3b2949c8b5dc77f1e0c9f8c

### Auto generated by `cargo zng l10n`

info =
    .install = Où {$app} doit-il être installé ?
    .update-repair-uninstall = Où {$app} est installé.

# $bytes is already formatted e.g.: 900kB or 50MB.
min-required-space = Il faut au moins {$bytes} d'espace disque libre.

reset-label = Emplacement par défaut

select-label = Sélectionner un emplacement

title =
    .install = Sélectionner l'emplacement d'installation
    .uninstall = Emplacement d'installation