### Machine translated by `cargo zng l10n`, 8c9c95d8cf28b2cb9c70f9781ccec7824f959908ffe3f862c4b327a081d61caf

### Auto generated by `cargo zng l10n`

INSPECT_CMD =
    .info = ตรวจสอบหน้าต่าง
    .name = ตัวตรวจสอบการดีบั๊ก

## Inspector Window (always en-US)

info-help = ข้อมูลวิดเจ็ตที่ติดตาม

intrinsic-help = โหนดภายใน

nest-group-help = กลุ่มที่ซ้อนอยู่

screenshot =
    .copy-error = เกิดข้อผิดพลาดในการคัดลอกภาพหน้าจอ {$error}
    .error-dlg-title = ข้อผิดพลาดของภาพหน้าจอ
    .save-dlg-filter = ไฟล์รูปภาพ
    .save-dlg-starting-name = screenshot.png
    .save-dlg-title = บันทึกภาพหน้าจอ
    .save-error = เกิดข้อผิดพลาดในการบันทึกภาพหน้าจอ {$error}

select-widget = เลือกวิดเจ็ตเพื่อตรวจสอบ

window =
    .title = {$inspected_window_title} - ตัวตรวจสอบ