// Script inserted in each property function's full page after the user docs.
// It changes the page to highlight the widget property aspects.
(function () {

    // change title.
    let title = document.getElementsByTagName('h1')[0];
    title.innerHTML = title.innerHTML.replace('Function', 'Property');

    // copy fn declaration to Function section that was generated by #[property]
    let fn = document.querySelector('pre.rust.fn');
    let ffn = document.getElementById('ffn');
    ffn.innerHTML = fn.innerHTML;

    // edit the function source code to only show the property name and arguments.
    fn.innerText = fn.innerText
                    .replace(/.*fn /s, '')
                    .replace(/(?!<[^>]*)\((?![^<]*>)\s*/s, ': {\n    ')
                    .replace(/(?!<[^>]*)\s*\)\s+->(?![^<]*>).*/s, '\n}');
    let set = new Set();
    for (let a of ffn.getElementsByTagName('a')) {
         if (!set.has(a.innerText)) {
            fn.innerHTML = fn.innerHTML.replaceAll(a.innerText, a.outerHTML);
            set.add(a.innerText)
        }
    }

})()