### Machine translated by `cargo zng l10n`, ab0682936292139ef046e822c139586a33986c3522951ecb20715ef0c900db4b

### Auto generated by `cargo zng l10n`

FOCUS_ALT_CMD =
    .info = Focus sur la portée ALT
    .name = Focus Alt

FOCUS_DOWN_CMD =
    .info = Focus sur le plus proche élément enfichable vers le bas
    .name = Focus Bas

FOCUS_ENTER_CMD =
    .info = Focus sur l'enfant enfichable
    .name = Focus Entrée

FOCUS_EXIT_CMD =
    .info = Focus sur le parent enfichable, ou retour au focus
    .name = Focus Sortie

FOCUS_LEFT_CMD =
    .info = Focus sur le plus proche élément enfichable vers la gauche
    .name = Focus Gauche

FOCUS_NEXT_CMD =
    .info = Focus sur l'élément enfichable suivant
    .name = Focus Suivant

FOCUS_PREV_CMD =
    .info = Focus sur l'élément enfichable précédent
    .name = Focus Précédent

FOCUS_RIGHT_CMD =
    .info = Focus sur le plus proche élément enfichable vers la droite
    .name = Focus Droit

FOCUS_UP_CMD =
    .info = Focus sur le plus proche élément enfichable vers le haut
    .name = Focus Haut