[workspace]
[package]
name = "zng-res-sfx"
version = "0.1.0"
edition = "2024"

[dependencies]
zstd = { version = "0.13", default-features = false }
lzma-rust2 = { version = "0.19", default-features = false, features = ["std"] }

# <has-icon>
[target.'cfg(windows)'.build-dependencies]
winresource = "0.1"
# </has-icon>

# optimize for binary size
[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = true