### Machine translated by `cargo zng l10n`, 3bff0a0f920b53ccdc5a8a62ff6395907be54fe1e4eb7448f218d39230ddc71b

### Auto generated by `cargo zng l10n`

PAGE_DOWN_CMD =
    .info = Egy oldalonként csúszd le
    .name = Oldal lefelé

PAGE_LEFT_CMD =
    .info = Egy oldalonként csúszd balra
    .name = Oldal balra

PAGE_RIGHT_CMD =
    .info = Egy oldalonként csúszd jobbra
    .name = Oldal jobbra

PAGE_UP_CMD =
    .info = Egy oldalonként csúszd felfelé
    .name = Oldal felfelé

SCROLL_DOWN_CMD =
    .info = Egy csúszási egységkel csúszd le
    .name = Csúszd le

SCROLL_LEFT_CMD =
    .info = Egy csúszási egységkel csúszd balra
    .name = Csúszd balra

SCROLL_RIGHT_CMD =
    .info = Egy csúszási egységkel csúszd jobbra
    .name = Csúszd jobbra

SCROLL_TO_BOTTOM_CMD =
    .info = Csúszd le az tartalom aljára
    .name = Csúszd le az aljra

SCROLL_TO_LEFTMOST_CMD =
    .info = Csúszd balra a tartalom bal széle
    .name = Csúszd a legbalra

SCROLL_TO_RIGHTMOST_CMD =
    .info = Csúszd jobbra a tartalom jobb széle
    .name = Csúszd a legjobbra

SCROLL_TO_TOP_CMD =
    .info = Csúszd felfelé a tartalom tetejére
    .name = Csúszd fel

SCROLL_UP_CMD =
    .info = Egy csúszási egységkel csúszd felfelé
    .name = Csúszd fel

ZOOM_IN_CMD =
    .name = Nagyítás

ZOOM_OUT_CMD =
    .name = Kisítés

ZOOM_RESET_CMD =
    .name = Nagyítás visszaállítása

ZOOM_TO_FIT_CMD =
    .name = Belefogadás