### Machine translated by `cargo zng l10n`, ab0682936292139ef046e822c139586a33986c3522951ecb20715ef0c900db4b

### Auto generated by `cargo zng l10n`

FOCUS_ALT_CMD =
    .info = Fokus auf den Alt-Bereich
    .name = Fokus Alt

FOCUS_DOWN_CMD =
    .info = Fokus auf das nächstgelegene fokussierbare nach unten
    .name = Fokus Runter

FOCUS_ENTER_CMD =
    .info = Fokus auf den fokussierbaren Kind
    .name = Fokus Enter

FOCUS_EXIT_CMD =
    .info = Fokus auf das fokussierbare Elternteil oder Fokus zurückgeben
    .name = Fokus Verlassen

FOCUS_LEFT_CMD =
    .info = Fokus auf das nächstgelegene fokussierbare links
    .name = Fokus Links

FOCUS_NEXT_CMD =
    .info = Fokus auf das nächste fokussierbare
    .name = Fokus Nächster

FOCUS_PREV_CMD =
    .info = Fokus auf das vorherige fokussierbare
    .name = Fokus Vorheriger

FOCUS_RIGHT_CMD =
    .info = Fokus auf das nächstgelegene fokussierbare rechts
    .name = Fokus Rechts

FOCUS_UP_CMD =
    .info = Fokus auf das nächstgelegene fokussierbare nach oben
    .name = Fokus Hoch