### Machine translated by `cargo zng l10n`, 94527aed8f60480f65e908ce1bb46627d277ef4ebd081f0dc4bb2eb5cfcfaf82

### Auto generated by `cargo zng l10n`

action-run =
    .info = {$app} を実行

message =
    .install = ウィザードが {$app} {$version} をコンピュータにインストールしました。
    .uninstall = ウィザードが {$app} {$version} をコンピュータからアンインストールしました。
    .update = ウィザードが {$app} を {$current_version} から {$new_version} に更新しました。

title =
    .install = {$app} をインストールしました
    .repair = {$app} を修復しました
    .uninstall = {$app} をアンインストールしました
    .update = {$app} を更新しました