### Machine translated by `cargo zng l10n`, 86bb0abb6293e164ae596c4745cba0db2da828923ef8061ed99c7bf5ccfa9ddd

### Auto generated by `cargo zng l10n`

default-info =
    .create-shortcut = ショートカットを作成
    .extract-files = ファイルを抽出
    .register-uninstaller = アンインストーラーを登録
    .remove-files = ファイルを削除
    .remove-shortcut = ショートカットを削除
    .unregister-uninstaller = アンインストーラーの登録解除

info =
    .install = {$app} がコンピューターにインストールされるまでお待ちください。
    .repair = {$app} がコンピューターで修復されるまでお待ちください。
    .uninstall = {$app} がコンピューターからアンインストールされるまでお待ちください。
    .update = {$app} がコンピューターで更新されるまでお待ちください。

title =
    .install = インストール中
    .repair = 修復中
    .uninstall = アンインストール中
    .update = 更新中