### Machine translated by `cargo zng l10n`, 3bff0a0f920b53ccdc5a8a62ff6395907be54fe1e4eb7448f218d39230ddc71b

### Auto generated by `cargo zng l10n`

PAGE_DOWN_CMD =
    .info = Gulir ke bawah satu unit halaman
    .name = Bawah Halaman

PAGE_LEFT_CMD =
    .info = Gulir Kiri satu unit halaman
    .name = Kiri Halaman

PAGE_RIGHT_CMD =
    .info = Gulir Kanan satu unit halaman
    .name = Kanan Halaman

PAGE_UP_CMD =
    .info = Gulir Atas satu unit halaman
    .name = Atas Halaman

SCROLL_DOWN_CMD =
    .info = Gulir ke bawah satu unit gulir
    .name = Gulir Bawah

SCROLL_LEFT_CMD =
    .info = Gulir Kiri satu unit gulir
    .name = Gulir Kiri

SCROLL_RIGHT_CMD =
    .info = Gulir Kanan satu unit gulir
    .name = Gulir Kanan

SCROLL_TO_BOTTOM_CMD =
    .info = Gulir ke bawah ke bagian bawah konten.
    .name = Gulir ke Bawah

SCROLL_TO_LEFTMOST_CMD =
    .info = Gulir kiri ke tepi kiri konten
    .name = Gulir ke Paling Kiri

SCROLL_TO_RIGHTMOST_CMD =
    .info = Gulir kanan ke tepi kanan konten
    .name = Gulir ke Paling Kanan

SCROLL_TO_TOP_CMD =
    .info = Gulir ke atas ke bagian atas konten
    .name = Gulir ke Atas

SCROLL_UP_CMD =
    .info = Gulir Atas satu unit gulir
    .name = Gulir Atas

ZOOM_IN_CMD =
    .name = Perbesar

ZOOM_OUT_CMD =
    .name = Perkecil

ZOOM_RESET_CMD =
    .name = Atur Ulang Zoom

ZOOM_TO_FIT_CMD =
    .name = Sesuaikan Zoom