### Machine translated by `cargo zng l10n`, 3bff0a0f920b53ccdc5a8a62ff6395907be54fe1e4eb7448f218d39230ddc71b

### Auto generated by `cargo zng l10n`

PAGE_DOWN_CMD =
    .info = Deslizza cap avall per una unitat de pàgina
    .name = Pàgina Avall

PAGE_LEFT_CMD =
    .info = Deslizza a l'Esquerre per una unitat de pàgina
    .name = Pàgina Esquerre

PAGE_RIGHT_CMD =
    .info = Deslizza a la Dreta per una unitat de pàgina
    .name = Pàgina Dreta

PAGE_UP_CMD =
    .info = Deslizza cap amunt per una unitat de pàgina
    .name = Pàgina Amunt

SCROLL_DOWN_CMD =
    .info = Deslizza cap avall per una unitat de desclinat
    .name = Deslizza Cap Avall

SCROLL_LEFT_CMD =
    .info = Deslizza a l'Esquerre per una unitat de desclinat
    .name = Deslizza a l'Esquerre

SCROLL_RIGHT_CMD =
    .info = Deslizza a la Dreta per una unitat de desclinat
    .name = Deslizza a la Dreta

SCROLL_TO_BOTTOM_CMD =
    .info = Deslizza cap avall fins al fons del contingut.
    .name = Deslizza a la Part Inferior

SCROLL_TO_LEFTMOST_CMD =
    .info = Deslizza a l'Esquerre fins a l'orla esquerra del contingut
    .name = Deslizza a l'Esquerre

SCROLL_TO_RIGHTMOST_CMD =
    .info = Deslizza a la Dreta fins a l'orla dreta del contingut
    .name = Deslizza a la Dreta

SCROLL_TO_TOP_CMD =
    .info = Deslizza cap amunt fins a la part superior del contingut
    .name = Deslizza a la Part Superior

SCROLL_UP_CMD =
    .info = Deslizza cap amunt per una unitat de desclinat
    .name = Deslizza Cap Amunt

ZOOM_IN_CMD =
    .name = Fer Zoom

ZOOM_OUT_CMD =
    .name = Desenzoomar

ZOOM_RESET_CMD =
    .name = Reiniciar Zoom

ZOOM_TO_FIT_CMD =
    .name = Adaptar Zoom