### Machine translated by `cargo zng l10n`, be135842e65abb43f38e8f66e75bcc43fb249683b92f3d12466fbb444de99621

### Auto generated by `cargo zng l10n`

info =
    .clean = Operācija neizdevās, visas izmaiņas tika atsauktas.
    .corrupted = Operācija neizdevās, instalācija ir bojāta.

message =
    .install-clean = Instalēšanas operācija neizdevās, {$app} netika instalēts.
    .install-corrupted = Instalēšanas operācija neizdevās, {$app} tika instalēts tikai daļēji.
    .repair-clean = Labošanas operācija neizdevās, {$app} instalācija netika salabota.
    .repair-corrupted = Labošanas operācija neizdevās, {$app} instalācija tika salabota tikai daļēji.
    .uninstall-clean = Atinstalēšanas operācija neizdevās, {$app} palika instalēts.
    .uninstall-corrupted = Atinstalēšanas operācija neizdevās, {$app} tika atinstalēts tikai daļēji.
    .update-clean = Atjaunināšanas operācija neizdevās, {$app} netika atjaunināts. Pašreiz instalētā versija {$current_version} paliek un to joprojām var izmantot.
    .update-corrupted = Atjaunināšanas operācija neizdevās, {$app} tika atjaunināts tikai daļēji.

title =
    .install = Instalēšana neizdevās
    .repair = Labošana neizdevās
    .uninstall = Atinstalēšana neizdevās
    .update = Atjaunināšana neizdevās