### Machine translated by `cargo zng l10n`, 08fd454f1bfe552e85c1338a6842b18e91dd13c7e3b2949c8b5dc77f1e0c9f8c

### Auto generated by `cargo zng l10n`

info =
    .install = Kur {$app} vajadzētu instalēt?
    .update-repair-uninstall = Kur {$app} ir instalēts.

# $bytes is already formatted e.g.: 900kB or 50MB.
min-required-space = Nepieciešams vismaz {$bytes} brīva diska telpa.

reset-label = Standarta vieta

select-label = Izvēlēties vietu

title =
    .install = Izvēlēties instalācijas vietu
    .uninstall = Instalācijas vieta