### Machine translated by `cargo zng l10n`, be135842e65abb43f38e8f66e75bcc43fb249683b92f3d12466fbb444de99621

### Auto generated by `cargo zng l10n`

info =
    .clean = Operacija nepavyko, visi pakeitimai anuliuoti.
    .corrupted = Operacija nepavyko, diegimas pažeistas.

message =
    .install-clean = Diegimo operacija nepavyko, {$app} nebuvo įdiegta.
    .install-corrupted = Diegimo operacija nepavyko, {$app} buvo įdiegta tik iš dalies.
    .repair-clean = Taisymo operacija nepavyko, {$app} diegimas nebuvo pataisytas.
    .repair-corrupted = Taisymo operacija nepavyko, {$app} buvo pataisyta tik iš dalies.
    .uninstall-clean = Pašalinimo operacija nepavyko, {$app} liko įdiegta.
    .uninstall-corrupted = Pašalinimo operacija nepavyko, {$app} buvo pašalinta tik iš dalies.
    .update-clean = Atnaujinimo operacija nepavyko, {$app} nebuvo atnaujinta. Dabartinė įdiegta versija {$current_version} lieka ir gali būti naudojama.
    .update-corrupted = Atnaujinimo operacija nepavyko, {$app} buvo atnaujinta tik iš dalies.

title =
    .install = Diegimas nepavyko
    .repair = Taisymas nepavyko
    .uninstall = Pašalinimas nepavyko
    .update = Atnaujinimas nepavyko