### Machine translated by `cargo zng l10n`, 08fd454f1bfe552e85c1338a6842b18e91dd13c7e3b2949c8b5dc77f1e0c9f8c

### Auto generated by `cargo zng l10n`

info =
    .install = Kur turėtų būti įdiegtas {$app}?
    .update-repair-uninstall = Kur yra įdiegtas {$app}.

# $bytes is already formatted e.g.: 900kB or 50MB.
min-required-space = Reikalingai bent {$bytes} laisvos diskras vietos.

reset-label = Standartinė vieta

select-label = Pasirinkite vietą

title =
    .install = Pasirinkite įdiegimo vietą
    .uninstall = Įdiegimo vieta