### Machine translated by `cargo zng l10n`, 86bb0abb6293e164ae596c4745cba0db2da828923ef8061ed99c7bf5ccfa9ddd

### Auto generated by `cargo zng l10n`

default-info =
    .create-shortcut = Sukurti trumpiklį
    .extract-files = Išsigyti failus
    .register-uninstaller = Registruoti pašalinimo įrankį
    .remove-files = pašalinti failus
    .remove-shortcut = pašalinti trumpiklį
    .unregister-uninstaller = Iregistruoti pašalinimo įrankį

info =
    .install = Prašome laukti, kol {$app} bus įdiegtas jūsų kompiuteriu.
    .repair = Prašome laukti, kol {$app} bus taisytas jūsų kompiuteriu.
    .uninstall = Prašome laukti, kol {$app} bus pašalintas iš jūsų kompiuterio.
    .update = Prašome laukti, kol {$app} bus atnaujintas jūsų kompiuteriu.

title =
    .install = Įdiegimas
    .repair = Taisymas
    .uninstall = Pašalijimas
    .update = Atnaujinimas