### Machine translated by `cargo zng l10n`, d71191013144b142e5eaea12b0fca3409e50c6d718fac39611285128494e9ee4

### Auto generated by `cargo zng l10n`

## Debug Crash Handler

window =
    .title = {$app} - アプリがクラッシュしました

## Panels

# save-copy-starting-name:
#     default file name
minidump =
    .open-error = ミニダンプを開けませんでした。
        {$error}
    .remove-error = ミニダンプを削除できませんでした。
        {$error}
    .save-copy-filter-name = ミニダンプ
    .save-copy-starting-name = minidump
    .save-copy-title = コピーを保存
    .save-error = ミニダンプのコピーを保存できませんでした。
        {$error}
    .title = ミニダンプ

panic =
    .title = パニック

stderr =
    .title = Stderr

stdout =
    .title = Stdout

summary =
    .text = タイムスタンプ: {$timestamp}
        終了コード: {$exit_code}
        シグナル: {$signal}
        Stderr: {$stderr_len} バイト
        Stdout: {$stdout_len} バイト
        パニック: {$is_panic}
        ミニダンプ: {$minidump_path}
        
        引数: {$args}
        OS: {$os}
    .title = 概要

widget =
    .title = ウィジェット