### Machine translated by `cargo zng l10n`, 1efe39e07e78c5ca09a02e98644ae77adf5b9afad87a6f8b13dcc8790acc63db

### Auto generated by `cargo zng l10n`

COPY_CMD =
    .info = Seçimi panoya kopyala
    .name = Kopyala

CUT_CMD =
    .info = Seçimi kaldır ve panoya yerleştir
    .name = Kes

PASTE_CMD =
    .info = Panodaki içeriği yapıştır
    .name = Yapıştır