### Machine translated by `cargo zng l10n`, ab0682936292139ef046e822c139586a33986c3522951ecb20715ef0c900db4b

### Auto generated by `cargo zng l10n`

FOCUS_ALT_CMD =
    .info = Alternatif odak kapsamına geç
    .name = Alternatif Odak

FOCUS_DOWN_CMD =
    .info = Aşağıdaki en yakın odaklanılabilir öğeye geç
    .name = Aşağı Odakla

FOCUS_ENTER_CMD =
    .info = Alt odaklanılabilir öğeye geç
    .name = Odağa Gir

FOCUS_EXIT_CMD =
    .info = Üst odaklanılabilir öğeye geç veya odağı geri döndür
    .name = Odaktan Çık

FOCUS_LEFT_CMD =
    .info = Soldaki en yakın odaklanılabilir öğeye geç
    .name = Sola Odakla

FOCUS_NEXT_CMD =
    .info = Sonraki odaklanılabilir öğeye geç
    .name = Sonraki Odak

FOCUS_PREV_CMD =
    .info = Önceki odaklanılabilir öğeye geç
    .name = Önceki Odak

FOCUS_RIGHT_CMD =
    .info = Sağdaki en yakın odaklanılabilir öğeye geç
    .name = Sağa Odakla

FOCUS_UP_CMD =
    .info = Yukarıdaki en yakın odaklanılabilir öğeye geç
    .name = Yukarı Odakla