### Machine translated by `cargo zng l10n`, ca15a8ce25cc0c158873c10a67ae3b8a2387847209565e6c26c99f1cba2d77eb

### Auto generated by `cargo zng l10n`

accept =
    .false = Ne prihvaćam sporazum
    .true = Prihvaćam sporazum

info =
    .install = Molimo vas da pregledate uvjete licence prije instaliranja {$app}
    .update = Molimo vas da pregledate uvjete licence prije ažuriranja {$app}

message = Morate prihvatiti uvjete ovog sporazuma prije nastavka.
    .requires_scroll = Morate pročitati i prihvatiti uvjete ovog sporazuma prije nastavka.

title = Ugovor o licenci