### Machine translated by `cargo zng l10n`, 2abd48f76a022e01c465074590f32305b520f65b9a52b2a63373e4df86ad2381

### Auto generated by `cargo zng l10n`

action-run =
    .info = Pokreni {$app}

message =
    .install = Čarobnjak je instalirao {$app} {$version} na vaše računalo.
    .repair = Čarobnjak je popravio instalaciju {$app} {$version} na vašem računalu.
    .uninstall = Čarobnjak je deinstalirao {$app} {$version} s vašeg računala.
    .update = Čarobnjak je ažurirao {$app} s verzije {$current_version} na {$new_version} na vašem računalu.

title =
    .install = {$app} je instaliran
    .repair = {$app} je popravljen
    .uninstall = {$app} je deinstaliran
    .update = {$app} je ažuriran