### Machine translated by `cargo zng l10n`, 08fd454f1bfe552e85c1338a6842b18e91dd13c7e3b2949c8b5dc77f1e0c9f8c

### Auto generated by `cargo zng l10n`

info =
    .install = Gdje bi {$app} trebao biti instaliran?
    .update-repair-uninstall = Gdje je {$app} instaliran.

# $bytes is already formatted e.g.: 900kB or 50MB.
min-required-space = Potrebno je najmanje {$bytes} slobodnog prostora na disku.

reset-label = Zadata lokacija

select-label = Odaberi lokaciju

title =
    .install = Odaberi lokaciju instalacije
    .uninstall = Lokacija instalacije