### Machine translated by `cargo zng l10n`, 3bff0a0f920b53ccdc5a8a62ff6395907be54fe1e4eb7448f218d39230ddc71b

### Auto generated by `cargo zng l10n`

PAGE_DOWN_CMD =
    .info = Faire défiler vers le bas d'une page
    .name = Page suivante

PAGE_LEFT_CMD =
    .info = Faire défiler vers la gauche d'une page
    .name = Page à gauche

PAGE_RIGHT_CMD =
    .info = Faire défiler vers la droite d'une page
    .name = Page à droite

PAGE_UP_CMD =
    .info = Faire défiler vers le haut d'une page
    .name = Page précédente

SCROLL_DOWN_CMD =
    .info = Faire défiler vers le bas d'une unité de défilement
    .name = Faire défiler vers le bas

SCROLL_LEFT_CMD =
    .info = Faire défiler vers la gauche d'une unité de défilement
    .name = Faire défiler vers la gauche

SCROLL_RIGHT_CMD =
    .info = Faire défiler vers la droite d'une unité de défilement
    .name = Faire défiler vers la droite

SCROLL_TO_BOTTOM_CMD =
    .info = Faire défiler jusqu'au bas du contenu.
    .name = Aller en bas

SCROLL_TO_LEFTMOST_CMD =
    .info = Faire défiler vers la gauche jusqu'au bord du contenu
    .name = Aller tout à gauche

SCROLL_TO_RIGHTMOST_CMD =
    .info = Faire défiler vers la droite jusqu'au bord du contenu
    .name = Aller tout à droite

SCROLL_TO_TOP_CMD =
    .info = Faire défiler vers le haut jusqu'au début du contenu
    .name = Aller en haut

SCROLL_UP_CMD =
    .info = Faire défiler vers le haut d'une unité de défilement
    .name = Faire défiler vers le haut

ZOOM_IN_CMD =
    .name = Zoom avant

ZOOM_OUT_CMD =
    .name = Zoom arrière

ZOOM_RESET_CMD =
    .name = Réinitialiser le zoom

ZOOM_TO_FIT_CMD =
    .name = Zoom adapté au contenu