### Machine translated by `cargo zng l10n`, 4292840b02efe22ea758535122b9d05ba08fe158b1edf04331363016191aab59

### Auto generated by `cargo zng l10n`

message =
    .install = Dit zal {$app} {$version} op uw computer installeren.
    .uninstall = Dit zal {$app} {$version} van uw computer verwijderen.
    .update = Dit zal {$app} op uw computer bijwerken van {$current_version} naar {$new_version}.

title =
    .install = Welkom bij de {$app} Installatiewizard
    .repair = Welkom bij de {$app} Herstelwizard
    .uninstall = Welkom bij de {$app} Verwijderingswizard
    .update = Welkom bij de {$app} Updatewizard