### Machine translated by `cargo zng l10n`, d71191013144b142e5eaea12b0fca3409e50c6d718fac39611285128494e9ee4

### Auto generated by `cargo zng l10n`

## Debug Crash Handler

window =
    .title = {$app} - Збій програми

## Panels

# save-copy-starting-name:
#     default file name
minidump =
    .open-error = Не вдалося відкрити мінідамп.
        {$error}
    .remove-error = Не вдалося видалити мінідамп.
        {$error}
    .save-copy-filter-name = Мінідамп
    .save-copy-starting-name = minidump
    .save-copy-title = Зберегти копію
    .save-error = Не вдалося зберегти копію мінідампу.
        {$error}
    .title = Мінідамп

panic =
    .title = Паніка

stderr =
    .title = Stderr

stdout =
    .title = Stdout

summary =
    .text = Timestamp: {$timestamp}
        Exit Code: {$exit_code}
        Signal: {$signal}
        Stderr: {$stderr_len} bytes
        Stdout: {$stdout_len} bytes
        Panic: {$is_panic}
        Minidump: {$minidump_path}
        
        Args: {$args}
        OS: {$os}
    .title = Підсумок

widget =
    .title = Віджет