### Machine translated by `cargo zng l10n`, 8c9c95d8cf28b2cb9c70f9781ccec7824f959908ffe3f862c4b327a081d61caf

### Auto generated by `cargo zng l10n`

INSPECT_CMD =
    .info = Inspeccionar la ventana
    .name = Inspector de depuración

## Inspector Window (always en-US)

info-help = información del widget observado

intrinsic-help = nodo intrínseco

nest-group-help = grupo de anidación

screenshot =
    .copy-error = Error al copiar la captura de pantalla. {$error}
    .error-dlg-title = Error de captura de pantalla
    .save-dlg-filter = Archivos de imagen
    .save-dlg-starting-name = captura.png
    .save-dlg-title = Guardar captura de pantalla
    .save-error = Error al guardar la captura de pantalla. {$error}

select-widget = seleccione un widget para inspeccionar

window =
    .title = {$inspected_window_title} - Inspector