### Machine translated by `cargo zng l10n`, be135842e65abb43f38e8f66e75bcc43fb249683b92f3d12466fbb444de99621

### Auto generated by `cargo zng l10n`

info =
    .clean = 작업에 실패했습니다. 모든 변경 사항이 취소되었습니다.
    .corrupted = 작업에 실패했습니다. 설치 파일이 손상되었습니다.

message =
    .install-clean = 설치 작업에 실패했습니다. {$app}이(가) 설치되지 않았습니다.
    .install-corrupted = 설치 작업에 실패했습니다. {$app}이(가) 부분적으로만 설치되었습니다.
    .repair-clean = 복구 작업에 실패했습니다. {$app} 설치를 복구하지 못했습니다.
    .repair-corrupted = 복구 작업에 실패했습니다. {$app}이(가) 부분적으로만 복구되었습니다.
    .uninstall-clean = 제거 작업에 실패했습니다. {$app}이(가) 여전히 설치되어 있습니다.
    .uninstall-corrupted = 제거 작업에 실패했습니다. {$app}이(가) 부분적으로만 제거되었습니다.
    .update-clean = 업데이트 작업에 실패했습니다. {$app}이(가) 업데이트되지 않았습니다. 현재 설치된 버전 {$current_version}은(는) 유지되며 계속 사용할 수 있습니다.
    .update-corrupted = 업데이트 작업에 실패했습니다. {$app}이(가) 부분적으로만 업데이트되었습니다.

title =
    .install = 설치 실패
    .repair = 복구 실패
    .uninstall = 제거 실패
    .update = 업데이트 실패