### Machine translated by `cargo zng l10n`, 7e38427d13a824c01f61a40c9cc84343f4089dd04c28a1f541f14d6f9c1dff32

### Auto generated by `cargo zng l10n`

message =
    .install = 귀하의 컴퓨터에 {$app} {$version}을 설치합니다.
    .repair = 귀하의 컴퓨터에 설치된 {$app} {$version}을 복구합니다.
    .uninstall = 귀하의 컴퓨터에서 {$app} {$version}을 제거합니다.
    .update = 귀하의 컴퓨터에서 {$app}을 {$current_version}에서 {$new_version}으로 업데이트합니다.

title =
    .install = {$app} 설치 마법사에 오신 것을 환영합니다
    .repair = {$app} 복구 마법사에 오신 것을 환영합니다
    .uninstall = {$app} 제거 마법사에 오신 것을 환영합니다
    .update = {$app} 업데이트 마법사에 오신 것을 환영합니다