### Machine translated by `cargo zng l10n`, 2abd48f76a022e01c465074590f32305b520f65b9a52b2a63373e4df86ad2381

### Auto generated by `cargo zng l10n`

action-run =
    .info = Suorita {$app}

message =
    .install = Ohjattu toiminto on asentanut ohjelman {$app} {$version} tietokoneellesi.
    .repair = Ohjattu toiminto on korjannut ohjelman {$app} {$version} asennuksen tietokoneellasi.
    .uninstall = Ohjattu toiminto on poistanut ohjelman {$app} {$version} tietokoneeltasi.
    .update = Ohjattu toiminto on päivittänyt ohjelman {$app} versiosta {$current_version} versioon {$new_version} tietokoneellasi.

title =
    .install = {$app} asennettu
    .repair = {$app} korjattu
    .uninstall = {$app} poistettu
    .update = {$app} päivitetty