### Machine translated by `cargo zng l10n`, 7e38427d13a824c01f61a40c9cc84343f4089dd04c28a1f541f14d6f9c1dff32

### Auto generated by `cargo zng l10n`

message =
    .install = Tämä asentaa sovelluksen {$app} {$version} tietokoneellesi.
    .repair = Tämä korjaa sovelluksen {$app} {$version} asennuksen tietokoneellasi.
    .uninstall = Tämä poistaa sovelluksen {$app} {$version} tietokoneeltasi.
    .update = Tämä päivittää sovelluksen {$app} versiosta {$current_version} versioon {$new_version} tietokoneellasi.

title =
    .install = Tervetuloa sovelluksen {$app} asennusohjattuun toimintoon
    .repair = Tervetuloa sovelluksen {$app} korjausohjattuun toimintoon
    .uninstall = Tervetuloa sovelluksen {$app} poisto-ohjattuun toimintoon
    .update = Tervetuloa sovelluksen {$app} päivitysohjattuun toimintoon