### Machine translated by `cargo zng l10n`, f6f3457c31fdbcd5d2453877e9762215770aa27c6e290e4b4b30e0a2f59d484a

### Auto generated by `cargo zng l10n`

# name:
#     Nom de la licence
# user-name:
#     « user » est le paquet qui utilise la licence
license-none =
    .id = <aucune>
    .name = Aucune donnée de licence
    .user-name = <aucune>

search =
    .placeholder = rechercher des licences ({$shortcut})

window =
    .title = {$app} - Licences tierces