### Auto generated by `cargo zng l10n`

try_open_link =
    .copy-path = Copy Path
    .copy-url = Copy Url
    .open-url = Open in Browser
    .reveal-path = Reveal in File Manager
    .reveal-path-macos = Reveal in Finder
    .reveal-path-windows = Reveal in File Explorer
