### Machine translated by `cargo zng l10n`, 3bff0a0f920b53ccdc5a8a62ff6395907be54fe1e4eb7448f218d39230ddc71b

### Auto generated by `cargo zng l10n`

PAGE_DOWN_CMD =
    .info = Vieritä alas yhdellä sivuyksiköllä
    .name = Sivu alas

PAGE_LEFT_CMD =
    .info = Vieritä vasemmalle yhdellä sivuyksiköllä
    .name = Sivu vasemmalle

PAGE_RIGHT_CMD =
    .info = Vieritä oikealle yhdellä sivuyksiköllä
    .name = Sivu oikealle

PAGE_UP_CMD =
    .info = Vieritä ylöspäin yhdellä sivuyksiköllä
    .name = Sivu ylös

SCROLL_DOWN_CMD =
    .info = Vieritä alas yhdellä vierityksiyksiköllä
    .name = Vieritä alas

SCROLL_LEFT_CMD =
    .info = Vieritä vasemmalle yhdellä vierityksiyksiköllä
    .name = Vieritä vasemmalle

SCROLL_RIGHT_CMD =
    .info = Vieritä oikealle yhdellä vierityksiyksiköllä
    .name = Vieritä oikealle

SCROLL_TO_BOTTOM_CMD =
    .info = Vieritä alas sisältöön.
    .name = Vieritä pohjalle

SCROLL_TO_LEFTMOST_CMD =
    .info = Vieritä vasemmalle sisältöalareunaan
    .name = Vieritä vasempaan reunaan

SCROLL_TO_RIGHTMOST_CMD =
    .info = Vieritä oikealle sisältöoikeareunaan
    .name = Vieritä oikeaan reunaan

SCROLL_TO_TOP_CMD =
    .info = Vieritä ylös sisältöön
    .name = Vieritä ylös

SCROLL_UP_CMD =
    .info = Vieritä ylöspäin yhdellä vierityksiyksiköllä
    .name = Vieritä ylös

ZOOM_IN_CMD =
    .name = Zoomaa sisään

ZOOM_OUT_CMD =
    .name = Zoomaa ulos

ZOOM_RESET_CMD =
    .name = Nollaa zoomaus

ZOOM_TO_FIT_CMD =
    .name = Sovita koko näkyviin