### Machine translated by `cargo zng l10n`, 3e9db6ab8a9dbbac14d31c68f744c15e88fd79703c907e34ad6ccc8a803d4847

### Auto generated by `cargo zng l10n`

CLOSE_CMD =
    .info = Pechar a xanela
    .name = Pechar

EXCLUSIVE_FULLSCREEN_CMD =
    .info = Alternar o modo de pantalla completa exclusiva na xanela
    .name = Pantalla completa exclusiva

FULLSCREEN_CMD =
    .info = Alternar o modo de pantalla completa na xanela
    .name = Pantalla completa

MAXIMIZE_CMD =
    .info = Maximizar a xanela
    .name = Maximizar

MINIMIZE_CMD =
    .info = Minimizar a xanela
    .name = Minimizar

RESTORE_CMD =
    .info = Restaurar a xanela ao seu estado anterior non minimizado ou ao seu estado normal
    .name = Restaurar