pub fn pseudo(dir: &str, check: bool, verbose: bool) {
    fluent_pseudo_impl(dir, "pseudo", false, false, check, verbose)
}

pub fn pseudo_mirr(dir: &str, check: bool, verbose: bool) {
    fluent_pseudo_impl(dir, "pseudo-mirr", true, false, check, verbose)
}

pub fn pseudo_wide(dir: &str, check: bool, verbose: bool) {
    fluent_pseudo_impl(dir, "pseudo-wide", false, true, check, verbose)
}

fn fluent_pseudo_impl(dir: &str, to_name: &str, flipped: bool, elongate: bool, check: bool, verbose: bool) {
    crate::l10n::generate_util::generate(
        dir,
        to_name,
        "### Test locale, generated by cargo zng l10n",
        &|s| fluent_pseudo::transform(s, flipped, elongate),
        check,
        verbose,
    )
}
