### Auto generated by `cargo zng l10n`

info =
    .install = Where should {$app} be installed?
    .update-repair-uninstall = Where {$app} is installed.

reset-label = Default Location

select-label = Select Location

title =
    .install = Select Install Location
    .uninstall = Install Location
