### Auto generated by `cargo zng l10n`

default-info =
    .create-shortcut = Create shortcut
    .extract-files = Extract files
    .register-uninstaller = Register uninstaller
    .remove-files = Remove files
    .remove-shortcut = Remove shortcut
    .unregister-uninstaller = Unregister uninstaller

info =
    .install = Please wait while {$app} is installed on your computer.
    .repair = Please wait while {$app} is repaired on your computer.
    .uninstall = Please wait while {$app} is uninstalled from your computer.
    .update = Please wait while {$app} is updated on your computer.

title =
    .install = Installing
    .repair = Repairing
    .uninstall = Uninstalling
    .update = Updating
