### Machine translated by `cargo zng l10n`, ab0682936292139ef046e822c139586a33986c3522951ecb20715ef0c900db4b

### Auto generated by `cargo zng l10n`

FOCUS_ALT_CMD =
    .info = Fokus pada cakupan alt
    .name = Fokus Alt

FOCUS_DOWN_CMD =
    .info = Fokus pada elemen yang dapat difokuskan terdekat ke bawah
    .name = Fokus Bawah

FOCUS_ENTER_CMD =
    .info = Fokus pada elemen anak yang dapat difokuskan
    .name = Fokus Masuk

FOCUS_EXIT_CMD =
    .info = Fokus pada elemen induk yang dapat difokuskan, atau kembalikan fokus
    .name = Fokus Keluar

FOCUS_LEFT_CMD =
    .info = Fokus pada elemen yang dapat difokuskan terdekat ke kiri
    .name = Fokus Kiri

FOCUS_NEXT_CMD =
    .info = Fokus pada elemen yang dapat difokuskan berikutnya
    .name = Fokus Berikutnya

FOCUS_PREV_CMD =
    .info = Fokus pada elemen yang dapat difokuskan sebelumnya
    .name = Fokus Sebelumnya

FOCUS_RIGHT_CMD =
    .info = Fokus pada elemen yang dapat difokuskan terdekat ke kanan
    .name = Fokus Kanan

FOCUS_UP_CMD =
    .info = Fokus pada elemen yang dapat difokuskan terdekat ke atas
    .name = Fokus Atas