### Machine translated by `cargo zng l10n`, 1efe39e07e78c5ca09a02e98644ae77adf5b9afad87a6f8b13dcc8790acc63db

### Auto generated by `cargo zng l10n`

COPY_CMD =
    .info = Kopiraj selekciju u ostavu
    .name = Kopiraj

CUT_CMD =
    .info = Ukloni selekciju i postavi je u ostavu
    .name = Iseci

PASTE_CMD =
    .info = Ubaci sadržaj iz ostave
    .name = Nalepi