### Machine translated by `cargo zng l10n`, 2abd48f76a022e01c465074590f32305b520f65b9a52b2a63373e4df86ad2381

### Auto generated by `cargo zng l10n`

action-run =
    .info = Executar {$app}

message =
    .install = L'assistència ha instal·lat {$app} {$version} en el vostre ordinador.
    .repair = L'assistència ha reparat l'instal·lació de {$app} {$version} en el vostre ordinador.
    .uninstall = L'assistència ha desinstal·lat {$app} {$version} del vostre ordinador.
    .update = L'assistència ha actualitzat {$app} de {$current_version} a {$new_version} en el vostre ordinador.

title =
    .install = {$app} Instal·lat
    .repair = {$app} Reparat
    .uninstall = {$app} Desinstal·lat
    .update = {$app} Actualitzat