### Machine translated by `cargo zng l10n`, 4292840b02efe22ea758535122b9d05ba08fe158b1edf04331363016191aab59

### Auto generated by `cargo zng l10n`

message =
    .install = Això instal·larà {$app} {$version} a l'ordinador.
    .uninstall = Això desinstal·larà {$app} {$version} de l'ordinador.
    .update = Això actualitzarà {$app} de {$current_version} a {$new_version} a l'ordinador.

title =
    .install = Benvingut a l'assistent d'instal·lació de {$app}
    .repair = Benvingut a l'assistent de reparació de {$app}
    .uninstall = Benvingut a l'assistent de desinstal·lació de {$app}
    .update = Benvingut a l'assistent d'actualització de {$app}