### Machine translated by `cargo zng l10n`, 8c9c95d8cf28b2cb9c70f9781ccec7824f959908ffe3f862c4b327a081d61caf

### Auto generated by `cargo zng l10n`

INSPECT_CMD =
    .info = Inspektera fönstret
    .name = Debug-inspektör

## Inspector Window (always en-US)

info-help = Info om övervakad widget

intrinsic-help = Intrinsisk nod

nest-group-help = Nestgrupp

screenshot =
    .copy-error = Skärmdump kopieringsfel. {$error}
    .error-dlg-title = Skärmdumpfel
    .save-dlg-filter = Bildfiler
    .save-dlg-starting-name = screenshot.png
    .save-dlg-title = Spara skärmdump
    .save-error = Skärmdump sparingsfel. {$error}

select-widget = Välj en widget att inspektera

window =
    .title = {$inspected_window_title} - Inspektör