### Machine translated by `cargo zng l10n`, f6f3457c31fdbcd5d2453877e9762215770aa27c6e290e4b4b30e0a2f59d484a

### Auto generated by `cargo zng l10n`

# name:
#     Ime licence
# user-name:
#     "user" je paket, ki uporablja licenco
license-none =
    .id = <brez>
    .name = Ni podatkov o licenci
    .user-name = <brez>

search =
    .placeholder = išči licence ({$shortcut})

window =
    .title = {$app} - Licence tretjih oseb