### Machine translated by `cargo zng l10n`, 3bff0a0f920b53ccdc5a8a62ff6395907be54fe1e4eb7448f218d39230ddc71b

### Auto generated by `cargo zng l10n`

PAGE_DOWN_CMD =
    .info = เลื่อนลงหนึ่งหน่วยหน้า
    .name = Page Down

PAGE_LEFT_CMD =
    .info = เลื่อนซ้ายหนึ่งหน่วยหน้า
    .name = Page Left

PAGE_RIGHT_CMD =
    .info = เลื่อนขวาหนึ่งหน่วยหน้า
    .name = Page Right

PAGE_UP_CMD =
    .info = เลื่อนขึ้นหนึ่งหน่วยหน้า
    .name = Page Up

SCROLL_DOWN_CMD =
    .info = เลื่อนลงหนึ่งหน่วยการเลื่อน
    .name = Scroll Down

SCROLL_LEFT_CMD =
    .info = เลื่อนซ้ายหนึ่งหน่วยการเลื่อน
    .name = Scroll Left

SCROLL_RIGHT_CMD =
    .info = เลื่อนขวาหนึ่งหน่วยการเลื่อน
    .name = Scroll Right

SCROLL_TO_BOTTOM_CMD =
    .info = เลื่อนลงไปยังส่วนล่างของเนื้อหา
    .name = Scroll to Bottom

SCROLL_TO_LEFTMOST_CMD =
    .info = เลื่อนซ้ายไปยังขอบซ้ายของเนื้อหา
    .name = Scroll to Leftmost

SCROLL_TO_RIGHTMOST_CMD =
    .info = เลื่อนขวาไปยังขอบขวาของเนื้อหา
    .name = Scroll to Rightmost

SCROLL_TO_TOP_CMD =
    .info = เลื่อนขึ้นไปยังส่วนบนของเนื้อหา
    .name = Scroll to Top

SCROLL_UP_CMD =
    .info = เลื่อนขึ้นหนึ่งหน่วยการเลื่อน
    .name = Scroll Up

ZOOM_IN_CMD =
    .name = ซูมเข้า

ZOOM_OUT_CMD =
    .name = ซูมออก

ZOOM_RESET_CMD =
    .name = รีเซ็ตการซูม

ZOOM_TO_FIT_CMD =
    .name = ซูมให้พอดี