### Machine translated by `cargo zng l10n`, 3bff0a0f920b53ccdc5a8a62ff6395907be54fe1e4eb7448f218d39230ddc71b

### Auto generated by `cargo zng l10n`

PAGE_DOWN_CMD =
    .info = Rolar para baixo por uma unidade de página
    .name = Página Abaixo

PAGE_LEFT_CMD =
    .info = Rolar para a esquerda por uma unidade de página
    .name = Página Esquerda

PAGE_RIGHT_CMD =
    .info = Rolar para a direita por uma unidade de página
    .name = Página Direita

PAGE_UP_CMD =
    .info = Rolar para cima por uma unidade de página
    .name = Página Acima

SCROLL_DOWN_CMD =
    .info = Rolar para baixo por uma unidade de rolagem
    .name = Rolagem para Baixo

SCROLL_LEFT_CMD =
    .info = Rolar para a esquerda por uma unidade de rolagem
    .name = Rolagem para Esquerda

SCROLL_RIGHT_CMD =
    .info = Rolar para a direita por uma unidade de rolagem
    .name = Rolagem para Direita

SCROLL_TO_BOTTOM_CMD =
    .info = Rolar para baixo até ao fundo do conteúdo.
    .name = Rolar para o Fundo

SCROLL_TO_LEFTMOST_CMD =
    .info = Rolar para a esquerda até à margem esquerda do conteúdo
    .name = Rolar para a Esquerda Mais Distante

SCROLL_TO_RIGHTMOST_CMD =
    .info = Rolar para a direita até à margem direita do conteúdo
    .name = Rolar para a Direita Mais Distante

SCROLL_TO_TOP_CMD =
    .info = Rolar para cima até ao topo do conteúdo
    .name = Rolar para o Topo

SCROLL_UP_CMD =
    .info = Rolar para cima por uma unidade de rolagem
    .name = Rolagem para Cima

ZOOM_IN_CMD =
    .name = Ampliar

ZOOM_OUT_CMD =
    .name = Reduzir Zoom

ZOOM_RESET_CMD =
    .name = Resetar Zoom

ZOOM_TO_FIT_CMD =
    .name = Ajustar ao Tamanho