### Machine translated by `cargo zng l10n`, 3e9db6ab8a9dbbac14d31c68f744c15e88fd79703c907e34ad6ccc8a803d4847

### Auto generated by `cargo zng l10n`

CLOSE_CMD =
    .info = Закрыть окно
    .name = Закрыть

EXCLUSIVE_FULLSCREEN_CMD =
    .info = Переключить эксклюзивный полноэкранный режим окна
    .name = Эксклюзивный полноэкранный

FULLSCREEN_CMD =
    .info = Переключить полноэкранный режим окна
    .name = Полноэкранный

MAXIMIZE_CMD =
    .info = Развернуть окно
    .name = Развернуть

MINIMIZE_CMD =
    .info = Свернуть окно
    .name = Свернуть

RESTORE_CMD =
    .info = Восстановить окно в предыдущее неминимизированное состояние или нормальное состояние
    .name = Восстановить