### Machine translated by `cargo zng l10n`, ca15a8ce25cc0c158873c10a67ae3b8a2387847209565e6c26c99f1cba2d77eb

### Auto generated by `cargo zng l10n`

accept =
    .false = Ne sprejem pogodbe
    .true = Sprejem pogodbo

info =
    .install = Prosim, preverite pogoje licence pred namestitvijo {$app}
    .update = Prosim, preverite pogoje licence pred posodobitvijo {$app}

message = Morate sprejeti pogoje te pogodbe, preden nadaljujete.
    .requires_scroll = Morate prebrati in sprejeti pogoje te pogodbe, preden nadaljujete.

title = Pogodba o licenci