### Machine translated by `cargo zng l10n`, 2abd48f76a022e01c465074590f32305b520f65b9a52b2a63373e4df86ad2381

### Auto generated by `cargo zng l10n`

action-run =
    .info = Pokreni {$app}

message =
    .install = Vizaž je namestil {$app} {$version} na vaš računalnik.
    .repair = Vizaž je popravil namestitev {$app} {$version} na vaš računalnik.
    .uninstall = Vizaž je odstranil {$app} {$version} z vašega računalnika.
    .update = Vizaž je posodobil {$app} iz {$current_version} na {$new_version} na vašem računalniku.

title =
    .install = {$app} Namestit
    .repair = {$app} Popravljen
    .uninstall = {$app} Odstranjen
    .update = {$app} Posodobljen