### Machine translated by `cargo zng l10n`, 86bb0abb6293e164ae596c4745cba0db2da828923ef8061ed99c7bf5ccfa9ddd

### Auto generated by `cargo zng l10n`

default-info =
    .create-shortcut = Ustvariti zakratko
    .extract-files = Izključiti datoteke
    .register-uninstaller = Registrirati odninstalator
    .remove-files = Ukloniti datoteke
    .remove-shortcut = Ukloniti zakratko
    .unregister-uninstaller = Odregistrirati odninstalator

info =
    .install = Prosimo, počakajte, medtem ko je {$app} nameščen na vašem računalniku.
    .repair = Prosimo, počakajte, medtem ko se {$app} popravlja na vašem računalniku.
    .uninstall = Prosimo, počakajte, medtem ko se {$app} odstranjuje z vašega računalnika.
    .update = Prosimo, počakajte, medtem ko se {$app} posodablja na vašem računalniku.

title =
    .install = Nameščanje
    .repair = Popravljanje
    .uninstall = Odstranjevanje
    .update = Posodabljanje