### Machine translated by `cargo zng l10n`, 86bb0abb6293e164ae596c4745cba0db2da828923ef8061ed99c7bf5ccfa9ddd

### Auto generated by `cargo zng l10n`

default-info =
    .create-shortcut = Ustvari bližnjico
    .extract-files = Razširi datoteke
    .register-uninstaller = Registriraj odstranjevalec
    .remove-files = Odstrani datoteke
    .remove-shortcut = Odstrani bližnjico
    .unregister-uninstaller = Odstrani registracijo odstranjevalca

info =
    .install = Prosimo, počakajte, da se {$app} namesti v vaš računalnik.
    .repair = Prosimo, počakajte, da se {$app} popravi v vašem računalniku.
    .uninstall = Prosimo, počakajte, da se {$app} odstrani iz vašega računalnika.
    .update = Prosimo, počakajte, da se {$app} posodobi v vašem računalniku.

title =
    .install = Nameščanje
    .repair = Popravljanje
    .uninstall = Odstranjevanje
    .update = Posodabljanje