### Machine translated by `cargo zng l10n`, 2bbf575c7bf1ae877b1732f1d62041cb9d57d959ec1aca0f05662bbd6d20a92f

### Auto generated by `cargo zng l10n`

# tip on hover of the reset arrow button
reset = Alapértelmezett állapotra visszaállítás

search =
    .no_results = Nincs beállítás található
    .placeholder = Keressési beállítások ({$shortcut})

window =
    .title = {$app} - Beállítások