### Machine translated by `cargo zng l10n`, f7e78c417f90217d5c21cbcda6fabb6faeab7fde745f69268d7dce1a1f8f3772

### Auto generated by `cargo zng l10n`

try_open_link =
    .copy-path = Kopēt ceļu
    .copy-url = Kopēt URL
    .open-url = Atvērt pārlūkprogrammā
    .reveal-path = Rādīt failu pārvaldniekā
    .reveal-path-macos = Rādīt programmā Finder
    .reveal-path-windows = Rādīt failu pārlūkā