### Machine translated by `cargo zng l10n`, 3e9db6ab8a9dbbac14d31c68f744c15e88fd79703c907e34ad6ccc8a803d4847

### Auto generated by `cargo zng l10n`

CLOSE_CMD =
    .info = Zatvori prozor
    .name = Zatvori

EXCLUSIVE_FULLSCREEN_CMD =
    .info = Uključi/isključi ekskluzivni način rada preko cijelog zaslona
    .name = Ekskluzivni puni zaslon

FULLSCREEN_CMD =
    .info = Uključi/isključi način rada preko cijelog zaslona
    .name = Puni zaslon

MAXIMIZE_CMD =
    .info = Maksimiziraj prozor
    .name = Maksimiziraj

MINIMIZE_CMD =
    .info = Minimiziraj prozor
    .name = Minimiziraj

RESTORE_CMD =
    .info = Vraća prozor u prethodno stanje prije minimiziranja ili u normalno stanje
    .name = Vrati izvorno stanje