### Machine translated by `cargo zng l10n`, 8c9c95d8cf28b2cb9c70f9781ccec7824f959908ffe3f862c4b327a081d61caf

### Auto generated by `cargo zng l10n`

INSPECT_CMD =
    .info = Inspecter la fenêtre
    .name = Inspecteur de débogage

## Inspector Window (always en-US)

info-help = Infos du widget surveillé

intrinsic-help = Nœud intrinsèque

nest-group-help = Groupe imbriqué

screenshot =
    .copy-error = Erreur lors de la copie de la capture d'écran. {$error}
    .error-dlg-title = Erreur de capture d'écran
    .save-dlg-filter = Fichiers d'images
    .save-dlg-starting-name = screenshot.png
    .save-dlg-title = Enregistrer la capture d'écran
    .save-error = Erreur d'enregistrement de la capture d'écran. {$error}

select-widget = Sélectionner un widget à inspecter

window =
    .title = {$inspected_window_title} - Inspecteur