### Machine translated by `cargo zng l10n`, 94527aed8f60480f65e908ce1bb46627d277ef4ebd081f0dc4bb2eb5cfcfaf82

### Auto generated by `cargo zng l10n`

action-run =
    .info = Executar {$app}

message =
    .install = O assistente instalou o {$app} {$version} no seu computador.
    .uninstall = O assistente desinstalou o {$app} {$version} do seu computador.
    .update = O assistente atualizou o {$app} de {$current_version} para {$new_version} no seu computador.

title =
    .install = {$app} Instalado
    .repair = {$app} Reparado
    .uninstall = {$app} Desinstalado
    .update = {$app} Atualizado