### Machine translated by `cargo zng l10n`, f66bc3e2d3fe992cf8f2ec38a95f5c05828baae1f65d73e015906b4eebfe2254

### Auto generated by `cargo zng l10n`

### Valid gesture key names
### 
### * The ID is the `Key` variant name. [1]
### * An OS generic text must be provided, optional OS specific text can be set as attributes.
### * OS attribute is a `std::env::consts::OS` value. [2]
### * L10n not include Char, Str, modifiers and composite keys.
### 
### Note: This file does not include all valid keys, see [1] for a full list.
### 
### [1]: https://zng-ui.github.io/doc/zng/keyboard/enum.Key.html
### [2]: https://doc.rust-lang.org/std/env/consts/constant.OS.html

ArrowDown = ↓

ArrowLeft = ←

ArrowRight = →

ArrowUp = ↑

Backspace = ←Askelpalautin
    .macos = Delete

Close = Sulje

ContextMenu = ≣Kontekstivalikko

Copy = Kopioi

Cut = Leikkaa

Delete = Poista
    .macos = Forward Delete

Eject = ⏏Poista levy

Enter = ↵Enter
    .macos = ↵Return

Escape = Esc

Find = Etsi

Help = ?Ohje

New = Uusi

Open = Avaa

PageDown = PgDn

PageUp = PgUp

Paste = Liitä

Print = Tulosta

PrintScreen = PrtSc

Redo = Tee uudelleen

Save = Tallenna

Tab = ⭾Sarkain

Undo = Kumoa

ZoomIn = +Lähennä

ZoomOut = -Loitonna