### Machine translated by `cargo zng l10n`, 2bbf575c7bf1ae877b1732f1d62041cb9d57d959ec1aca0f05662bbd6d20a92f

### Auto generated by `cargo zng l10n`

# रिसेट एरो बटन पर होवर करने पर टिप
reset = डिफ़ॉल्ट पर रीसेट करें

search =
    .no_results = कोई सेटिंग नहीं मिली
    .placeholder = सेटिंग्स खोजें ({$shortcut})

window =
    .title = {$app} - सेटिंग्स