### Machine translated by `cargo zng l10n`, 08fd454f1bfe552e85c1338a6842b18e91dd13c7e3b2949c8b5dc77f1e0c9f8c

### Auto generated by `cargo zng l10n`

info =
    .install = ¿Dónde debería instalarse {$app}?
    .update-repair-uninstall = Dónde está instalado {$app}.

# $bytes is already formatted e.g.: 900kB or 50MB.
min-required-space = Se requiere al menos {$bytes} de espacio libre en disco.

reset-label = Ubicación predeterminada

select-label = Seleccionar ubicación

title =
    .install = Seleccionar ubicación de instalación
    .uninstall = Ubicación de instalación