### Machine translated by `cargo zng l10n`, d71191013144b142e5eaea12b0fca3409e50c6d718fac39611285128494e9ee4

### Auto generated by `cargo zng l10n`

## Debug Crash Handler

window =
    .title = {$app} – Sovellus kaatui

## Panels

# save-copy-starting-name:
#     default file name
minidump =
    .open-error = Minidumpin avaaminen epäonnistui.
        {$error}
    .remove-error = Minidumpin poistaminen epäonnistui.
        {$error}
    .save-copy-filter-name = Minidump
    .save-copy-starting-name = minidump
    .save-copy-title = Tallenna kopio
    .save-error = Minidump-kopion tallentaminen epäonnistui.
        {$error}
    .title = Minidump

panic =
    .title = Virhetilanne (Panic)

stderr =
    .title = Stderr

stdout =
    .title = Stdout

summary =
    .text = Aikaleima: {$timestamp}
        Poistumiskoodi: {$exit_code}
        Signaali: {$signal}
        Stderr: {$stderr_len} tavua
        Stdout: {$stdout_len} tavua
        Virhetilanne: {$is_panic}
        Minidump: {$minidump_path}
        
        Argumentit: {$args}
        Käyttöjärjestelmä: {$os}
    .title = Yhteenveto

widget =
    .title = Widget