### Machine translated by `cargo zng l10n`, 8c9c95d8cf28b2cb9c70f9781ccec7824f959908ffe3f862c4b327a081d61caf

### Auto generated by `cargo zng l10n`

INSPECT_CMD =
    .info = Pregledaj prozor
    .name = Debug Inspector

## Inspector Window (always en-US)

info-help = Informacije o pratioćem vidžetu

intrinsic-help = Intrinsični čvor

nest-group-help = Grupa ugnježdenih elemenata

screenshot =
    .copy-error = Greška pri kopiranju snimka. {$error}
    .error-dlg-title = Greška pri snimku
    .save-dlg-filter = Datoteke slika
    .save-dlg-starting-name = screenshot.png
    .save-dlg-title = Sačuvaj snimak ekrana
    .save-error = Greška pri snimanju. {$error}

select-widget = Izaberite vidžet za pregled

window =
    .title = {$inspected_window_title} - Inspector