### Machine translated by `cargo zng l10n`, be135842e65abb43f38e8f66e75bcc43fb249683b92f3d12466fbb444de99621

### Auto generated by `cargo zng l10n`

info =
    .clean = L'opération a échoué, toutes les modifications ont été annulées.
    .corrupted = L'opération a échoué, l'installation est corrompue.

message =
    .install-clean = L'installation a échoué, {$app} n'a pas été installé.
    .install-corrupted = L'installation a échoué, {$app} n'a été installé que partiellement.
    .repair-clean = La réparation a échoué, l'installation de {$app} n'a pas été réparée.
    .repair-corrupted = La réparation a échoué, l'installation de {$app} n'a été réparée que partiellement.
    .uninstall-clean = La désinstallation a échoué, {$app} demeure installé.
    .uninstall-corrupted = La désinstallation a échoué, {$app} n'a été désinstallé que partiellement.
    .update-clean = La mise à jour a échoué, {$app} n'a pas été mis à jour. La version {$current_version} actuellement installée demeure disponible et peut toujours être utilisée.
    .update-corrupted = La mise à jour a échoué, {$app} n'a été mis à jour que partiellement.

title =
    .install = Échec de l'installation
    .repair = Échec de la réparation
    .uninstall = Échec de la désinstallation
    .update = Échec de la mise à jour