### Machine translated by `cargo zng l10n`, 86bb0abb6293e164ae596c4745cba0db2da828923ef8061ed99c7bf5ccfa9ddd

### Auto generated by `cargo zng l10n`

default-info =
    .create-shortcut = Créer un raccourci
    .extract-files = Extraire les fichiers
    .register-uninstaller = Enregistrer le désinstalleur
    .remove-files = Supprimer les fichiers
    .remove-shortcut = Supprimer le raccourci
    .unregister-uninstaller = Désenregistrer le désinstalleur

info =
    .install = Veuillez patienter pendant que {$app} est installé sur votre ordinateur.
    .repair = Veuillez patienter pendant que {$app} est réparé sur votre ordinateur.
    .uninstall = Veuillez patienter pendant que {$app} est désinstallé de votre ordinateur.
    .update = Veuillez patienter pendant que {$app} est mis à jour sur votre ordinateur.

title =
    .install = Installation
    .repair = Réparation
    .uninstall = Désinstallation
    .update = Mise à jour