### Machine translated by `cargo zng l10n`, 1efe39e07e78c5ca09a02e98644ae77adf5b9afad87a6f8b13dcc8790acc63db

### Auto generated by `cargo zng l10n`

COPY_CMD =
    .info = Copiar a selección ao portapapeis
    .name = Copiar

CUT_CMD =
    .info = Cortar a selección e poñela no portapapeis
    .name = Cortar

PASTE_CMD =
    .info = Inserir o contido do portapapeis
    .name = Pegar