### Machine translated by `cargo zng l10n`, 3e9db6ab8a9dbbac14d31c68f744c15e88fd79703c907e34ad6ccc8a803d4847

### Auto generated by `cargo zng l10n`

CLOSE_CMD =
    .info = Zatvori prozor
    .name = Zatvori

EXCLUSIVE_FULLSCREEN_CMD =
    .info = Uključi/isključi ekskluzivni režim preko celog ekrana
    .name = Ekskluzivni režim preko celog ekrana

FULLSCREEN_CMD =
    .info = Uključi/isključi režim preko celog ekrana
    .name = Preko celog ekrana

MAXIMIZE_CMD =
    .info = Maksimizuj prozor
    .name = Maksimizuj

MINIMIZE_CMD =
    .info = Minimizuj prozor
    .name = Minimizuj

RESTORE_CMD =
    .info = Vraća prozor u prethodno stanje pre minimizacije ili u normalno stanje
    .name = Vrati