### Machine translated by `cargo zng l10n`, 8c9c95d8cf28b2cb9c70f9781ccec7824f959908ffe3f862c4b327a081d61caf

### Auto generated by `cargo zng l10n`

INSPECT_CMD =
    .info = Zkontrolovat okno
    .name = Ladicí inspektor

## Inspector Window (always en-US)

info-help = informace o sledovaném widgetu

intrinsic-help = vnitřní uzel

nest-group-help = skupina vnoření

screenshot =
    .copy-error = Chyba při kopírování snímku obrazovky. {$error}
    .error-dlg-title = Chyba snímku obrazovky
    .save-dlg-filter = Obrázkové soubory
    .save-dlg-starting-name = snimek_obrazovky.png
    .save-dlg-title = Uložit snímek obrazovky
    .save-error = Chyba při ukládání snímku obrazovky. {$error}

select-widget = vyberte widget ke kontrole

window =
    .title = {$inspected_window_title} - Inspektor