### Machine translated by `cargo zng l10n`, 0b1afb2b50bb026726c0531d85ae2f8c2ce81c3ae17e93445959e2db7ce271bc

### Auto generated by `cargo zng l10n`

### Valid gesture key names
### 
### * The ID is the `Key` variant name. [1]
### * An OS generic text must be provided, optional OS specific text can be set as attributes.
### * OS attribute is a `std::env::consts::OS` value. [2]
### * L10n not include Char, Str, modifiers and composite keys.
### 
### Note: This file does not include all valid keys, see [1] for a full list.
### 
### [1]: https://zng-ui.github.io/doc/zng/keyboard/enum.Key.html
### [2]: https://doc.rust-lang.org/std/env/consts/constant.OS.html

ArrowDown = ↓

ArrowLeft = ←

ArrowRight = →

ArrowUp = ↑

Backspace = ←退格键
    .macos = Delete

Close = 关闭

ContextMenu = ≣右键菜单

Copy = 复制

Cut = 剪切

Delete = 删除
    .macos = 向前删除

Eject = ⏏弹出

Enter = ↵回车
    .macos = ↵Return

Escape = Esc

Find = 查找

Help = ?帮助

New = 新建

Open = 打开

PageDown = 下一页

PageUp = 上一页

Paste = 粘贴

PrintScreen = 截屏

Redo = 重做

Save = 保存

Tab = ⭾制表键

Undo = 撤销

ZoomIn = +放大

ZoomOut = -缩小