### Machine translated by `cargo zng l10n`, 94527aed8f60480f65e908ce1bb46627d277ef4ebd081f0dc4bb2eb5cfcfaf82

### Auto generated by `cargo zng l10n`

action-run =
    .info = Kjør {$app}

message =
    .install = Veiviseren har installert {$app} {$version} på datamaskinen din.
    .uninstall = Veiviseren har avinstallert {$app} {$version} fra datamaskinen din.
    .update = Veiviseren har oppdatert {$app} fra {$current_version} til {$new_version} på datamaskinen din.

title =
    .install = {$app} installert
    .repair = {$app} reparert
    .uninstall = {$app} avinstallert
    .update = {$app} oppdatert