### Machine translated by `cargo zng l10n`, 8c9c95d8cf28b2cb9c70f9781ccec7824f959908ffe3f862c4b327a081d61caf

### Auto generated by `cargo zng l10n`

INSPECT_CMD =
    .info = 창 검사
    .name = 디버그 인스펙터

## Inspector Window (always en-US)

info-help = 모니터링된 위젯 정보

intrinsic-help = 본질 노드

nest-group-help = 중첩 그룹

screenshot =
    .copy-error = 스크린샷 복사 오류입니다. {$error}
    .error-dlg-title = 스크린샷 오류
    .save-dlg-filter = 이미지 파일
    .save-dlg-starting-name = screenshot.png
    .save-dlg-title = 스크린샷 저장
    .save-error = 스크린샷 저장 오류입니다. {$error}

select-widget = 검사할 위젯을 선택하십시오.

window =
    .title = {$inspected_window_title} - 인스펙터