### Machine translated by `cargo zng l10n`, d71191013144b142e5eaea12b0fca3409e50c6d718fac39611285128494e9ee4

### Auto generated by `cargo zng l10n`

## Debug Crash Handler

window =
    .title = {$app} - Colapso da aplicación

## Panels

# save-copy-starting-name:
#     default file name
minidump =
    .open-error = Fallou abrir minidump.
        {$error}
    .remove-error = Fallou remover minidump.
        {$error}
    .save-copy-filter-name = Minidump
    .save-copy-starting-name = minidump
    .save-copy-title = Guardar Copia
    .save-error = Fallou guardar a copia do minidump.
        {$error}
    .title = Minidump

panic =
    .title = Pánico

stderr =
    .title = Stderr

stdout =
    .title = Stdout

summary =
    .text = Marcador de tempo: {$timestamp}
        Código de saída: {$exit_code}
        Sinal: {$signal}
        Stderr: {$stderr_len} bytes
        Stdout: {$stdout_len} bytes
        Pánico: {$is_panic}
        Minidump: {$minidump_path}
        
        Argumentos: {$args}
        S.O.: {$os}
    .title = Resumo

widget =
    .title = Widget