### Machine translated by `cargo zng l10n`, 0b1afb2b50bb026726c0531d85ae2f8c2ce81c3ae17e93445959e2db7ce271bc

### Auto generated by `cargo zng l10n`

### Valid gesture key names
### 
### * The ID is the `Key` variant name. [1]
### * An OS generic text must be provided, optional OS specific text can be set as attributes.
### * OS attribute is a `std::env::consts::OS` value. [2]
### * L10n not include Char, Str, modifiers and composite keys.
### 
### Note: This file does not include all valid keys, see [1] for a full list.
### 
### [1]: https://zng-ui.github.io/doc/zng/keyboard/enum.Key.html
### [2]: https://doc.rust-lang.org/std/env/consts/constant.OS.html

ArrowDown = ↓

ArrowLeft = ←

ArrowRight = →

ArrowUp = ↑

Backspace = ←Backspace
    .macos = Delete

Close = 閉じる

ContextMenu = ≣コンテキストメニュー

Copy = コピー

Cut = 切り取り

Delete = 削除
    .macos = Forward Delete

Eject = ⏏イジェクト

Enter = ↵Enter
    .macos = ↵Return

Escape = Esc

Find = 検索

Help = ?ヘルプ

New = 新規作成

Open = 開く

PageDown = PgDn

PageUp = PgUp

Paste = 貼り付け

PrintScreen = PrintScreen

Redo = やり直し

Save = 保存

Tab = ⭾Tab

Undo = 元に戻す

ZoomIn = +拡大

ZoomOut = -縮小