### Machine translated by `cargo zng l10n`, d71191013144b142e5eaea12b0fca3409e50c6d718fac39611285128494e9ee4

### Auto generated by `cargo zng l10n`

## Debug Crash Handler

window =
    .title = {$app} - היישום קרס

## Panels

# save-copy-starting-name:
#     default file name
minidump =
    .open-error = נכשל בפתיחת ה-minidump.
        {$error}
    .remove-error = נכשל בהסרת ה-minidump.
        {$error}
    .save-copy-filter-name = Minidump
    .save-copy-starting-name = minidump
    .save-copy-title = שמירת עותק
    .save-error = נכשל בשמירת עותק ה-minidump.
        {$error}
    .title = Minidump

panic =
    .title = קריסה (Panic)

stderr =
    .title = Stderr

stdout =
    .title = Stdout

summary =
    .text = חותמת זמן: {$timestamp}
        קוד יציאה: {$exit_code}
        אות (Signal): {$signal}
        Stderr: {$stderr_len} בתים
        Stdout: {$stdout_len} בתים
        קריסה (Panic): {$is_panic}
        Minidump: {$minidump_path}
        
        ארגומנטים: {$args}
        מערכת הפעלה: {$os}
    .title = סיכום

widget =
    .title = ווידג'ט