### Machine translated by `cargo zng l10n`, ab0682936292139ef046e822c139586a33986c3522951ecb20715ef0c900db4b

### Auto generated by `cargo zng l10n`

FOCUS_ALT_CMD =
    .info = Fokusoen galidea (scope)
    .name = Alt Fokusua

FOCUS_DOWN_CMD =
    .info = Fokuso hilerriko (focusable) hilerriko goehera
    .name = Fokuso Goehera

FOCUS_ENTER_CMD =
    .info = Fokuso haurrera (child) hilerriko
    .name = Fokuso Sartu

FOCUS_EXIT_CMD =
    .info = Fokuso gizartea (parent) hilerriko edo fokusa itzultzea
    .name = Fokuso Izultzea

FOCUS_LEFT_CMD =
    .info = Fokuso hilerriko (focusable) hilerriko ezera
    .name = Fokuso Ezera

FOCUS_NEXT_CMD =
    .info = Fokuso hilerriko (focusable) hurrengo
    .name = Fokuso Hurrengo

FOCUS_PREV_CMD =
    .info = Fokuso hilerriko (focusable) aurrekoa
    .name = Fokuso Aurrekoa

FOCUS_RIGHT_CMD =
    .info = Fokuso hilerriko (focusable) hilerriko esera
    .name = Fokuso Esera

FOCUS_UP_CMD =
    .info = Fokuso hilerriko (focusable) hilerriko goraka
    .name = Fokuso Goraka