### Machine translated by `cargo zng l10n`, ab0682936292139ef046e822c139586a33986c3522951ecb20715ef0c900db4b

### Auto generated by `cargo zng l10n`

FOCUS_ALT_CMD =
    .info = Fokuaren ordezko esparrua
    .name = Foku Alternatiboa

FOCUS_DOWN_CMD =
    .info = Beherantz dagoen foku-elementu hurbilena
    .name = Fokua Behera

FOCUS_ENTER_CMD =
    .info = Haur-elementu fokagarria hautatu
    .name = Fokua Sartu

FOCUS_EXIT_CMD =
    .info = Guraso-elementu fokagarria hautatu, edo fokua itzuli
    .name = Fokua Irten

FOCUS_LEFT_CMD =
    .info = Ezkerrerantz dagoen foku-elementu hurbilena
    .name = Fokua Ezkerrera

FOCUS_NEXT_CMD =
    .info = Hurrengo foku-elementua hautatu
    .name = Hurrengo Fokua

FOCUS_PREV_CMD =
    .info = Aurreko foku-elementua hautatu
    .name = Aurreko Fokua

FOCUS_RIGHT_CMD =
    .info = Eskinerantz dagoen foku-elementu hurbilena
    .name = Fokua Eskuinera

FOCUS_UP_CMD =
    .info = Gorantz dagoen foku-elementu hurbilena
    .name = Fokua Gora