//! Widget info tree.

use std::{
    borrow::Cow,
    cell::{Cell, RefCell},
    fmt, mem,
    ops::{self, ControlFlow},
    rc::Rc,
};

use ego_tree::Tree;

use crate::{
    border::ContextBorders,
    context::{InfoContext, LayoutContext, LayoutMetricsSnapshot, OwnedStateMap, StateMap, Updates},
    crate_util::{IdMap, IdSet},
    event::EventUpdateArgs,
    handler::WidgetHandler,
    impl_from_and_into_var,
    units::*,
    var::{Var, VarValue, VarsRead, WithVarsRead},
    window::WindowId,
    UiNode, Widget, WidgetId,
};

mod path;
pub use path::*;

mod builder;
pub use builder::*;

pub mod iter;
pub use iter::TreeFilter;

mod spatial;

unique_id_64! {
    /// Identifies a [`WidgetInfoTree`] snapshot, can be use for more speedy [`WidgetPath`] resolution.
    struct WidgetInfoTreeId;
}

/// Bundle of widget info data from the current widget.
#[derive(Clone, Default)]
pub struct WidgetContextInfo {
    /// Bounds layout info.
    pub bounds: WidgetBoundsInfo,
    /// Border and corners info.
    pub border: WidgetBorderInfo,
}
impl WidgetContextInfo {
    /// New default.
    pub fn new() -> Self {
        Self::default()
    }
}

/// A tree of [`WidgetInfo`].
///
/// The tree is behind an `Rc` pointer so cloning and storing this type is very cheap.
///
/// Instantiated using [`WidgetInfoBuilder`].
#[derive(Clone)]
pub struct WidgetInfoTree(Rc<WidgetInfoTreeInner>);
struct WidgetInfoTreeInner {
    id: WidgetInfoTreeId,
    window_id: WindowId,
    tree: Tree<WidgetInfoData>,
    inner_bounds_tree: RefCell<spatial::QuadTree>,
    lookup: IdMap<WidgetId, ego_tree::NodeId>,
    interactivity_filters: InteractivityFilters,
}
impl PartialEq for WidgetInfoTree {
    fn eq(&self, other: &Self) -> bool {
        self.0.id == other.0.id
    }
}
impl Eq for WidgetInfoTree {}
impl WidgetInfoTree {
    /// Blank window that contains only the root widget taking no space.
    pub fn blank(window_id: WindowId, root_id: WidgetId) -> Self {
        WidgetInfoBuilder::new(window_id, root_id, WidgetBoundsInfo::new(), WidgetBorderInfo::new(), None)
            .finalize()
            .0
    }

    /// Reference to the root widget in the tree.
    pub fn root(&self) -> WidgetInfo {
        WidgetInfo::new(self, self.0.tree.root().id())
    }

    /// All widgets including `root`.
    pub fn all_widgets(&self) -> impl Iterator<Item = WidgetInfo> {
        self.0.tree.root().descendants().map(move |n| WidgetInfo::new(self, n.id()))
    }

    /// Id of the window that owns all widgets represented in the tree.
    pub fn window_id(&self) -> WindowId {
        self.0.window_id
    }

    /// Reference to the widget in the tree, if it is present.
    pub fn find(&self, widget_id: impl Into<WidgetId>) -> Option<WidgetInfo> {
        self.0
            .lookup
            .get(&widget_id.into())
            .and_then(|i| self.0.tree.get(*i).map(|n| WidgetInfo::new(self, n.id())))
    }

    /// If the tree contains the widget.
    pub fn contains(&self, widget_id: impl Into<WidgetId>) -> bool {
        self.0.lookup.contains_key(&widget_id.into())
    }

    /// Reference to the widget in the tree, if it is present.
    ///
    /// Faster then [`find`](Self::find) if the widget path was generated by `self`.
    pub fn get(&self, path: &WidgetPath) -> Option<WidgetInfo> {
        if let Some((tree_id, id)) = path.node_id {
            if tree_id == self.0.id {
                return self.0.tree.get(id).map(|n| WidgetInfo::new(self, n.id()));
            }
        }

        self.find(path.widget_id())
    }

    /// Reference to the widget or first parent that is present.
    pub fn get_or_parent(&self, path: &WidgetPath) -> Option<WidgetInfo> {
        self.get(path)
            .or_else(|| path.ancestors().iter().rev().find_map(|&id| self.find(id)))
    }

    /// If the widgets in this tree have been rendered at least once, after the first render the widget bounds info are always up-to-date
    /// and spatial queries can be made on the widgets.
    pub fn is_rendered(&self) -> bool {
        !self.0.inner_bounds_tree.borrow().is_empty()
    }

    /// Enveloping bounds of all inner bounds rendered in this tree, visitors outside these bounds never find any widget.
    pub fn visit_bounds(&self) -> euclid::Box2D<Px, ()> {
        self.0.inner_bounds_tree.borrow().bounds()
    }

    /// Visit widgets by the [`inner_bounds`] quad-tree.
    ///
    /// Only widgets inside the areas allowed by `include_quad` are visited, the `visit` closure is called for every widget contained by the
    /// allowed quads and can either continue visiting or break early with a result. Each widget can be visited multiple times if more then one
    /// parallel quad is allowed, if only nested quads are allowed (like in a point hit-test) then widgets are only visited once. You can use
    /// [`visit_quads_dedup`] to ensure that widgets are only visited once.
    ///
    /// Note that no widget is visited before the first render as the quad-tree is only build after the first render, you can check if the tree is
    /// rendered using [`is_rendered`].
    ///
    /// [`inner_bounds`]: WidgetInfo::inner_bounds
    /// [`is_rendered`]: Self::is_rendered
    /// [`visit_quads_dedup`]: Self::visit_quads_dedup
    pub fn visit_quads<'a, B>(
        &'a self,
        include_quad: impl FnMut(euclid::Box2D<Px, ()>) -> bool,
        mut visit: impl FnMut(WidgetInfo<'a>) -> ControlFlow<B>,
    ) -> ControlFlow<B> {
        self.0
            .inner_bounds_tree
            .borrow()
            .visit(include_quad, move |node_id| visit(WidgetInfo::new(self, node_id)))
    }

    /// Like [`visit_quads`], but ensures that widgets are only visited once.
    ///
    /// [`visit_quads`]: Self::visit_quads
    pub fn visit_quads_dedup<'a, B>(
        &'a self,
        include_quad: impl FnMut(euclid::Box2D<Px, ()>) -> bool,
        mut visit: impl FnMut(WidgetInfo<'a>) -> ControlFlow<B>,
    ) -> ControlFlow<B> {
        self.0
            .inner_bounds_tree
            .borrow()
            .visit_dedup(include_quad, move |node_id| visit(WidgetInfo::new(self, node_id)))
    }

    /// Visit all widgets in quads that contain the `point`.
    ///
    /// Note that this is slightly faster then [`visit_quads`] and there are naturally no repeated widgets for single point queries.
    ///
    /// [`visit_quads`]: Self::visit_quads
    pub fn visit_point<'a, B>(&'a self, point: PxPoint, mut visit: impl FnMut(WidgetInfo<'a>) -> ControlFlow<B>) -> ControlFlow<B> {
        self.0
            .inner_bounds_tree
            .borrow()
            .visit_point(point, move |node_id| visit(WidgetInfo::new(self, node_id)))
    }

    fn visit_area_op<'a, B>(
        &'a self,
        area: PxRect,
        op: impl Fn(euclid::Box2D<Px, ()>, euclid::Box2D<Px, ()>) -> bool,
        mut visit: impl FnMut(WidgetInfo<'a>) -> ControlFlow<B>,
    ) -> ControlFlow<B> {
        let area = area.to_box2d();
        self.visit_quads_dedup(
            |q| op(area, q),
            |wgt| {
                if op(area, wgt.inner_bounds().to_box2d()) {
                    return visit(wgt);
                }
                ControlFlow::Continue(())
            },
        )
    }

    /// Visit all widgets with [`inner_bounds`] that intersect the `area`, widgets are only visited once.
    ///
    /// [`inner_bounds`]: WidgetInfo::inner_bounds
    pub fn visit_intersects<'a, B>(&'a self, area: PxRect, visit: impl FnMut(WidgetInfo<'a>) -> ControlFlow<B>) -> ControlFlow<B> {
        self.visit_area_op(area, |area, q| area.intersects(&q), visit)
    }

    /// Visit all widgets with [`inner_bounds`] that contains the `point`, widgets are only visited once.
    ///
    /// [`inner_bounds`]: WidgetInfo::inner_bounds
    pub fn visit_contains<'a, B>(&'a self, point: PxPoint, mut visit: impl FnMut(WidgetInfo<'a>) -> ControlFlow<B>) -> ControlFlow<B> {
        self.visit_point(point, |wgt| {
            if wgt.inner_bounds().contains(point) {
                return visit(wgt);
            }
            ControlFlow::Continue(())
        })
    }

    /// Visit all widgets with [`inner_bounds`] that are fully inside the `area`, widgets are only visited once.
    ///
    /// [`inner_bounds`]: WidgetInfo::inner_bounds
    pub fn visit_contained<'a, B>(&'a self, area: PxRect, visit: impl FnMut(WidgetInfo<'a>) -> ControlFlow<B>) -> ControlFlow<B> {
        self.visit_area_op(area, |area, q| area.contains_box(&q), visit)
    }

    /// Visit all widgets with [`inner_bounds`] that fully envelops the `area`, widgets are only visited once.
    ///
    /// [`inner_bounds`]: WidgetInfo::inner_bounds
    pub fn visit_contains_area<'a, B>(&'a self, area: PxRect, visit: impl FnMut(WidgetInfo<'a>) -> ControlFlow<B>) -> ControlFlow<B> {
        self.visit_area_op(area, |area, q| q.contains_box(&area), visit)
    }

    /// Visit all widgets with [`center`] inside the `area`, widgets are only visited once.
    ///
    /// [`center`]: WidgetInfo::center
    pub fn visit_center_contained<'a, B>(
        &'a self,
        area: PxRect,
        mut visit: impl FnMut(WidgetInfo<'a>) -> ControlFlow<B>,
    ) -> ControlFlow<B> {
        let area = area.to_box2d();
        self.visit_quads_dedup(
            |q| q.intersects(&area),
            |wgt| {
                if area.contains(wgt.center()) {
                    return visit(wgt);
                }
                ControlFlow::Continue(())
            },
        )
    }

    /// Visit all widgets with [`center`] in the direction defined by `orientation` and within the `distance`, widgets are only visited once
    /// and the distance is clipped by the [`visit_bounds`], use [`Px::MAX`] on the distance to visit all widgets in the direction.
    ///
    /// The first parameter of `visit` is the current search quadrant, each subsequent quadrants is double in size and further away
    /// from the `origin` by the length of the previous search quadrant, this means that every time the search quadrant changes all
    /// visited widgets are further away from `origin` then all widgets from the previous quadrant.
    ///
    /// [`center`]: WidgetInfo::center
    /// [`visit_bounds`]: Self::visit_bounds
    pub fn visit_oriented<'a, B>(
        &'a self,
        origin: PxPoint,
        distance: Px,
        orientation: WidgetOrientation,
        mut visit: impl FnMut(PxRect, WidgetInfo<'a>) -> ControlFlow<B>,
    ) -> ControlFlow<B> {
        let limit = self.visit_bounds();
        let limit = match orientation {
            WidgetOrientation::Above => origin.y - limit.min.y,
            WidgetOrientation::Right => limit.max.x - origin.x,
            WidgetOrientation::Below => limit.max.y - origin.y,
            WidgetOrientation::Left => origin.x - limit.min.x,
        };
        let actual_distance = distance.min(limit);

        if distance < Px::MAX {
            let ds_max = distance.0 as f32;
            let ds_origin = origin.to_f32();
            for r in orientation.search_bounds(origin, actual_distance) {
                self.visit_center_contained(r, |w| {
                    let center = w.center();
                    if orientation.is(origin, center) && ds_origin.distance_to(center.to_f32()) <= ds_max {
                        visit(r, w)?;
                    }
                    ControlFlow::Continue(())
                })?;
            }
        } else {
            for r in orientation.search_bounds(origin, actual_distance) {
                self.visit_center_contained(r, |w| {
                    if orientation.is(origin, w.center()) {
                        visit(r, w)?;
                    }
                    ControlFlow::Continue(())
                })?;
            }
        }

        ControlFlow::Continue(())
    }

    pub(crate) fn after_render(&self) {
        let _span = tracing::trace_span!("info_after_render").entered();
        let _time = measure_time!("quad-tree rebuild");

        let mut quad_tree = self.0.inner_bounds_tree.borrow_mut();
        quad_tree.clear();
        for node in self.0.tree.nodes() {
            quad_tree.insert(node.id(), node.value().bounds_info.inner_bounds());
        }
    }

    pub(crate) fn after_render_update(&self) {
        self.after_render();
    }
}
impl fmt::Debug for WidgetInfoTree {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        let nl = if f.alternate() { "\n   " } else { " " };

        write!(
            f,
            "WidgetInfoTree(Rc<{{{nl}id: {},{nl}window_id: {},{nl}widget_count: {},{nl}...}}>)",
            self.0.id.sequential(),
            self.0.window_id,
            self.0.lookup.len(),
            nl = nl
        )
    }
}

#[derive(Default, Debug)]
struct WidgetBoundsData {
    prev_offsets_pass: Cell<LayoutPassId>,
    prev_outer_offset: Cell<PxVector>,
    prev_inner_offset: Cell<PxVector>,
    prev_child_offset: Cell<PxVector>,
    working_pass: Cell<LayoutPassId>,

    outer_offset: Cell<PxVector>,
    inner_offset: Cell<PxVector>,
    child_offset: Cell<PxVector>,
    offsets_pass: Cell<LayoutPassId>,

    childs_changed: Cell<bool>,

    measure_outer_size: Cell<PxSize>,
    outer_size: Cell<PxSize>,
    inner_size: Cell<PxSize>,
    baseline: Cell<Px>,
    inner_offset_baseline: Cell<bool>,

    measure_metrics: Cell<Option<LayoutMetricsSnapshot>>,
    measure_metrics_used: Cell<LayoutMask>,
    metrics: Cell<Option<LayoutMetricsSnapshot>>,
    metrics_used: Cell<LayoutMask>,

    outer_transform: Cell<RenderTransform>,
    inner_transform: Cell<RenderTransform>,
    rendered: Cell<bool>,

    outer_bounds: Cell<PxRect>,
    inner_bounds: Cell<PxRect>,
}

/// Shared reference to layout size and offsets of a widget and rendered transforms and bounds.
///
/// Can be retrieved in the [`WidgetContextInfo`] and [`WidgetInfo`].
#[derive(Default, Clone, Debug)]
pub struct WidgetBoundsInfo(Rc<WidgetBoundsData>);
impl WidgetBoundsInfo {
    /// New default.
    pub fn new() -> Self {
        Self::default()
    }

    /// Constructor for tests.
    #[cfg(test)]
    #[cfg_attr(doc_nightly, doc(cfg(test)))]
    pub fn new_test(
        inner: PxRect,
        outer: Option<PxRect>,
        outer_transform: Option<RenderTransform>,
        inner_transform: Option<RenderTransform>,
    ) -> Self {
        let r = Self::default();
        r.set_inner_offset(inner.origin.to_vector());
        r.set_inner_size(inner.size);

        if let Some(outer) = outer {
            r.set_outer_offset(outer.origin.to_vector());
            r.set_outer_size(outer.size);
        }

        if let Some(transform) = outer_transform {
            r.set_outer_transform(transform);
        }
        if let Some(transform) = inner_transform {
            r.set_inner_transform(transform);
        }

        r.set_rendered(true);

        r
    }

    /// New info with bound sizes known.
    pub fn new_size(outer: PxSize, inner: PxSize) -> Self {
        let me = Self::new();
        me.set_outer_size(outer);
        me.set_inner_size(inner);
        me
    }

    /// Gets the widget's outer bounds offset inside the parent widget.
    pub fn outer_offset(&self) -> PxVector {
        self.0.outer_offset.get()
    }

    pub(crate) fn measure_outer_size(&self) -> PxSize {
        self.0.measure_outer_size.get()
    }

    /// Gets the widget's outer bounds size.
    pub fn outer_size(&self) -> PxSize {
        self.0.outer_size.get()
    }

    /// Gets the widget's inner bounds offset inside the outer bounds.
    ///
    /// If [`inner_offset_baseline`] is `true` the [`baseline`] is added from this value.
    ///
    /// [`inner_offset_baseline`]: Self::baseline
    /// [`baseline`]: Self::baseline
    pub fn inner_offset(&self) -> PxVector {
        let mut r = self.0.inner_offset.get();
        if self.inner_offset_baseline() {
            r.y += self.baseline();
        }
        r
    }

    /// If the [`baseline`] is added from the [`inner_offset`].
    ///
    /// [`baseline`]: Self::baseline
    /// [`inner_offset`]: Self::inner_offset
    pub fn inner_offset_baseline(&self) -> bool {
        self.0.inner_offset_baseline.get()
    }

    /// Gets the widget's child offset inside the inner bounds.
    ///
    /// If the widget's child is another widget this is zero and the offset is added to that child's outer offset instead.
    pub fn child_offset(&self) -> PxVector {
        self.0.child_offset.get()
    }

    /// Gets the widget's inner bounds size.
    pub fn inner_size(&self) -> PxSize {
        self.0.inner_size.get()
    }

    /// The baseline offset up from the inner bounds bottom line.
    ///
    /// Note that if [`inner_offset_baseline`] is `true` the [`inner_offset`] is already added by the baseline.
    ///
    /// [`inner_offset_baseline`]: Self::inner_offset_baseline
    /// [`inner_offset`]: Self::inner_offset
    pub fn baseline(&self) -> Px {
        self.0.baseline.get()
    }

    /// Gets the global transform of the widget's outer bounds during the last render or render update.
    pub fn outer_transform(&self) -> RenderTransform {
        self.0.outer_transform.get()
    }

    /// Gets the global transform of the widget's inner bounds during the last render or render update.
    pub fn inner_transform(&self) -> RenderTransform {
        self.0.inner_transform.get()
    }

    /// Get if the widget or descendant widgets rendered in the latest window frame.
    pub fn rendered(&self) -> bool {
        self.0.rendered.get()
    }

    /// Set if the widget or child widgets rendered.
    pub(super) fn set_rendered(&self, rendered: bool) {
        self.0.rendered.set(rendered);
    }

    pub(super) fn set_outer_transform(&self, transform: RenderTransform) {
        let bounds = transform
            .outer_transformed_px(PxRect::from_size(self.outer_size()))
            .unwrap_or_default();

        self.0.outer_bounds.set(bounds);
        self.0.outer_transform.set(transform);
    }

    pub(super) fn set_inner_transform(&self, transform: RenderTransform) {
        let bounds = transform
            .outer_transformed_px(PxRect::from_size(self.inner_size()))
            .unwrap_or_default();

        self.0.inner_bounds.set(bounds);
        self.0.inner_transform.set(transform);
    }

    /// Outer bounding box, updated after every render.
    pub fn outer_bounds(&self) -> PxRect {
        self.0.outer_bounds.get()
    }

    /// Calculate the bounding box that envelops the actual size and position of the inner bounds last rendered.
    pub fn inner_bounds(&self) -> PxRect {
        self.0.inner_bounds.get()
    }

    /// Last layout pass that updated the offsets or any of the descendant offsets.
    ///
    /// The version is different every time any of the offsets on the widget or descendants changes after a layout update.
    /// Widget implementers can use this version when optimizing `render` and `render_update`, the [`implicit_base::nodes::widget`]
    /// widget does this.
    ///
    /// [`implicit_base::nodes::widget`]: crate::widget_base::implicit_base::nodes::widget
    pub fn offsets_pass(&self) -> LayoutPassId {
        if self.0.childs_changed.get() {
            self.0.working_pass.get()
        } else {
            self.0.offsets_pass.get()
        }
    }

    /// Snapshot of the [`LayoutMetrics`] on the last layout.
    ///
    /// The [`metrics_used`] value indicates what fields where actually used in the last layout.
    ///
    /// Is `None` if the widget is collapsed.
    ///
    /// [`LayoutMetrics`]: crate::context::LayoutMetrics
    /// [`metrics_used`]: Self::metrics_used
    pub fn metrics(&self) -> Option<LayoutMetricsSnapshot> {
        self.0.metrics.get()
    }

    /// All [`metrics`] fields used by the widget or descendants on the last layout.
    ///
    /// [`metrics`]: Self::metrics
    pub fn metrics_used(&self) -> LayoutMask {
        self.0.metrics_used.get()
    }

    pub(crate) fn measure_metrics(&self) -> Option<LayoutMetricsSnapshot> {
        self.0.measure_metrics.get()
    }
    pub(crate) fn measure_metrics_used(&self) -> LayoutMask {
        self.0.measure_metrics_used.get()
    }

    fn begin_pass(&self, pass: LayoutPassId) {
        // Record current state as previous state on the first call of the `pass`, see `Self::end_pass`.

        if self.0.working_pass.get() != pass {
            self.0.working_pass.set(pass);
            self.0.childs_changed.set(false);

            self.0.prev_outer_offset.set(self.0.outer_offset.get());
            self.0.prev_inner_offset.set(self.0.inner_offset.get());
            self.0.prev_child_offset.set(self.0.child_offset.get());
            self.0.prev_offsets_pass.set(self.0.offsets_pass.get());
        }
    }

    fn end_pass(&self) -> i32 {
        // Check for changes against the previously recorded values, returns an offset to add to the parent's
        // changed child counter.
        //
        // How this works:
        //
        // Begin/end pass can be called multiple times in a "true" layout pass, due to intrinsic second passes or the
        // usage of `with_outer`, so an end pass can detect an intermediary value change, and return +1 to add to the parent,
        // then on the *intrinsic pass*, it detects that actually there was no change, and return -1 to fix the parent count.

        // if actually changed from previous global pass
        let changed = self.0.prev_outer_offset.get() != self.0.outer_offset.get()
            || self.0.prev_inner_offset.get() != self.0.inner_offset.get()
            || self.0.prev_child_offset.get() != self.0.child_offset.get();

        // if already processed one end_pass request and returned +1
        let believed_changed = self.0.offsets_pass.get() == self.0.working_pass.get();

        if changed {
            if believed_changed {
                0 // already updated, no need to add to the parent counter.
            } else {
                //
                self.0.offsets_pass.set(self.0.working_pass.get());
                1
            }
        } else if believed_changed {
            self.0.offsets_pass.set(self.0.prev_offsets_pass.get());
            -1 // second intrinsic pass returned value to previous, need to remove one from the parent counter.
        } else {
            0 // did not update the parent incorrectly.
        }
    }

    fn set_changed_child(&self) {
        self.0.childs_changed.set(true);
    }

    fn set_outer_offset(&self, offset: PxVector) {
        self.0.outer_offset.set(offset);
    }

    fn set_outer_size(&self, size: PxSize) {
        self.0.outer_size.set(size);
    }

    pub(crate) fn set_measure_outer_size(&self, size: PxSize) {
        self.0.measure_outer_size.set(size);
    }

    fn set_inner_offset(&self, offset: PxVector) {
        self.0.inner_offset.set(offset);
    }

    fn set_child_offset(&self, offset: PxVector) {
        self.0.child_offset.set(offset);
    }

    fn set_inner_size(&self, size: PxSize) {
        self.0.inner_size.set(size);
    }

    fn set_baseline(&self, baseline: Px) {
        self.0.baseline.set(baseline);
    }

    fn set_inner_offset_baseline(&self, enabled: bool) {
        self.0.inner_offset_baseline.set(enabled);
    }

    fn set_metrics(&self, metrics: Option<LayoutMetricsSnapshot>, used: LayoutMask) {
        self.0.metrics.set(metrics);
        self.0.metrics_used.set(used);
    }

    pub(crate) fn set_measure_metrics(&self, metrics: Option<LayoutMetricsSnapshot>, used: LayoutMask) {
        self.0.measure_metrics.set(metrics);
        self.0.measure_metrics_used.set(used);
    }
}

#[derive(Default, Debug)]
struct WidgetBorderData {
    offsets: Cell<PxSideOffsets>,
    corner_radius: Cell<PxCornerRadius>,
}

/// Shared reference to the combined *border* and corner radius of a [`WidgetInfo`].
#[derive(Default, Clone, Debug)]
pub struct WidgetBorderInfo(Rc<WidgetBorderData>);
impl WidgetBorderInfo {
    /// New default.
    pub fn new() -> Self {
        Self::default()
    }

    /// Constructor for tests.
    #[cfg(test)]
    #[cfg_attr(doc_nightly, doc(cfg(test)))]
    pub fn new_test(offsets: PxSideOffsets, corner_radius: PxCornerRadius) -> Self {
        let r = Self::default();
        r.set_offsets(offsets);
        r.set_corner_radius(corner_radius);
        r
    }

    /// Sum of the widths of all borders set on the widget.
    pub fn offsets(&self) -> PxSideOffsets {
        self.0.offsets.get()
    }

    /// Corner radius set on the widget, this is the *outer* curve of border corners.
    pub fn corner_radius(&self) -> PxCornerRadius {
        self.0.corner_radius.get()
    }

    /// Computes the [`corner_radius`] deflated by [`offsets`], this is the *inner* curve of border corners.
    ///
    /// [`corner_radius`]: Self::corner_radius
    /// [`offsets`]: Self::offsets
    pub fn inner_corner_radius(&self) -> PxCornerRadius {
        self.corner_radius().deflate(self.offsets())
    }

    /// Compute the inner offset plus [`offsets`] left, top.
    ///
    /// [`offsets`]: Self::offsets
    pub fn inner_offset(&self, bounds: &WidgetBoundsInfo) -> PxVector {
        let o = self.offsets();
        let o = PxVector::new(o.left, o.top);
        bounds.inner_offset() + o
    }

    /// Compute the inner size offset by [`offsets`].
    ///
    /// [`offsets`]: Self::offsets
    pub fn inner_size(&self, bounds: &WidgetBoundsInfo) -> PxSize {
        let o = self.offsets();
        bounds.inner_size() - PxSize::new(o.horizontal(), o.vertical())
    }

    /// Compute the inner transform offset by the [`offsets`].
    ///
    /// [`offsets`]: Self::offsets
    pub fn inner_transform(&self, bounds: &WidgetBoundsInfo) -> RenderTransform {
        let o = self.offsets();
        let o = PxVector::new(o.left, o.top);
        bounds.inner_transform().pre_translate_px(o)
    }

    pub(super) fn set_offsets(&self, widths: PxSideOffsets) {
        self.0.offsets.set(widths);
    }

    pub(super) fn set_corner_radius(&self, radius: PxCornerRadius) {
        self.0.corner_radius.set(radius)
    }
}

#[derive(Clone)]
struct WidgetInfoData {
    widget_id: WidgetId,
    bounds_info: WidgetBoundsInfo,
    border_info: WidgetBorderInfo,
    meta: Rc<OwnedStateMap>,
    interactivity_filters: InteractivityFilters,
    interactivity_cache: Cell<Option<Interactivity>>,
    local_interactivity: Cell<Interactivity>,
}
impl fmt::Debug for WidgetInfoData {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.debug_struct("WidgetInfoData")
            .field("widget_id", &self.widget_id)
            .finish_non_exhaustive()
    }
}

/// Reference to a widget info in a [`WidgetInfoTree`].
#[derive(Clone, Copy)]
pub struct WidgetInfo<'a> {
    tree: &'a WidgetInfoTree,
    node_id: ego_tree::NodeId,
}
impl<'a> PartialEq for WidgetInfo<'a> {
    fn eq(&self, other: &Self) -> bool {
        self.node_id == other.node_id
    }
}
impl<'a> Eq for WidgetInfo<'a> {}
impl<'a> std::hash::Hash for WidgetInfo<'a> {
    fn hash<H: std::hash::Hasher>(&self, state: &mut H) {
        std::hash::Hash::hash(&self.node_id, state)
    }
}
impl<'a> std::fmt::Debug for WidgetInfo<'a> {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("WidgetInfo")
            .field("[path]", &self.path().to_string())
            .field("[meta]", self.meta())
            .finish_non_exhaustive()
    }
}

impl<'a> WidgetInfo<'a> {
    fn new(tree: &'a WidgetInfoTree, node_id: ego_tree::NodeId) -> Self {
        Self { tree, node_id }
    }

    fn node(&self) -> ego_tree::NodeRef<'a, WidgetInfoData> {
        unsafe { self.tree.0.tree.get_unchecked(self.node_id) }
    }

    fn info(&self) -> &'a WidgetInfoData {
        self.node().value()
    }

    /// Widget id.
    pub fn widget_id(self) -> WidgetId {
        self.info().widget_id
    }

    /// Full path to this widget.
    pub fn path(self) -> WidgetPath {
        let mut path: Vec<_> = self.ancestors().map(|a| a.widget_id()).collect();
        path.reverse();
        path.push(self.widget_id());

        WidgetPath::new_internal(self.tree.0.window_id, path.into(), self.tree.0.id, self.node_id)
    }

    /// Full path to this widget with [`interactivity`] values.
    ///
    /// [`interactivity`]: Self::interactivity
    pub fn interaction_path(self) -> InteractionPath {
        let mut path = vec![];

        let mut blocked = None;
        let mut disabled = None;

        for w in self.self_and_ancestors() {
            let intera = w.interactivity();
            if intera.contains(Interactivity::BLOCKED) {
                blocked = Some(path.len());
            }
            if intera.contains(Interactivity::DISABLED) {
                disabled = Some(path.len());
            }

            path.push(w.widget_id());
        }
        path.reverse();

        let len = path.len();

        let path = WidgetPath::new_internal(self.tree.0.window_id, path.into(), self.tree.0.id, self.node_id);
        InteractionPath::new_internal(
            path,
            blocked.map(|i| len - i - 1).unwrap_or(len),
            disabled.map(|i| len - i - 1).unwrap_or(len),
        )
    }

    /// Gets the [`path`] if it is different from `old_path`.
    ///
    /// Only allocates a new path if needed.
    ///
    /// # Panics
    ///
    /// If `old_path` does not point to the same widget id as `self`.
    ///
    /// [`path`]: Self::path
    pub fn new_path(self, old_path: &WidgetPath) -> Option<WidgetPath> {
        assert_eq!(old_path.widget_id(), self.widget_id());
        if self
            .ancestors()
            .zip(old_path.ancestors().iter().rev())
            .any(|(ancestor, id)| ancestor.widget_id() != *id)
        {
            Some(self.path())
        } else {
            None
        }
    }

    /// Gets the [`interaction_path`] if it is different from `old_path`.
    ///
    /// Only allocates a new path if needed.
    ///
    /// Panics
    ///
    /// If `old_path` does not point to the same widget id as `self`.
    ///
    /// [`interaction_path`]: Self::interaction_path
    pub fn new_interaction_path(self, old_path: &InteractionPath) -> Option<InteractionPath> {
        assert_eq!(old_path.widget_id(), self.widget_id());

        if self.interactivity() != old_path.interactivity()
            || self
                .ancestors()
                .zip(old_path.zip())
                .any(|(anc, (id, int))| anc.widget_id() != id || anc.interactivity() != int)
        {
            Some(self.interaction_path())
        } else {
            None
        }
    }

    /// Returns `true` if the widget or the widget's descendants rendered in the last frame.
    ///
    /// This value is updated every [`render`] without causing a tree rebuild.
    ///
    /// [`render`]: crate::UiNode::render
    pub fn rendered(self) -> bool {
        self.info().bounds_info.rendered()
    }

    /// Compute the visibility of the widget or the widget's descendants.
    ///
    /// If is [`rendered`] is [`Visible`], if not and the [`bounds_info`] outer size is zero then is [`Collapsed`] else
    /// is [`Hidden`].
    ///
    /// [`rendered`]: Self::rendered
    /// [`Visible`]: Visibility::Visible
    /// [`bounds_info`]: Self::bounds_info
    /// [`Collapsed`]: Visibility::Collapsed
    /// [`Hidden`]: Visibility::Hidden
    pub fn visibility(self) -> Visibility {
        if self.rendered() {
            Visibility::Visible
        } else if self.info().bounds_info.outer_size() == PxSize::zero() {
            Visibility::Collapsed
        } else {
            Visibility::Hidden
        }
    }

    /// Get or compute the interactivity of the widget.
    ///
    /// The interactivity of a widget is the combined result of all interactivity filters applied to it and its ancestors.
    /// If a parent is blocked this is blocked, same for disabled.
    pub fn interactivity(self) -> Interactivity {
        if let Some(cache) = self.info().interactivity_cache.get() {
            cache
        } else {
            let mut interactivity = self.info().local_interactivity.get();

            if interactivity != Interactivity::BLOCKED_DISABLED {
                interactivity |= self.parent().map(|n| n.interactivity()).unwrap_or(Interactivity::ENABLED);
                if interactivity != Interactivity::BLOCKED_DISABLED {
                    for filter in &self.tree.0.interactivity_filters {
                        interactivity |= filter(&InteractivityFilterArgs { info: self });
                        if interactivity == Interactivity::BLOCKED_DISABLED {
                            break;
                        }
                    }
                }
            }

            self.info().interactivity_cache.set(Some(interactivity));
            interactivity
        }
    }

    /// All the transforms introduced by this widget, starting from the outer info.
    ///
    /// This information is up-to-date, it is updated every layout and render without causing a tree rebuild.
    pub fn bounds_info(self) -> WidgetBoundsInfo {
        self.info().bounds_info.clone()
    }

    /// Clone a reference to the widget border and corner radius information.
    ///
    /// This information is up-to-date, it is updated every layout without causing a tree rebuild.
    pub fn border_info(self) -> WidgetBorderInfo {
        self.info().border_info.clone()
    }

    /// Size of the widget outer area, not transformed.
    ///
    /// Returns an up-to-date size, the size is updated every layout without causing a tree rebuild.
    pub fn outer_size(self) -> PxSize {
        self.info().bounds_info.outer_size()
    }

    /// Size of the widget inner area, not transformed.
    ///
    /// Returns an up-to-date size, the size is updated every layout without causing a tree rebuild.
    pub fn inner_size(self) -> PxSize {
        self.info().bounds_info.inner_size()
    }

    /// Size of the widget child area, not transformed.
    ///
    /// Returns an up-to-date size, the size is updated every layout without causing a tree rebuild.
    pub fn inner_border_size(self) -> PxSize {
        let info = self.info();
        info.border_info.inner_size(&info.bounds_info)
    }

    /// Gets the baseline offset up from the inner bounds bottom line.
    pub fn baseline(self) -> Px {
        self.info().bounds_info.baseline()
    }

    /// Widget outer transform in window space.
    ///
    /// Returns an up-to-date transform, the transform is updated every render or render update without causing a tree rebuild.
    pub fn outer_transform(self) -> RenderTransform {
        self.info().bounds_info.outer_transform()
    }

    /// Widget inner transform in the window space.
    ///
    /// Returns an up-to-date transform, the transform is updated every render or render update without causing a tree rebuild.
    pub fn inner_transform(self) -> RenderTransform {
        self.info().bounds_info.inner_transform()
    }

    /// Widget outer rectangle in the window space.
    ///
    /// Returns an up-to-date rect, the bounds are updated every render or render update without causing a tree rebuild.
    pub fn outer_bounds(self) -> PxRect {
        let info = self.info();
        info.bounds_info.outer_bounds()
    }

    /// Widget inner rectangle in the window space.
    ///
    /// Returns an up-to-date rect, the bounds are updated every render or render update without causing a tree rebuild.
    pub fn inner_bounds(self) -> PxRect {
        let info = self.info();
        info.bounds_info.inner_bounds()
    }

    /// Widget inner bounds center in the window space.
    pub fn center(self) -> PxPoint {
        self.inner_bounds().center()
    }

    /// Metadata associated with the widget during render.
    pub fn meta(self) -> &'a StateMap {
        &self.info().meta.0
    }

    /// Reference the [`WidgetInfoTree`] that owns `self`.
    pub fn tree(self) -> &'a WidgetInfoTree {
        self.tree
    }

    /// Reference to the root widget.
    pub fn root(self) -> Self {
        self.ancestors().last().unwrap_or(self)
    }

    /// Reference to the widget that contains this widget.
    ///
    /// Is `None` only for [`root`](WidgetInfoTree::root).
    pub fn parent(self) -> Option<Self> {
        self.node().parent().map(move |n| WidgetInfo::new(self.tree, n.id()))
    }

    /// Reference to the previous widget within the same parent.
    pub fn prev_sibling(self) -> Option<Self> {
        self.node().prev_sibling().map(move |n| WidgetInfo::new(self.tree, n.id()))
    }

    /// Reference to the next widget within the same parent.
    pub fn next_sibling(self) -> Option<Self> {
        self.node().next_sibling().map(move |n| WidgetInfo::new(self.tree, n.id()))
    }

    /// Reference to the first widget within this widget.
    pub fn first_child(self) -> Option<Self> {
        self.node().first_child().map(move |n| WidgetInfo::new(self.tree, n.id()))
    }

    /// Reference to the last widget within this widget.
    pub fn last_child(self) -> Option<Self> {
        self.node().last_child().map(move |n| WidgetInfo::new(self.tree, n.id()))
    }

    /// If the parent widget has multiple children.
    pub fn has_siblings(self) -> bool {
        self.node().has_siblings()
    }

    /// If the widget has at least one child.
    pub fn has_children(self) -> bool {
        self.node().has_children()
    }

    /// All parent children except this widget.
    pub fn siblings(self) -> impl Iterator<Item = WidgetInfo<'a>> {
        self.prev_siblings().chain(self.next_siblings())
    }

    /// Iterator over the widgets directly contained by this widget.
    pub fn children(self) -> impl DoubleEndedIterator<Item = WidgetInfo<'a>> {
        self.node().children().map(move |n| WidgetInfo::new(self.tree, n.id()))
    }

    /// Iterator over all widgets contained by this widget.
    pub fn descendants(self) -> iter::Descendants<'a> {
        let mut d = self.self_and_descendants();
        d.next();
        d.next_back();
        d
    }

    /// Iterator over the widget and all widgets contained by it.
    pub fn self_and_descendants(self) -> iter::Descendants<'a> {
        iter::Descendants::new(self.tree, self.node())
    }

    /// Iterator over parent -> grandparent -> .. -> root.
    pub fn ancestors(self) -> impl Iterator<Item = WidgetInfo<'a>> {
        self.node().ancestors().map(move |n| WidgetInfo::new(self.tree, n.id()))
    }

    /// Iterator over self -> parent -> grandparent -> .. -> root.
    pub fn self_and_ancestors(self) -> impl Iterator<Item = WidgetInfo<'a>> {
        [self].into_iter().chain(self.ancestors())
    }

    /// Iterator over all previous widgets within the same parent.
    pub fn prev_siblings(self) -> impl Iterator<Item = WidgetInfo<'a>> {
        self.node().prev_siblings().map(move |n| WidgetInfo::new(self.tree, n.id()))
    }

    /// Iterator over self and all previous widgets within the same parent.
    pub fn self_and_prev_siblings(self) -> impl Iterator<Item = WidgetInfo<'a>> {
        [self].into_iter().chain(self.prev_siblings())
    }

    /// Iterator over all next widgets within the same parent.
    pub fn next_siblings(self) -> impl Iterator<Item = WidgetInfo<'a>> {
        self.node().next_siblings().map(move |n| WidgetInfo::new(self.tree, n.id()))
    }

    /// Iterator over self and all next widgets within the same parent.
    pub fn self_and_next_siblings(self) -> impl Iterator<Item = WidgetInfo<'a>> {
        [self].into_iter().chain(self.next_siblings())
    }

    /// Iterator over all previous widgets within the same `ancestor`, including descendants of siblings.
    ///
    /// If `ancestor` is not actually an ancestor iterates to the root.
    pub fn prev_siblings_in(self, ancestor: WidgetInfo<'a>) -> iter::Descendants<'a> {
        iter::Descendants::new_in_after(self.tree, ancestor.node(), self.node(), true)
    }

    /// Iterator over self, descendants and all previous widgets within the same `ancestor`.
    ///
    /// If `ancestor` is not actually an ancestor iterates to the root.
    pub fn self_and_prev_siblings_in(self, ancestor: WidgetInfo<'a>) -> iter::Descendants<'a> {
        iter::Descendants::new_in(self.tree, ancestor.node(), self.node(), true)
    }

    /// Iterator over all next widgets within the same `ancestor`, including descendants of siblings.
    ///
    /// If `ancestor` is not actually an ancestor iterates to the root.
    pub fn next_siblings_in(self, ancestor: WidgetInfo<'a>) -> iter::Descendants<'a> {
        iter::Descendants::new_in_after(self.tree, ancestor.node(), self.node(), false)
    }

    /// Iterator over self, descendants and all next widgets within the same `ancestor`.
    ///
    /// If `ancestor` is not actually an ancestor iterates to the root.
    pub fn self_and_next_siblings_in(self, ancestor: WidgetInfo<'a>) -> iter::Descendants<'a> {
        iter::Descendants::new_in(self.tree, ancestor.node(), self.node(), false)
    }

    /// The [`center`] orientation in relation to a `origin`.
    ///
    /// Returns `None` if the `origin` is the center.
    ///
    /// [`center`]: Self::center
    pub fn orientation_from(self, origin: PxPoint) -> Option<WidgetOrientation> {
        let o = self.center();
        for &d in &[
            WidgetOrientation::Above,
            WidgetOrientation::Right,
            WidgetOrientation::Below,
            WidgetOrientation::Left,
        ] {
            if d.is(origin, o) {
                return Some(d);
            }
        }
        None
    }

    /// All the parent's children except this widget, sorted by the [`distance_key`] to this widget's center.
    ///
    /// [`distance_key`]: Self::distance_key
    pub fn closest_siblings(self) -> Vec<WidgetInfo<'a>> {
        let mut vec: Vec<_> = self.siblings().collect();
        let origin = self.center();
        vec.sort_by_key(|w| w.distance_key(origin));
        vec
    }

    /// Value that indicates the distance between this widget center and `origin`.
    pub fn distance_key(self, origin: PxPoint) -> usize {
        let o = self.center();
        let a = (o.x - origin.x).0.pow(2);
        let b = (o.y - origin.y).0.pow(2);
        (a + b) as usize
    }

    /// Count of ancestors.
    pub fn depth(self) -> usize {
        self.ancestors().count()
    }

    /// First ancestor of `self` and `other`.
    ///
    /// Returns `None` if `other` is not from the same tree.
    pub fn shared_ancestor(self, other: Self) -> Option<WidgetInfo<'a>> {
        if self.tree == other.tree {
            let a = self.path();
            let b = other.path();
            let shared = a.shared_ancestor(&b).unwrap();
            self.tree.get(&*shared)
        } else {
            None
        }
    }

    fn prefer_linear_spatial_search(self) -> bool {
        let mut count = 0;
        for _ in self.descendants() {
            count += 1;
            if count > 8 {
                return false;
            }
        }
        true
    }

    /// Visit all descendants with [`inner_bounds`] that intersect the `area`.
    ///
    /// [`inner_bounds`]: WidgetInfo::inner_bounds
    pub fn visit_intersects<B>(self, area: PxRect, mut visit: impl FnMut(WidgetInfo<'a>) -> ControlFlow<B>) -> ControlFlow<B> {
        if self.prefer_linear_spatial_search() {
            let area = area.to_box2d();
            for d in self.descendants() {
                if d.inner_bounds().to_box2d().intersects(&area) {
                    visit(d)?;
                }
            }
            return ControlFlow::Continue(());
        }

        self.tree().visit_intersects(area, |w| {
            if w.ancestors().any(|w| w == self) {
                visit(w)
            } else {
                ControlFlow::Continue(())
            }
        })
    }

    /// Visit all descendants with [`inner_bounds`] that contains the `point`.
    ///
    /// [`inner_bounds`]: WidgetInfo::inner_bounds
    pub fn visit_contains<B>(self, point: PxPoint, mut visit: impl FnMut(WidgetInfo<'a>) -> ControlFlow<B>) -> ControlFlow<B> {
        if self.prefer_linear_spatial_search() {
            for d in self.descendants() {
                if d.inner_bounds().contains(point) {
                    visit(d)?;
                }
            }
            return ControlFlow::Continue(());
        }

        self.tree().visit_contains(point, |w| {
            if w.ancestors().any(|w| w == self) {
                visit(w)
            } else {
                ControlFlow::Continue(())
            }
        })
    }

    /// Visit all descendants with [`inner_bounds`] that are fully inside the `area`.
    ///
    /// [`inner_bounds`]: WidgetInfo::inner_bounds
    pub fn visit_contained<B>(self, area: PxRect, mut visit: impl FnMut(WidgetInfo<'a>) -> ControlFlow<B>) -> ControlFlow<B> {
        if self.prefer_linear_spatial_search() {
            let area = area.to_box2d();
            for d in self.descendants() {
                if area.contains_box(&d.inner_bounds().to_box2d()) {
                    visit(d)?
                }
            }
            return ControlFlow::Continue(());
        }
        self.tree().visit_contained(area, |w| {
            if w.ancestors().any(|w| w == self) {
                visit(w)
            } else {
                ControlFlow::Continue(())
            }
        })
    }

    /// Visit all descendants with [`inner_bounds`] that fully envelops the `area`.
    ///
    /// [`inner_bounds`]: WidgetInfo::inner_bounds
    pub fn visit_contains_area<B>(self, area: PxRect, mut visit: impl FnMut(WidgetInfo<'a>) -> ControlFlow<B>) -> ControlFlow<B> {
        if self.prefer_linear_spatial_search() {
            let area = area.to_box2d();
            for d in self.descendants() {
                if d.inner_bounds().to_box2d().contains_box(&area) {
                    visit(d)?;
                }
            }
            return ControlFlow::Continue(());
        }
        self.tree().visit_contains_area(area, |w| {
            if w.ancestors().any(|w| w == self) {
                visit(w)
            } else {
                ControlFlow::Continue(())
            }
        })
    }

    /// Visit all descendants with [`center`] inside the `area`.
    ///
    /// [`center`]: WidgetInfo::center
    pub fn visit_center_contained<B>(self, area: PxRect, mut visit: impl FnMut(WidgetInfo<'a>) -> ControlFlow<B>) -> ControlFlow<B> {
        if self.prefer_linear_spatial_search() {
            let area = area.to_box2d();
            for d in self.descendants() {
                if area.contains(d.center()) {
                    visit(d)?;
                }
            }
            return ControlFlow::Continue(());
        }

        self.tree().visit_center_contained(area, |w| {
            if w.ancestors().any(|w| w == self) {
                visit(w)
            } else {
                ControlFlow::Continue(())
            }
        })
    }

    /// Visit all descendants with [`center`] in the direction defined by `orientation` from the `origin` and within the `distance`.
    ///
    /// Note that you can use [`Px::MAX`] on the distance to visit all widgets in the direction.
    ///
    /// The first parameter of `visit` is the current search quadrant, each subsequent quadrants is double in size and further away
    /// from the `origin` by the length of the previous search quadrant, this means that every time the search quadrant changes all
    /// visited widgets are further away from `origin` than previous widgets.
    ///
    /// If the widget has only a small amount of descendants a linear search is done instead, in this case the search quadrant has size zero.
    ///
    /// [`center`]: WidgetInfo::center
    pub fn visit_oriented<B>(
        self,
        origin: PxPoint,
        distance: Px,
        orientation: WidgetOrientation,
        mut visit: impl FnMut(PxRect, WidgetInfo<'a>) -> ControlFlow<B>,
    ) -> ControlFlow<B> {
        if self.prefer_linear_spatial_search() {
            let none_search_quad = PxRect::new(origin, PxSize::zero());
            for d in self.descendants() {
                if d.orientation_from(origin) == Some(orientation) {
                    visit(none_search_quad, d)?;
                }
            }
            return ControlFlow::Continue(());
        }

        self.tree().visit_oriented(origin, distance, orientation, visit)
    }

    /// First descendant found in the direction, within `distance` but at any distance, this is the fastest check for if there
    /// are any descendants in the direction.
    pub fn first_oriented(self, origin: PxPoint, distance: Px, orientation: WidgetOrientation) -> Option<WidgetInfo<'a>> {
        let mut result = None;
        self.visit_oriented(origin, distance, orientation, |_, w| {
            result = Some(w);
            ControlFlow::Break(())
        });
        result
    }

    /// Find any descendant in the direction within the `distance` that is allowed by the `filter`.
    pub fn find_oriented(
        self,
        origin: PxPoint,
        distance: Px,
        orientation: WidgetOrientation,
        mut filter: impl FnMut(WidgetInfo<'a>) -> bool,
    ) -> Option<WidgetInfo<'a>> {
        let mut result = None;
        self.visit_oriented(origin, distance, orientation, |_, w| {
            if filter(w) {
                result = Some(w);
                ControlFlow::Break(())
            } else {
                ControlFlow::Continue(())
            }
        });
        result
    }

    /// Closest descendant in the direction within the `distance`.
    pub fn closest_oriented(self, origin: PxPoint, distance: Px, orientation: WidgetOrientation) -> Option<WidgetInfo<'a>> {
        let mut closest_key = usize::MAX;
        let mut closest = None;
        let mut search_quad = PxRect::zero();

        self.visit_oriented(origin, distance, orientation, |q, w| {
            if q != search_quad {
                if search_quad.size.width == Px(0) || closest.is_none() {
                    search_quad = q;
                } else {
                    // subsequent search quads are guaranteed to only yield items further away.
                    return ControlFlow::Break(());
                }
            }

            let key = w.distance_key(origin);
            if key < closest_key {
                closest_key = key;
                closest = Some(w);
            }

            ControlFlow::<()>::Continue(())
        });

        closest
    }

    /// Find closest descendant in the direction within the `distance` that is allowed by the `filter`.
    pub fn find_closest_oriented(
        self,
        origin: PxPoint,
        distance: Px,
        orientation: WidgetOrientation,
        mut filter: impl FnMut(WidgetInfo<'a>) -> bool,
    ) -> Option<WidgetInfo<'a>> {
        let mut closest_key = usize::MAX;
        let mut closest = None;
        let mut search_quad = PxRect::zero();

        self.visit_oriented(origin, distance, orientation, |q, w| {
            if q != search_quad {
                if search_quad.size.width == Px(0) || closest.is_none() {
                    search_quad = q;
                } else {
                    // subsequent search quads are guaranteed to only yield items further away.
                    return ControlFlow::Break(());
                }
            }

            if filter(w) {
                let key = w.distance_key(origin);
                if key < closest_key {
                    closest_key = key;
                    closest = Some(w);
                }
            }

            ControlFlow::<()>::Continue(())
        });

        closest
    }
}

/// Orientation of a [`WidgetInfo`] relative to another point.
#[derive(Debug, PartialEq, Eq, Clone, Copy)]
pub enum WidgetOrientation {
    /// Widget is above the reference point.
    Above,
    /// Widget is to the right of the reference point.
    Right,
    /// Widget is below the reference point.
    Below,
    /// Widget is to the left of the reference point.
    Left,
}
impl WidgetOrientation {
    /// Check if `center` orientation from `origin` matches `self`.
    pub fn is(self, origin: PxPoint, center: PxPoint) -> bool {
        let (a, b, c, d) = match self {
            WidgetOrientation::Above => (center.y, origin.y, center.x, origin.x),
            WidgetOrientation::Right => (origin.x, center.x, center.y, origin.y),
            WidgetOrientation::Below => (origin.y, center.y, center.x, origin.x),
            WidgetOrientation::Left => (center.x, origin.x, center.y, origin.y),
        };

        let mut is_in_direction = false;

        // for 'Above' this is:
        // is above line?
        if a < b {
            // is to the right?
            if c > d {
                // is in the 45º 'frustum'
                // │?╱
                // │╱__
                is_in_direction = c <= d + (b - a);
            } else {
                //  ╲?│
                // __╲│
                is_in_direction = c >= d - (b - a);
            }
        }

        is_in_direction
    }

    /// Suggested areas for spatial visitors looking for points in the orientation from `origin`.
    ///
    /// The rectangles must be used for visited and [`is_in_direction`] called for every widget visited.
    ///
    /// [`is_in_direction`]: Self::is_in_direction
    pub fn search_bounds(self, origin: PxPoint, max_distance: Px) -> impl Iterator<Item = PxRect> {
        iter::DirectionSearchBounds::new(self, origin, max_distance)
    }
}

/// Data from a previous [`WidgetInfoBuilder`], can be reused in the next rebuild for a performance boost.
pub struct UsedWidgetInfoBuilder {
    tree_capacity: usize,
    interactivity_filters_capacity: usize,
}
impl UsedWidgetInfoBuilder {
    fn fallback() -> Self {
        UsedWidgetInfoBuilder {
            tree_capacity: 100,
            interactivity_filters_capacity: 30,
        }
    }
}

macro_rules! update_slot {
    ($(
        $(#[$meta:meta])*
        $vis:vis struct $Slot:ident -> $Mask:ident;
    )+) => {$(
        $(#[$meta])*
        ///
        /// This `struct` is a single byte that represents an index in the full bitmap.
        #[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
        $vis struct $Slot(u8);

        impl $Slot {
            /// Gets a slot.
            pub fn next() -> Self {
                thread_local! {
                    static SLOT: Cell<u8> = Cell::new(0);
                }

                let slot = SLOT.with(|s| {
                    let slot = s.get().wrapping_add(1);
                    s.set(slot);
                    slot
                });

                Self(slot)
            }

            /// Gets a mask representing just this slot.
            pub fn mask(self) -> $Mask {
                $Mask::from_slot(self)
            }
        }
    )+}
}
macro_rules! update_mask {
    ($(
        $(#[$meta:meta])*
        $vis:vis struct $Mask:ident <- $Slot:ident;
    )+) => {$(
        $(#[$meta])*
        ///
        /// This `struct` is a 256-bit bitmap of flagged slots.
        #[derive(Clone, Copy, Default, PartialEq, Eq, Hash)]
        $vis struct $Mask([u128; 2]);

        impl $Mask {
            /// Gets a mask representing just the `slot`.
            pub fn from_slot(slot: $Slot) -> Self {
                let mut r = Self::none();
                r.insert(slot);
                r
            }

            /// Returns a mask that represents no update.
            pub const fn none() -> Self {
                $Mask([0; 2])
            }

            /// Returns a mask that represents all updates.
            pub const fn all() -> Self {
                $Mask([u128::MAX; 2])
            }

            /// Returns `true` if this mask does not represent any update.
            pub fn is_none(&self) -> bool {
                self.0[0] == 0 && self.0[1] == 0
            }

            /// Flags the `slot` in this mask.
            pub fn insert(&mut self, slot: $Slot) {
                let slot = slot.0;
                if slot < 128 {
                    self.0[0] |= 1 << slot;
                } else {
                    self.0[1] |= 1 << (slot - 128);
                }
            }

            /// Returns `true` if the `slot` is set in this mask.
            pub fn contains(&self, slot: $Slot) -> bool {
                let slot = slot.0;
                if slot < 128 {
                    (self.0[0] & (1 << slot)) != 0
                } else {
                    (self.0[1] & (1 << (slot - 128))) != 0
                }
            }

            /// Flags all slots set in `other` in `self` as well.
            pub fn extend(&mut self, other: &Self) {
                self.0[0] |= other.0[0];
                self.0[1] |= other.0[1];
            }

            /// Returns `true` if any slot is set in both `self` and `other`.
            pub fn intersects(&self, other: &Self) -> bool {
                (self.0[0] & other.0[0]) != 0 || (self.0[1] & other.0[1]) != 0
            }
        }
        impl ops::BitOrAssign<Self> for $Mask {
            fn bitor_assign(&mut self, rhs: Self) {
                self.extend(&rhs)
            }
        }
        impl ops::BitOrAssign<$Slot> for $Mask {
            fn bitor_assign(&mut self, rhs: $Slot) {
                self.insert(rhs)
            }
        }
        impl ops::BitOr<Self> for $Mask {
            type Output = Self;

            fn bitor(mut self, rhs: Self) -> Self {
                self.extend(&rhs);
                self
            }
        }
        impl ops::BitOr<$Slot> for $Mask {
            type Output = Self;

            fn bitor(mut self, rhs: $Slot) -> Self {
                self.insert(rhs);
                self
            }
        }
        impl ops::BitOr<Self> for $Slot {
            type Output = $Mask;

            fn bitor(self, rhs: Self) -> $Mask {
                let mut m = self.mask();
                m.insert(rhs);
                m
            }
        }
        impl fmt::Debug for $Mask {
            fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
                use std::fmt::Write;

                let rows = [
                    self.0[0] as u64,
                    (self.0[0] >> 64) as u64,
                    self.0[1] as u64,
                    (self.0[1] >> 64) as u64
                ];

                writeln!(f, "{} {{", stringify!($Mask))?;

                let mut bmp = String::with_capacity(256 + 4);

                for row in rows {
                    write!(bmp, "    ")?;
                    for i in 0..64 {
                        let b = 1u64 << i;
                        if (b & row) == 0 {
                            write!(bmp, "░")?;
                        } else {
                            write!(bmp, "█")?;
                        }
                    }
                    writeln!(bmp)?;
                }

                write!(f, "{bmp}}}")
            }
        }

    )+}
}

update_slot! {
    /// Represents a single update source in a [`UpdateMask`].
    ///
    /// Anything that generates an [`UiNode::update`] has one of these slots reserved.
    ///
    /// [`UiNode::update`]: crate::UiNode::update
    pub struct UpdateSlot -> UpdateMask;

    /// Represents a single event in a [`EventMask`].
    ///
    /// Every event is assigned on of these slots.
    pub struct EventSlot -> EventMask;
}
update_mask! {
    /// Represents the combined update sources that affect an UI tree or widget.
    pub struct UpdateMask <- UpdateSlot;

    /// Represents the combined events that are listened by an UI tree or widget.
    pub struct EventMask <- EventSlot;
}

/// Represents all event and update subscriptions of a widget.
///
/// Properties must register their interest in events and variables here otherwise a call to [`UiNode::event`] or
/// [`UiNode::update`] can end-up skipped due to optimizations.
///
/// [`UiNode::event`]: crate::UiNode::event
/// [`UiNode::update`]: crate::UiNode::update
#[derive(Debug, Default, Clone, PartialEq, Eq, Hash)]
pub struct WidgetSubscriptions {
    event: EventMask,
    update: UpdateMask,
}
impl WidgetSubscriptions {
    /// New default, no subscriptions.
    pub fn new() -> Self {
        Self::default()
    }

    /// Register an [`Event`] or command subscription.
    ///
    /// [`Event`]: crate::event::Event
    pub fn event(&mut self, event: impl crate::event::Event) -> &mut Self {
        self.event.insert(event.slot());
        self
    }

    /// Register multiple event or command subscriptions.
    pub fn events(&mut self, mask: &EventMask) -> &mut Self {
        self.event.extend(mask);
        self
    }

    /// Register async handler waker update source.
    pub fn handler<A>(&mut self, handler: &impl WidgetHandler<A>) -> &mut Self
    where
        A: Clone + 'static,
    {
        handler.subscribe(self);
        self
    }

    /// Register a custom update source subscription.
    pub fn update(&mut self, slot: UpdateSlot) -> &mut Self {
        self.update.insert(slot);
        self
    }

    /// Register multiple update source subscriptions.
    pub fn updates(&mut self, mask: &UpdateMask) -> &mut Self {
        self.update.extend(mask);
        self
    }

    /// Register all subscriptions from `other` in `self`.
    pub fn extend(&mut self, other: &WidgetSubscriptions) -> &mut Self {
        self.events(&other.event).updates(&other.update)
    }

    /// Register a variable subscription.
    pub fn var<Vr, T>(&mut self, vars: &Vr, var: &impl Var<T>) -> &mut Self
    where
        Vr: WithVarsRead,
        T: VarValue,
    {
        self.update.extend(&var.update_mask(vars));
        self
    }

    /// Start a [`WidgetVarSubscriptions`] to register multiple variables without needing to reference the [`VarsRead`] for every variable.
    pub fn vars<'s, 'v>(&'s mut self, vars: &'v impl AsRef<VarsRead>) -> WidgetVarSubscriptions<'v, 's> {
        WidgetVarSubscriptions {
            vars: vars.as_ref(),
            subs: self,
        }
    }

    /// Returns `true` if the widget subscribes to events in the slot.
    pub fn event_contains(&self, event: &impl EventUpdateArgs) -> bool {
        self.event.contains(event.slot())
    }

    /// Returns `true` if the widget is interested in variables or other update sources that are flagged in `updates`.
    pub fn update_intersects(&self, updates: &Updates) -> bool {
        self.update.intersects(updates.current())
    }

    /// Returns the current set event subscriptions.
    pub fn event_mask(&self) -> EventMask {
        self.event
    }

    /// Returns the current set update subscriptions.
    pub fn update_mask(&self) -> UpdateMask {
        self.update
    }

    /// Returns if both event and update subscriptions are none.
    pub fn is_none(&self) -> bool {
        self.event.is_none() && self.update.is_none()
    }
}
impl ops::BitOr for WidgetSubscriptions {
    type Output = Self;

    fn bitor(mut self, rhs: Self) -> Self::Output {
        self |= rhs;
        self
    }
}
impl ops::BitOrAssign for WidgetSubscriptions {
    fn bitor_assign(&mut self, rhs: Self) {
        self.event |= rhs.event;
        self.update |= rhs.update;
    }
}

/// Helper for registering multiple [`WidgetSubscriptions::var`] without needing to reference the [`VarsRead`] instance for every variable.
pub struct WidgetVarSubscriptions<'v, 's> {
    vars: &'v VarsRead,
    /// The main [`WidgetSubscriptions`].
    pub subs: &'s mut WidgetSubscriptions,
}
impl<'v, 's> WidgetVarSubscriptions<'v, 's> {
    /// Register a variable subscriptions.
    pub fn var<T: VarValue>(self, var: &impl Var<T>) -> Self {
        Self {
            subs: self.subs.var(self.vars, var),
            vars: self.vars,
        }
    }
}

/// Argument for a interactivity filter function.
///
/// See [WidgetInfoBuilder::push_interactivity_filter].
#[derive(Debug)]
pub struct InteractivityFilterArgs<'a> {
    /// Widget being filtered.
    pub info: WidgetInfo<'a>,
}
impl<'a> InteractivityFilterArgs<'a> {
    /// New from `info`.
    pub fn new(info: WidgetInfo<'a>) -> Self {
        Self { info }
    }
}

type InteractivityFilters = Vec<Rc<dyn Fn(&InteractivityFilterArgs) -> Interactivity>>;

bitflags! {
    /// Represents the level of interaction allowed for a widget.
    pub struct Interactivity: u8 {
        /// Normal interactions allowed.
        ///
        /// This is the default value.
        const ENABLED = 0b00;

        /// Only "disabled" interactions allowed and disabled visuals.
        ///
        /// An example of disabled interaction is a tooltip that explains why a disabled button cannot be clicked.
        const DISABLED = 0b01;

        /// No interaction allowed, the widget must behave like a background visual.
        ///
        /// Note that widgets with blocked interaction are still hit-testable, so they can still be "clicked"
        /// as a visual part of an interactive parent widget.
        const BLOCKED = 0b10;

        /// `BLOCKED` with `DISABLED` visuals.
        const BLOCKED_DISABLED = Self::DISABLED.bits | Self::BLOCKED.bits;
    }
}
impl Interactivity {
    /// Normal interactions allowed.
    pub fn is_enabled(self) -> bool {
        self == Self::ENABLED
    }

    /// Enabled visuals, may still be blocked.
    pub fn is_visually_enabled(self) -> bool {
        !self.contains(Self::DISABLED)
    }

    /// Only "disabled" interactions allowed and disabled visuals.
    pub fn is_disabled(self) -> bool {
        self == Self::DISABLED
    }

    /// Disabled visuals, maybe also blocked.
    pub fn is_visually_disabled(self) -> bool {
        self.contains(Self::DISABLED)
    }

    /// No interaction allowed, may still be visually enabled.
    pub fn is_blocked(self) -> bool {
        self.contains(Self::BLOCKED)
    }
}
impl Default for Interactivity {
    /// `ENABLED`.
    fn default() -> Self {
        Interactivity::ENABLED
    }
}
impl_from_and_into_var! {
    /// * `true` -> `ENABLED`
    /// * `false` -> `DISABLED`
    fn from(enabled: bool) -> Interactivity {
        if enabled {
            Interactivity::ENABLED
        } else {
            Interactivity::DISABLED
        }
    }
}

/// Widget visibility.
///
/// The visibility status of a widget is computed from its outer-bounds in the last layout and if it rendered anything,
/// the visibility of a parent widget affects all descendant widgets, you can inspect the visibility using the
/// [`WidgetInfo::visibility`] method.
///
/// You can use  the [`visibility`] property to explicitly set the visibility of a widget, this property causes the widget to
/// layout and render according to specified visibility.
///
/// [`WidgetInfo::visibility`]: crate::widget_info::WidgetInfo::visibility
/// [`visibility`]: fn@crate::widget_base::visibility
#[derive(Copy, Clone, Eq, PartialEq)]
pub enum Visibility {
    /// The widget is visible, this is default.
    Visible,
    /// The widget is not visible, but still affects layout.
    ///
    /// Hidden widgets measure and reserve space in their parent but are not rendered.
    Hidden,
    /// The widget is not visible and does not affect layout.
    ///
    /// Collapsed widgets always measure to zero and are not rendered.
    Collapsed,
}
impl fmt::Debug for Visibility {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        if f.alternate() {
            write!(f, "Visibility::")?;
        }
        match self {
            Visibility::Visible => write!(f, "Visible"),
            Visibility::Hidden => write!(f, "Hidden"),
            Visibility::Collapsed => write!(f, "Collapsed"),
        }
    }
}
impl Default for Visibility {
    /// [` Visibility::Visible`]
    fn default() -> Self {
        Visibility::Visible
    }
}
impl ops::BitOr for Visibility {
    type Output = Self;

    /// `Collapsed` | `Hidden` | `Visible` short circuit from left to right.
    fn bitor(self, rhs: Self) -> Self::Output {
        use Visibility::*;
        match (self, rhs) {
            (Collapsed, _) | (_, Collapsed) => Collapsed,
            (Hidden, _) | (_, Hidden) => Hidden,
            _ => Visible,
        }
    }
}
impl ops::BitOrAssign for Visibility {
    fn bitor_assign(&mut self, rhs: Self) {
        *self = *self | rhs;
    }
}
impl_from_and_into_var! {
    /// * `true` -> `Visible`
    /// * `false` -> `Collapsed`
    fn from(visible: bool) -> Visibility {
        if visible { Visibility::Visible } else { Visibility::Collapsed }
    }
}
