### Machine translated by `cargo zng l10n`, 1efe39e07e78c5ca09a02e98644ae77adf5b9afad87a6f8b13dcc8790acc63db

### Auto generated by `cargo zng l10n`

COPY_CMD =
    .info = Nukopijuoti pasirinkimą į iškarpinę
    .name = Kopijuoti

CUT_CMD =
    .info = Iškirpti pasirinkimą ir įdėti jį į iškarpinę
    .name = Iškirpti

PASTE_CMD =
    .info = Įterpti turinį iš iškarpinės
    .name = Įklijuoti