### Machine translated by `cargo zng l10n`, ab0682936292139ef046e822c139586a33986c3522951ecb20715ef0c900db4b

### Auto generated by `cargo zng l10n`

FOCUS_ALT_CMD =
    .info = Fokusera alternativt omfång
    .name = Fokusera alternativt

FOCUS_DOWN_CMD =
    .info = Fokusera närmaste fokuserbara nedåt
    .name = Fokusera nedåt

FOCUS_ENTER_CMD =
    .info = Fokusera underliggande fokuserbart element
    .name = Fokusera gå in

FOCUS_EXIT_CMD =
    .info = Fokusera överliggande fokuserbart element, eller återgå
    .name = Fokusera gå ut

FOCUS_LEFT_CMD =
    .info = Fokusera närmaste fokuserbara åt vänster
    .name = Fokusera vänster

FOCUS_NEXT_CMD =
    .info = Fokusera nästa fokuserbara element
    .name = Fokusera nästa

FOCUS_PREV_CMD =
    .info = Fokusera föregående fokuserbara element
    .name = Fokusera föregående

FOCUS_RIGHT_CMD =
    .info = Fokusera närmaste fokuserbara åt höger
    .name = Fokusera höger

FOCUS_UP_CMD =
    .info = Fokusera närmaste fokuserbara uppåt
    .name = Fokusera uppåt