### Machine translated by `cargo zng l10n`, ca15a8ce25cc0c158873c10a67ae3b8a2387847209565e6c26c99f1cba2d77eb

### Auto generated by `cargo zng l10n`

accept =
    .false = لا أوافق على الاتفاقية
    .true = أوافق على الاتفاقية

info =
    .install = يرجى مراجعة شروط الترخيص قبل تثبيت {$app}
    .update = يرجى مراجعة شروط الترخيص قبل تحديث {$app}

message = يجب عليك الموافقة على شروط هذه الاتفاقية قبل المتابعة.
    .requires_scroll = يجب عليك قراءة والموافقة على شروط هذه الاتفاقية قبل المتابعة.

title = اتفاقية الترخيص