### Machine translated by `cargo zng l10n`, 94527aed8f60480f65e908ce1bb46627d277ef4ebd081f0dc4bb2eb5cfcfaf82

### Auto generated by `cargo zng l10n`

action-run =
    .info = {$app} uygulamasını çalıştır

message =
    .install = Sihirbaz, {$app} {$version} sürümünü bilgisayarınıza yükledi.
    .uninstall = Sihirbaz, {$app} {$version} sürümünü bilgisayarınızdan kaldırdı.
    .update = Sihirbaz, {$app} uygulamasını bilgisayarınızda {$current_version} sürümünden {$new_version} sürümüne güncelledi.

title =
    .install = {$app} Yüklendi
    .repair = {$app} Onarıldı
    .uninstall = {$app} Kaldırıldı
    .update = {$app} Güncellendi