### Machine translated by `cargo zng l10n`, ca15a8ce25cc0c158873c10a67ae3b8a2387847209565e6c26c99f1cba2d77eb

### Auto generated by `cargo zng l10n`

accept =
    .false = Nesouhlasím s dohodou
    .true = Souhlasím s dohodou

info =
    .install = Před instalací {$app} si prosím přečtěte licenční podmínky
    .update = Před aktualizací {$app} si prosím přečtěte licenční podmínky

message = Před pokračováním musíte souhlasit s podmínkami této dohody.
    .requires_scroll = Před pokračováním musíte přečíst a odsouhlasit podmínky této dohody.

title = Licenční dohoda