### Machine translated by `cargo zng l10n`, be135842e65abb43f38e8f66e75bcc43fb249683b92f3d12466fbb444de99621

### Auto generated by `cargo zng l10n`

info =
    .clean = Operace selhala, všechny změny byly zrušeny.
    .corrupted = Operace selhala, instalace je poškozená.

message =
    .install-clean = Instalace selhala, {$app} nebyla nainstalována.
    .install-corrupted = Instalace selhala, {$app} byla nainstalována pouze částečně.
    .repair-clean = Oprava selhala, instalace {$app} nebyla opravena.
    .repair-corrupted = Oprava selhala, {$app} byla opravena pouze částečně.
    .uninstall-clean = Odinstalace selhala, {$app} zůstává nainstalován.
    .uninstall-corrupted = Odinstalace selhala, {$app} byla odinstalována pouze částečně.
    .update-clean = Aktualizace selhala, {$app} nebyla aktualizována. Aktuální nainstalovaná verze {$current_version} zůstává a stále může být použita.
    .update-corrupted = Aktualizace selhala, {$app} byla aktualizována pouze částečně.

title =
    .install = Instalace selhala
    .repair = Oprava selhala
    .uninstall = Odinstalace selhala
    .update = Aktualizace selhala