### Machine translated by `cargo zng l10n`, be135842e65abb43f38e8f66e75bcc43fb249683b92f3d12466fbb444de99621

### Auto generated by `cargo zng l10n`

info =
    .clean = Operace selhala, všechny změny byly vráceny zpět.
    .corrupted = Operace selhala, instalace je poškozená.

message =
    .install-clean = Operace instalace selhala, aplikace {$app} nebyla nainstalována.
    .install-corrupted = Operace instalace selhala, aplikace {$app} byla nainstalována pouze částečně.
    .repair-clean = Operace opravy selhala, instalace {$app} nebyla opravena.
    .repair-corrupted = Operace opravy selhala, instalace {$app} byla opravena pouze částečně.
    .uninstall-clean = Operace odinstalace selhala, aplikace {$app} zůstala nainstalovaná.
    .uninstall-corrupted = Operace odinstalace selhala, aplikace {$app} byla odinstalována pouze částečně.
    .update-clean = Operace aktualizace selhala, aplikace {$app} nebyla aktualizována. Aktuálně nainstalovaná verze {$current_version} zůstává a lze ji nadále používat.
    .update-corrupted = Operace aktualizace selhala, aplikace {$app} byla aktualizována pouze částečně.

title =
    .install = Instalace selhala
    .repair = Oprava selhala
    .uninstall = Odinstalace selhala
    .update = Aktualizace selhala