### Machine translated by `cargo zng l10n`, 2abd48f76a022e01c465074590f32305b520f65b9a52b2a63373e4df86ad2381

### Auto generated by `cargo zng l10n`

action-run =
    .info = Spustit {$app}

message =
    .install = Průvodce nainstaloval {$app} {$version} do vašeho počítače.
    .repair = Průvodce opravil instalaci {$app} {$version} ve vašem počítači.
    .uninstall = Průvodce odinstaloval {$app} {$version} z vašeho počítače.
    .update = Průvodce aktualizoval {$app} z verze {$current_version} na {$new_version} ve vašem počítači.

title =
    .install = {$app} nainstalován
    .repair = {$app} opraven
    .uninstall = {$app} odinstalován
    .update = {$app} aktualizován