### Machine translated by `cargo zng l10n`, 86bb0abb6293e164ae596c4745cba0db2da828923ef8061ed99c7bf5ccfa9ddd

### Auto generated by `cargo zng l10n`

default-info =
    .create-shortcut = Vytvořit zkratku
    .extract-files = Extrahovat soubory
    .register-uninstaller = Registrovat odinstalátor
    .remove-files = Odebrat soubory
    .remove-shortcut = Odebrat zkratku
    .unregister-uninstaller = Deregistrovat odinstalátor

info =
    .install = Prosím, počkejte, dokud se {$app} nainstaluje na vašem počítači.
    .repair = Prosím, počkejte, dokud se {$app} opraví na vašem počítači.
    .uninstall = Prosím, počkejte, dokud se {$app} odinstaluje z vašeho počítače.
    .update = Prosím, počkejte, dokud se {$app} aktualizuje na vašem počítači.

title =
    .install = Instalace
    .repair = Oprava
    .uninstall = Odinstalace
    .update = Aktualizace