### Machine translated by `cargo zng l10n`, 86bb0abb6293e164ae596c4745cba0db2da828923ef8061ed99c7bf5ccfa9ddd

### Auto generated by `cargo zng l10n`

default-info =
    .create-shortcut = 建立捷徑
    .extract-files = 解壓縮檔案
    .register-uninstaller = 註冊解除安裝程式
    .remove-files = 移除檔案
    .remove-shortcut = 移除捷徑
    .unregister-uninstaller = 取消註冊解除安裝程式

info =
    .install = 請稍候，正在您的電腦上安裝 {$app}。
    .repair = 請稍候，正在您的電腦上修復 {$app}。
    .uninstall = 請稍候，正在從您的電腦上解除安裝 {$app}。
    .update = 請稍候，正在您的電腦上更新 {$app}。

title =
    .install = 正在安裝
    .repair = 正在修復
    .uninstall = 正在解除安裝
    .update = 正在更新