### Machine translated by `cargo zng l10n`, ab0682936292139ef046e822c139586a33986c3522951ecb20715ef0c900db4b

### Auto generated by `cargo zng l10n`

FOCUS_ALT_CMD =
    .info = التركيز على نطاق بديل
    .name = تركيز بديل

FOCUS_DOWN_CMD =
    .info = التركيز على أقرب عنصر قابل للتركيز في الأسفل
    .name = تركيز للأسفل

FOCUS_ENTER_CMD =
    .info = التركيز على عنصر فرعي قابل للتركيز
    .name = تركيز للداخل

FOCUS_EXIT_CMD =
    .info = التركيز على عنصر أب قابل للتركيز، أو استعادة التركيز
    .name = تركيز للخارج

FOCUS_LEFT_CMD =
    .info = التركيز على أقرب عنصر قابل للتركيز في اليسار
    .name = تركيز لليسار

FOCUS_NEXT_CMD =
    .info = التركيز على العنصر القابل للتركيز التالي
    .name = تركيز التالي

FOCUS_PREV_CMD =
    .info = التركيز على العنصر القابل للتركيز السابق
    .name = تركيز السابق

FOCUS_RIGHT_CMD =
    .info = التركيز على أقرب عنصر قابل للتركيز في اليمين
    .name = تركيز لليمين

FOCUS_UP_CMD =
    .info = التركيز على أقرب عنصر قابل للتركيز في الأعلى
    .name = تركيز للأعلى