### Machine translated by `cargo zng l10n`, be135842e65abb43f38e8f66e75bcc43fb249683b92f3d12466fbb444de99621

### Auto generated by `cargo zng l10n`

info =
    .clean = Åtgärden misslyckades, alla ändringar har ångrats.
    .corrupted = Åtgärden misslyckades, installationen är skadad.

message =
    .install-clean = Installationsåtgärden misslyckades, {$app} installerades inte.
    .install-corrupted = Installationsåtgärden misslyckades, {$app} installerades endast delvis.
    .repair-clean = Reparationsåtgärden misslyckades, installationen av {$app} reparerades inte.
    .repair-corrupted = Reparationsåtgärden misslyckades, {$app} reparerades endast delvis.
    .uninstall-clean = Avinstallationsåtgärden misslyckades, {$app} är fortfarande installerat.
    .uninstall-corrupted = Avinstallationsåtgärden misslyckades, {$app} avinstallerades endast delvis.
    .update-clean = Uppdateringsåtgärden misslyckades, {$app} uppdaterades inte. Den nuvarande installerade versionen {$current_version} kvarstår och kan fortfarande användas.
    .update-corrupted = Uppdateringsåtgärden misslyckades, {$app} uppdaterades endast delvis.

title =
    .install = Installation misslyckades
    .repair = Reparation misslyckades
    .uninstall = Avinstallation misslyckades
    .update = Uppdatering misslyckades