### Machine translated by `cargo zng l10n`, 2abd48f76a022e01c465074590f32305b520f65b9a52b2a63373e4df86ad2381

### Auto generated by `cargo zng l10n`

action-run =
    .info = Kör {$app}

message =
    .install = Guiden har installerat {$app} {$version} på din dator.
    .repair = Guiden har reparerat installationen av {$app} {$version} på din dator.
    .uninstall = Guiden har avinstallerat {$app} {$version} från din dator.
    .update = Guiden har uppdaterat {$app} från {$current_version} till {$new_version} på din dator.

title =
    .install = {$app} installerat
    .repair = {$app} reparerat
    .uninstall = {$app} avinstallerat
    .update = {$app} uppdaterat