### Machine translated by `cargo zng l10n`, 08fd454f1bfe552e85c1338a6842b18e91dd13c7e3b2949c8b5dc77f1e0c9f8c

### Auto generated by `cargo zng l10n`

info =
    .install = Var ska {$app} installeras?
    .update-repair-uninstall = Var {$app} är installerad.

# $bytes is already formatted e.g.: 900kB or 50MB.
min-required-space = Minst {$bytes} ledigt diskutrymme krävs.

reset-label = Standardplats

select-label = Välj plats

title =
    .install = Välj installationsplats
    .uninstall = Installationsplats