### Machine translated by `cargo zng l10n`, 2abd48f76a022e01c465074590f32305b520f65b9a52b2a63373e4df86ad2381

### Auto generated by `cargo zng l10n`

action-run =
    .info = 运行 {$app}

message =
    .install = 向导已在您的计算机上安装 {$app} {$version}。
    .repair = 向导已修复您计算机上的 {$app} {$version} 安装。
    .uninstall = 向导已从您的计算机上卸载 {$app} {$version}。
    .update = 向导已将您计算机上的 {$app} 从 {$current_version} 更新至 {$new_version}。

title =
    .install = {$app} 已安装
    .repair = {$app} 已修复
    .uninstall = {$app} 已卸载
    .update = {$app} 已更新