### Machine translated by `cargo zng l10n`, 7e38427d13a824c01f61a40c9cc84343f4089dd04c28a1f541f14d6f9c1dff32

### Auto generated by `cargo zng l10n`

message =
    .install = 这将在您的计算机上安装 {$app} {$version}。
    .repair = 这将修复您计算机上 {$app} {$version} 的安装。
    .uninstall = 这将从您的计算机上卸载 {$app} {$version}。
    .update = 这会将您计算机上的 {$app} 从 {$current_version} 更新至 {$new_version}。

title =
    .install = 欢迎使用 {$app} 安装向导
    .repair = 欢迎使用 {$app} 修复向导
    .uninstall = 欢迎使用 {$app} 卸载向导
    .update = 欢迎使用 {$app} 更新向导