### Machine translated by `cargo zng l10n`, 3bff0a0f920b53ccdc5a8a62ff6395907be54fe1e4eb7448f218d39230ddc71b

### Auto generated by `cargo zng l10n`

PAGE_DOWN_CMD =
    .info = Cuộn xuống một trang
    .name = Trang dưới

PAGE_LEFT_CMD =
    .info = Cuộn sang trái một trang
    .name = Trang trái

PAGE_RIGHT_CMD =
    .info = Cuộn sang phải một trang
    .name = Trang phải

PAGE_UP_CMD =
    .info = Cuộn lên một trang
    .name = Trang trên

SCROLL_DOWN_CMD =
    .info = Cuộn xuống một đơn vị
    .name = Cuộn xuống

SCROLL_LEFT_CMD =
    .info = Cuộn sang trái một đơn vị
    .name = Cuộn sang trái

SCROLL_RIGHT_CMD =
    .info = Cuộn sang phải một đơn vị
    .name = Cuộn sang phải

SCROLL_TO_BOTTOM_CMD =
    .info = Cuộn xuống dưới cùng của nội dung.
    .name = Cuộn xuống cuối

SCROLL_TO_LEFTMOST_CMD =
    .info = Cuộn sang trái tận cùng của nội dung
    .name = Cuộn đến tận cùng bên trái

SCROLL_TO_RIGHTMOST_CMD =
    .info = Cuộn sang phải tận cùng của nội dung
    .name = Cuộn đến tận cùng bên phải

SCROLL_TO_TOP_CMD =
    .info = Cuộn lên trên cùng của nội dung
    .name = Cuộn lên đầu

SCROLL_UP_CMD =
    .info = Cuộn lên một đơn vị
    .name = Cuộn lên

ZOOM_IN_CMD =
    .name = Phóng to

ZOOM_OUT_CMD =
    .name = Thu nhỏ

ZOOM_RESET_CMD =
    .name = Đặt lại thu phóng

ZOOM_TO_FIT_CMD =
    .name = Thu phóng vừa khung hình