### Machine translated by `cargo zng l10n`, f6f3457c31fdbcd5d2453877e9762215770aa27c6e290e4b4b30e0a2f59d484a

### Auto generated by `cargo zng l10n`

# name:
#     Naam van de licentie
# user-name:
#     "user" is het pakket dat de licentie gebruikt
license-none =
    .id = <geen>
    .name = Geen licentiegegevens
    .user-name = <geen>

search =
    .placeholder = doorzoek licenties ({$shortcut})

window =
    .title = {$app} - Licenties van derden