### Machine translated by `cargo zng l10n`, f66bc3e2d3fe992cf8f2ec38a95f5c05828baae1f65d73e015906b4eebfe2254

### Auto generated by `cargo zng l10n`

### Valid gesture key names
### 
### * The ID is the `Key` variant name. [1]
### * An OS generic text must be provided, optional OS specific text can be set as attributes.
### * OS attribute is a `std::env::consts::OS` value. [2]
### * L10n not include Char, Str, modifiers and composite keys.
### 
### Note: This file does not include all valid keys, see [1] for a full list.
### 
### [1]: https://zng-ui.github.io/doc/zng/keyboard/enum.Key.html
### [2]: https://doc.rust-lang.org/std/env/consts/constant.OS.html

ArrowDown = ↓

ArrowLeft = ←

ArrowRight = →

ArrowUp = ↑

Backspace = ←Atpakaļatkāpe
    .macos = Dzēst

Close = Aizvērt

ContextMenu = ≣Konteksta izvēlne

Copy = Kopēt

Cut = Izgriezt

Delete = Dzēst
    .macos = Dzēst uz priekšu

Eject = ⏏Izstumt

Enter = ↵Ievadīt
    .macos = ↵Atgriezt

Escape = Esc

Find = Atrast

Help = ?Palīdzība

New = Jauns

Open = Atvērt

PageDown = Lapa uz leju

PageUp = Lapa uz augšu

Paste = Ielīmēt

Print = Drukāt

PrintScreen = Ekrānuzņēmums

Redo = Atkārtot

Save = Saglabāt

Tab = ⭾Tabulēšana

Undo = Atsaukt

ZoomIn = +Pietuvināt

ZoomOut = -Attālināt