### Machine translated by `cargo zng l10n`, 85327a783ddb73e3b504dd657edba08fa951b35eba79666cd986bff08de07e3f

### Auto generated by `cargo zng l10n`

response-cancel = 取消

response-close = 关闭

response-no = 否

response-ok = 确定

response-yes = 是