[env]
DO_CMD = "cargo do"

[alias]
do = ["run", "--manifest-path", "tools/cargo-do/Cargo.toml", "--quiet", "--"]
# Windows does not support 'cargo do clean' because it locks the exe path, this
# alias runs from a different target dir
do-windows-target = ["run", "--manifest-path", "tools/cargo-do/Cargo.toml", "--quiet", "--target-dir", "tools/cargo-do/target", "--"]
