### Machine translated by `cargo zng l10n`, 2590ac79b0c8ba2dd798f143391a757cb81e66b377d998a90be9a820e78ad328

### Auto generated by `cargo zng l10n`

BACK_CMD =
    .name = ย้อนกลับ

BEGIN_CMD =
    .name = เริ่มต้น

CANCEL_CMD =
    .name = ยกเลิก

FINISH_CMD =
    .name = เสร็จสิ้น

NEXT_CMD =
    .name = ถัดไป