### Machine translated by `cargo zng l10n`, 3e9db6ab8a9dbbac14d31c68f744c15e88fd79703c907e34ad6ccc8a803d4847

### Auto generated by `cargo zng l10n`

CLOSE_CMD =
    .info = Luk vinduet
    .name = Luk

EXCLUSIVE_FULLSCREEN_CMD =
    .info = Skift eksklusiv fuldskærmstilstand for vinduet
    .name = Eksklusiv fuldskærm

FULLSCREEN_CMD =
    .info = Skift fuldskærmstilstand for vinduet
    .name = Fuldskærm

MAXIMIZE_CMD =
    .info = Maksimér vinduet
    .name = Maksimér

MINIMIZE_CMD =
    .info = Minimér vinduet
    .name = Minimér

RESTORE_CMD =
    .info = Genskaber vinduet til dets forrige ikke-minimeret tilstand eller normal tilstand
    .name = Gendan