### Machine translated by `cargo zng l10n`, 2e49d26318e656cea8e53532cc9cf2a73d2a6da0ef41a93590701e393b1ed3ad

### Auto generated by `cargo zng l10n`

BACK_CMD =
    .name = Atzera

CANCEL_CMD =
    .name = Utzi

FINISH_CMD =
    .name = Amaitu

NEXT_CMD =
    .name = Hurrengoa