### Machine translated by `cargo zng l10n`, be135842e65abb43f38e8f66e75bcc43fb249683b92f3d12466fbb444de99621

### Auto generated by `cargo zng l10n`

info =
    .clean = A operación fallou, todos os cambios desfeitos.
    .corrupted = A operación fallou, instalación corrompida.

message =
    .install-clean = A operación de instalación fallou, {$app} non se instalou.
    .install-corrupted = A operación de instalación fallou, {$app} só se instalou parcialmente.
    .repair-clean = A operación de reparación fallou, a instalación de {$app} non se reparou.
    .repair-corrupted = A operación de reparación fallou, {$app} só se reparou parcialmente.
    .uninstall-clean = A operación de desinstalación fallou, {$app} segue instalada.
    .uninstall-corrupted = A operación de desinstalación fallou, {$app} só se desinstalou parcialmente.
    .update-clean = A operación de actualización fallou, {$app} non se actualizou. A versión instalada actual {$current_version} segue e aínda pode ser usada.
    .update-corrupted = A operación de actualización fallou, {$app} só se actualizou parcialmente.

title =
    .install = Instalación fallida
    .repair = Reparación fallida
    .uninstall = Desinstalación fallida
    .update = Actualización fallida