### Machine translated by `cargo zng l10n`, 85327a783ddb73e3b504dd657edba08fa951b35eba79666cd986bff08de07e3f

### Auto generated by `cargo zng l10n`

response-cancel = Loobu

response-close = Sulge

response-no = Ei

response-ok = OK

response-yes = Jah