### Machine translated by `cargo zng l10n`, 99c16e25d5eccbc4a89d0ea0c5cad4a2c245c36657283da349303ad4efa259d8

### Auto generated by `cargo zng l10n`

NEW_CMD =
    .name = Nouveau

OPEN_CMD =
    .name = Ouvrir…

SAVE_AS_CMD =
    .name = Enregistrer sous…

SAVE_CMD =
    .name = Enregistrer

SETTINGS_CMD =
    .name = Paramètres