### Machine translated by `cargo zng l10n`, 3e9db6ab8a9dbbac14d31c68f744c15e88fd79703c907e34ad6ccc8a803d4847

### Auto generated by `cargo zng l10n`

CLOSE_CMD =
    .info = Uždaryti langą
    .name = Uždaryti

EXCLUSIVE_FULLSCREEN_CMD =
    .info = Perjungti išskirtinį viso ekrano režimą lange
    .name = Išskirtinis viso ekrano režimas

FULLSCREEN_CMD =
    .info = Perjungti viso ekrano režimą lange
    .name = Visas ekranas

MAXIMIZE_CMD =
    .info = Išskleisti langą
    .name = Išskleisti

MINIMIZE_CMD =
    .info = Suskleisti langą
    .name = Suskleisti

RESTORE_CMD =
    .info = Atkurti langą į ankstesnę nesuskleistą arba įprastą būseną
    .name = Atkurti