### Machine translated by `cargo zng l10n`, 08fd454f1bfe552e85c1338a6842b18e91dd13c7e3b2949c8b5dc77f1e0c9f8c

### Auto generated by `cargo zng l10n`

info =
    .install = Куда установить {$app}?
    .update-repair-uninstall = Место установки {$app}.

# $bytes is already formatted e.g.: 900kB or 50MB.
min-required-space = Требуется не менее {$bytes} свободного места на диске.

reset-label = Путь по умолчанию

select-label = Выбрать путь

title =
    .install = Выберите место установки
    .uninstall = Место установки