### Machine translated by `cargo zng l10n`, 4292840b02efe22ea758535122b9d05ba08fe158b1edf04331363016191aab59

### Auto generated by `cargo zng l10n`

message =
    .install = Это установит {$app} {$version} на ваш компьютер.
    .uninstall = Это удалит {$app} {$version} с вашего компьютера.
    .update = Это обновит {$app} с версии {$current_version} до {$new_version} на вашем компьютере.

title =
    .install = Добро пожаловать в мастер установки {$app}
    .repair = Добро пожаловать в мастер восстановления {$app}
    .uninstall = Добро пожаловать в мастер удаления {$app}
    .update = Добро пожаловать в мастер обновления {$app}