[package]
name = "zng-ext-setup"
version = "0.1.0"
authors = ["The Zng Project Developers"]
edition = "2024"
license = "Apache-2.0 OR MIT"
readme = "README.md"
description = "Part of the zng project."
documentation = "https://zng-ui.github.io/doc/zng_state_map"
repository = "https://github.com/zng-ui/zng"
categories = ["gui"]
keywords = ["gui", "ui", "user-interface", "zng"]

[dependencies]
zng-var = { path = "../zng-var", version = "0.15.2", default-features = false }
zng-task = { path = "../zng-task", version = "0.15.2", default-features = false }
zng-txt = { path = "../zng-txt", version = "0.6.0", default-features = false }
zng-ext-config = { path = "../zng-ext-config", version = "0.15.2", default-features = false }
zng-unit = { path = "../zng-unit", version = "0.7.1", default-features = false }
zng-app = { path = "../zng-app", version = "0.25.2", default-features = false }
zng-clone-move = { path = "../zng-clone-move", version = "0.4.0", default-features = false }

serde = { version = "1.0", default-features = false, features = ["std", "derive"] }
tar = { version = "0.4.45", default-features = false, features = ["xattr"] }
tracing = { version = "0.1", default-features = false, features = ["std"] }
walkdir = { version = "2.5", default-features = false }