### Machine translated by `cargo zng l10n`, 08fd454f1bfe552e85c1338a6842b18e91dd13c7e3b2949c8b5dc77f1e0c9f8c

### Auto generated by `cargo zng l10n`

info =
    .install = Onde {$app} deve ser instalado?
    .update-repair-uninstall = Onde {$app} está instalado.

# $bytes is already formatted e.g.: 900kB or 50MB.
min-required-space = É necessário pelo menos {$bytes} de espaço livre em disco.

reset-label = Localização Padrão

select-label = Selecionar Localização

title =
    .install = Selecionar Local de Instalação
    .uninstall = Local de Instalação