### Machine translated by `cargo zng l10n`, ab0682936292139ef046e822c139586a33986c3522951ecb20715ef0c900db4b

### Auto generated by `cargo zng l10n`

FOCUS_ALT_CMD =
    .info = Phạm vi tập trung thay thế
    .name = Tập trung Alt

FOCUS_DOWN_CMD =
    .info = Tập trung vào phần tử có thể chọn gần nhất phía dưới
    .name = Tập trung Xuống

FOCUS_ENTER_CMD =
    .info = Tập trung vào phần tử con có thể chọn
    .name = Tập trung Enter

FOCUS_EXIT_CMD =
    .info = Tập trung vào phần tử cha có thể chọn, hoặc trả lại tiêu điểm
    .name = Thoát Tập trung

FOCUS_LEFT_CMD =
    .info = Tập trung vào phần tử có thể chọn gần nhất phía trái
    .name = Tập trung Trái

FOCUS_NEXT_CMD =
    .info = Tập trung vào phần tử có thể chọn tiếp theo
    .name = Tập trung Tiếp theo

FOCUS_PREV_CMD =
    .info = Tập trung vào phần tử có thể chọn trước đó
    .name = Tập trung Trước đó

FOCUS_RIGHT_CMD =
    .info = Tập trung vào phần tử có thể chọn gần nhất phía phải
    .name = Tập trung Phải

FOCUS_UP_CMD =
    .info = Tập trung vào phần tử có thể chọn gần nhất phía trên
    .name = Tập trung Lên