### Machine translated by `cargo zng l10n`, ca15a8ce25cc0c158873c10a67ae3b8a2387847209565e6c26c99f1cba2d77eb

### Auto generated by `cargo zng l10n`

accept =
    .false = Ne prihvatam ugovor
    .true = Prihvatam ugovor

info =
    .install = Molimo vas da pročitate uslove licence pre instaliranja programa {$app}
    .update = Molimo vas da pročitate uslove licence pre ažuriranja programa {$app}

message = Morate prihvatiti uslove ovog ugovora pre nastavka.
    .requires_scroll = Morate pročitati i prihvatiti uslove ovog ugovora pre nastavka.

title = Licencni ugovor