### Machine translated by `cargo zng l10n`, 08fd454f1bfe552e85c1338a6842b18e91dd13c7e3b2949c8b5dc77f1e0c9f8c

### Auto generated by `cargo zng l10n`

info =
    .install = Gde bi {$app} trebalo da bude instaliran?
    .update-repair-uninstall = Gde je {$app} instaliran.

# $bytes is already formatted e.g.: 900kB or 50MB.
min-required-space = Zahteva se najmanje {$bytes} slobodnog prostora na disku.

reset-label = Podrazumevana lokacija

select-label = Izaberite lokaciju

title =
    .install = Izaberite lokaciju za instalaciju
    .uninstall = Lokacija za instalaciju