### Machine translated by `cargo zng l10n`, 3e9db6ab8a9dbbac14d31c68f744c15e88fd79703c907e34ad6ccc8a803d4847

### Auto generated by `cargo zng l10n`

CLOSE_CMD =
    .info = Az ablak bezárása
    .name = Bezárás

EXCLUSIVE_FULLSCREEN_CMD =
    .info = Exkluzív teljes képernyős mód váltása az ablakon
    .name = Exkluzív teljes képernyő

FULLSCREEN_CMD =
    .info = Teljes képernyős mód váltása az ablakon
    .name = Teljes képernyő

MAXIMIZE_CMD =
    .info = Az ablak maximalizálása
    .name = Maximalizálás

MINIMIZE_CMD =
    .info = Az ablak minimalizálása
    .name = Minimalizálás

RESTORE_CMD =
    .info = Az ablak visszaállítása a korábbi nem minimalizált vagy normál állapotába
    .name = Visszaállítás