### Machine translated by `cargo zng l10n`, ab0682936292139ef046e822c139586a33986c3522951ecb20715ef0c900db4b

### Auto generated by `cargo zng l10n`

FOCUS_ALT_CMD =
    .info = Fokuser på alt område
    .name = Fokus Alt

FOCUS_DOWN_CMD =
    .info = Fokuser på nærmeste fokuserbare ned
    .name = Fokus Ned

FOCUS_ENTER_CMD =
    .info = Fokuser på barn-fokuserbart
    .name = Fokus Enter

FOCUS_EXIT_CMD =
    .info = Fokuser på forelder-fokuserbart, eller returner fokus
    .name = Fokus Exit

FOCUS_LEFT_CMD =
    .info = Fokuser på nærmeste fokuserbare venstre
    .name = Fokus Venstre

FOCUS_NEXT_CMD =
    .info = Fokuser på neste fokuserbare
    .name = Fokus Neste

FOCUS_PREV_CMD =
    .info = Fokuser på forrige fokuserbare
    .name = Fokus Forrige

FOCUS_RIGHT_CMD =
    .info = Fokuser på nærmeste fokuserbare høyre
    .name = Fokus Høyre

FOCUS_UP_CMD =
    .info = Fokuser på nærmeste fokuserbare opp
    .name = Fokus Opp