### Machine translated by `cargo zng l10n`, be135842e65abb43f38e8f66e75bcc43fb249683b92f3d12466fbb444de99621

### Auto generated by `cargo zng l10n`

info =
    .clean = Thao tác thất bại, tất cả thay đổi đã được hoàn tác.
    .corrupted = Thao tác thất bại, cài đặt bị hỏng.

message =
    .install-clean = Thao tác cài đặt thất bại, {$app} chưa được cài đặt.
    .install-corrupted = Thao tác cài đặt thất bại, {$app} chỉ được cài đặt một phần.
    .repair-clean = Thao tác sửa chữa thất bại, cài đặt của {$app} chưa được sửa chữa.
    .repair-corrupted = Thao tác sửa chữa thất bại, {$app} chỉ được sửa chữa một phần.
    .uninstall-clean = Thao tác gỡ cài đặt thất bại, {$app} vẫn còn được cài đặt.
    .uninstall-corrupted = Thao tác gỡ cài đặt thất bại, {$app} chỉ được gỡ cài đặt một phần.
    .update-clean = Thao tác cập nhật thất bại, {$app} chưa được cập nhật. Phiên bản đã cài đặt hiện tại {$current_version} vẫn còn và vẫn có thể sử dụng được.
    .update-corrupted = Thao tác cập nhật thất bại, {$app} chỉ được cập nhật một phần.

title =
    .install = Cài đặt Thất bại
    .repair = Sửa chữa Thất bại
    .uninstall = Gỡ cài đặt Thất bại
    .update = Cập nhật Thất bại