### Machine translated by `cargo zng l10n`, 08fd454f1bfe552e85c1338a6842b18e91dd13c7e3b2949c8b5dc77f1e0c9f8c

### Auto generated by `cargo zng l10n`

info =
    .install = {$app} nên được cài đặt ở đâu?
    .update-repair-uninstall = {$app} được cài đặt ở đây.

# $bytes is already formatted e.g.: 900kB or 50MB.
min-required-space = Yêu cầu ít nhất {$bytes} dung lượng trống đĩa.

reset-label = Vị trí Mặc định

select-label = Chọn Vị trí

title =
    .install = Chọn Vị trí Cài đặt
    .uninstall = Vị trí Cài đặt