### Machine translated by `cargo zng l10n`, 8c9c95d8cf28b2cb9c70f9781ccec7824f959908ffe3f862c4b327a081d61caf

### Auto generated by `cargo zng l10n`

INSPECT_CMD =
    .info = Pregledaj prozor
    .name = Inspektor za debagovanje

## Inspector Window (always en-US)

info-help = Informacije o praćenom widgetu

intrinsic-help = Intrinzični čvor

nest-group-help = Ugnježdena grupa

screenshot =
    .copy-error = Greška pri kopiranju snimke zaslona. {$error}
    .error-dlg-title = Greška pri snimci zaslona
    .save-dlg-filter = Slika datoteke
    .save-dlg-starting-name = screenshot.png
    .save-dlg-title = Sačuvaj snimku zaslona
    .save-error = Greška pri spremanju snimke zaslona. {$error}

select-widget = Odaberi widget za pregled

window =
    .title = {$inspected_window_title} - Inspektor