### Machine translated by `cargo zng l10n`, 2590ac79b0c8ba2dd798f143391a757cb81e66b377d998a90be9a820e78ad328

### Auto generated by `cargo zng l10n`

BACK_CMD =
    .name = Quay lại

BEGIN_CMD =
    .name = Bắt đầu

CANCEL_CMD =
    .name = Hủy bỏ

FINISH_CMD =
    .name = Kết thúc

NEXT_CMD =
    .name = Tiếp theo