### Machine translated by `cargo zng l10n`, be135842e65abb43f38e8f66e75bcc43fb249683b92f3d12466fbb444de99621

### Auto generated by `cargo zng l10n`

info =
    .clean = Operațiunea a eșuat, toate modificările au fost anulată.
    .corrupted = Operațiunea a eșuat, instalarea este coruptă.

message =
    .install-clean = Operațiunea de instalare a eșuat, {$app} nu a fost instalat.
    .install-corrupted = Operațiunea de instalare a eșuat, {$app} a fost instalat doar parțial.
    .repair-clean = Operațiunea de reparare a eșuat, instalarea {$app} nu a fost reparată.
    .repair-corrupted = Operațiunea de reparare a eșuat, {$app} a fost reparat doar parțial.
    .uninstall-clean = Operațiunea de dezinstalare a eșuat, {$app} rămâne instalat.
    .uninstall-corrupted = Operațiunea de dezinstalare a eșuat, {$app} a fost dezinstalat doar parțial.
    .update-clean = Operațiunea de actualizare a eșuat, {$app} nu a fost actualizat. Versiunea curentă instalată {$current_version} rămâne și poate fi utilizată.
    .update-corrupted = Operațiunea de actualizare a eșuat, {$app} a fost actualizat doar parțial.

title =
    .install = Eșec la instalare
    .repair = Eșec la reparare
    .uninstall = Eșec la dezinstalare
    .update = Eșec la actualizare