### Machine translated by `cargo zng l10n`, 7e38427d13a824c01f61a40c9cc84343f4089dd04c28a1f541f14d6f9c1dff32

### Auto generated by `cargo zng l10n`

message =
    .install = Acest lucru va instala {$app} {$version} pe computerul dvs.
    .repair = Acest lucru va repara instalarea {$app} {$version} pe computerul dvs.
    .uninstall = Acest lucru va dezinstala {$app} {$version} de pe computerul dvs.
    .update = Acest lucru va actualiza {$app} de la {$current_version} la {$new_version} pe computerul dvs.

title =
    .install = Bine ați venit la Magicianul de Instalare {$app}
    .repair = Bine ați venit la Magicianul de Reparare {$app}
    .uninstall = Bine ați venit la Magicianul de Dezinstalare {$app}
    .update = Bine ați venit la Magicianul de Actualizare {$app}