### Machine translated by `cargo zng l10n`, 4292840b02efe22ea758535122b9d05ba08fe158b1edf04331363016191aab59

### Auto generated by `cargo zng l10n`

message =
    .install = Aceasta va instala {$app} {$version} pe calculatorul dumneavoastră.
    .uninstall = Aceasta va dezinstala {$app} {$version} de pe calculatorul dumneavoastră.
    .update = Aceasta va actualiza {$app} de la {$current_version} la {$new_version} pe calculatorul dumneavoastră.

title =
    .install = Bun venit la expertul de instalare {$app}
    .repair = Bun venit la expertul de reparare {$app}
    .uninstall = Bun venit la expertul de dezinstalare {$app}
    .update = Bun venit la expertul de actualizare {$app}