### Machine translated by `cargo zng l10n`, ca15a8ce25cc0c158873c10a67ae3b8a2387847209565e6c26c99f1cba2d77eb

### Auto generated by `cargo zng l10n`

accept =
    .false = Nie akceptuję tej umowy
    .true = Akceptuję tę umowę

info =
    .install = Prosimy o zapoznanie się z warunkami licencji przed instalacją {$app}
    .update = Prosimy o zapoznanie się z warunkami licencji przed aktualizacją {$app}

message = Aby kontynuować, musisz zaakceptować warunki tej umowy.
    .requires_scroll = Aby kontynuować, musisz przeczytać i zaakceptować warunki tej umowy.

title = Umowa licencyjna