### Machine translated by `cargo zng l10n`, be135842e65abb43f38e8f66e75bcc43fb249683b92f3d12466fbb444de99621

### Auto generated by `cargo zng l10n`

info =
    .clean = Operacja nie powiodła się, wszystkie zmiany zostały cofnięte.
    .corrupted = Operacja nie powiodła się, instalacja jest uszkodzona.

message =
    .install-clean = Instalacja nie powiodła się, program {$app} nie został zainstalowany.
    .install-corrupted = Instalacja nie powiodła się, program {$app} został zainstalowany tylko częściowo.
    .repair-clean = Naprawa nie powiodła się, instalacja programu {$app} nie została naprawiona.
    .repair-corrupted = Naprawa nie powiodła się, instalacja programu {$app} została naprawiona tylko częściowo.
    .uninstall-clean = Odinstalowywanie nie powiodło się, program {$app} pozostał zainstalowany.
    .uninstall-corrupted = Odinstalowywanie nie powiodło się, program {$app} został odinstalowany tylko częściowo.
    .update-clean = Aktualizacja nie powiodła się, program {$app} nie został zaktualizowany. Bieżąca zainstalowana wersja {$current_version} pozostaje i może być nadal używana.
    .update-corrupted = Aktualizacja nie powiodła się, program {$app} został zaktualizowany tylko częściowo.

title =
    .install = Instalacja nie powiodła się
    .repair = Naprawa nie powiodła się
    .uninstall = Odinstalowywanie nie powiodło się
    .update = Aktualizacja nie powiodła się