### Machine translated by `cargo zng l10n`, 86bb0abb6293e164ae596c4745cba0db2da828923ef8061ed99c7bf5ccfa9ddd

### Auto generated by `cargo zng l10n`

default-info =
    .create-shortcut = Utwórz skrót
    .extract-files = Wypakuj pliki
    .register-uninstaller = Zarejestruj deinstalator
    .remove-files = Usuń pliki
    .remove-shortcut = Usuń skrót
    .unregister-uninstaller = Wyrejestruj deinstalator

info =
    .install = Proszę czekać, trwa instalacja {$app} na tym komputerze.
    .repair = Proszę czekać, trwa naprawa {$app} na tym komputerze.
    .uninstall = Proszę czekać, trwa odinstalowywanie {$app} z tego komputera.
    .update = Proszę czekać, trwa aktualizacja {$app} na tym komputerze.

title =
    .install = Instalowanie
    .repair = Naprawianie
    .uninstall = Odinstalowywanie
    .update = Aktualizowanie