### Machine translated by `cargo zng l10n`, 4292840b02efe22ea758535122b9d05ba08fe158b1edf04331363016191aab59

### Auto generated by `cargo zng l10n`

message =
    .install = To zainstaluje {$app} {$version} na Twoim komputerze.
    .uninstall = To odinstaluje {$app} {$version} z Twojego komputera.
    .update = To zaktualizuje {$app} z wersji {$current_version} do {$new_version} na Twoim komputerze.

title =
    .install = Witamy w kreatorze instalacji {$app}
    .repair = Witamy w kreatorze naprawy {$app}
    .uninstall = Witamy w kreatorze odinstalowywania {$app}
    .update = Witamy w kreatorze aktualizacji {$app}