[package]
name = "zng-wgt-setup"
version = "0.1.0"
authors = ["The Zng Project Developers"]
edition = "2024"
license = "Apache-2.0 OR MIT"
readme = "README.md"
description = "Part of the zng project."
documentation = "https://zng-ui.github.io/doc/zng_wgt_progress"
repository = "https://github.com/zng-ui/zng"
categories = ["gui"]
keywords = ["gui", "ui", "user-interface", "zng"]

[dependencies]
zng-ext-setup = { path = "../zng-ext-setup", version = "0.1.1", default-features = false }
zng-wgt-wizard = { path = "../zng-wgt-wizard", version = "0.1.1", default-features = false }
zng-wgt = { path = "../zng-wgt", version = "0.17.3", default-features = false }
zng-wgt-container = { path = "../zng-wgt-container", version = "0.16.3", default-features = false }
zng-wgt-markdown = { path = "../zng-wgt-markdown", version = "0.15.3", default-features = false }
zng-wgt-button = { path = "../zng-wgt-button", version = "0.16.3", default-features = false }
zng-wgt-text-input = { path = "../zng-wgt-text-input", version = "0.16.3", default-features = false }
zng-wgt-text = { path = "../zng-wgt-text", version = "0.16.3", default-features = false }
zng-env = { path = "../zng-env", version = "0.12.2", default-features = false }
zng-ext-l10n = { path = "../zng-ext-l10n", version = "0.17.3", default-features = false }
zng-wgt-dialog = { path = "../zng-wgt-dialog", version = "0.13.3", default-features = false }
zng-unit = { path = "../zng-unit", version = "0.7.1", default-features = false }
zng-wgt-toggle = { path = "../zng-wgt-toggle", version = "0.15.3", default-features = false }
zng-wgt-menu = { path = "../zng-wgt-menu", version = "0.15.3", default-features = false }
zng-wgt-scroll = { path = "../zng-wgt-scroll", version = "0.16.3", default-features = false }

tracing = { version = "0.1", default-features = false, features = ["std"] }