### Machine translated by `cargo zng l10n`, 2abd48f76a022e01c465074590f32305b520f65b9a52b2a63373e4df86ad2381

### Auto generated by `cargo zng l10n`

action-run =
    .info = Käivita {$app}

message =
    .install = Viisard on installinud {$app} {$version} teie arvutisse.
    .repair = Viisard on parandanud {$app} {$version} installatsiooni teie arvutis.
    .uninstall = Viisard on eemaldanud {$app} {$version} teie arvutist.
    .update = Viisard on uuendanud {$app} versioonilt {$current_version} versioonile {$new_version} teie arvutis.

title =
    .install = {$app} on installitud
    .repair = {$app} on parandatud
    .uninstall = {$app} on eemaldatud
    .update = {$app} on uuendatud