### Machine translated by `cargo zng l10n`, 7e38427d13a824c01f61a40c9cc84343f4089dd04c28a1f541f14d6f9c1dff32

### Auto generated by `cargo zng l10n`

message =
    .install = See installib {$app} {$version} teie arvutisse.
    .repair = See parandab {$app} {$version} installatsiooni teie arvutisse.
    .uninstall = See eemaldab {$app} {$version} teie arvutist.
    .update = See värskendab {$app} teie arvutisse {$current_version}st {$new_version}ni.

title =
    .install = Tere {$app} installimisviisnar
    .repair = Tere {$app} parandimisviisnar
    .uninstall = Tere {$app} eemaldimisviisnar
    .update = Tere {$app} värskendusviisnar