### Machine translated by `cargo zng l10n`, be135842e65abb43f38e8f66e75bcc43fb249683b92f3d12466fbb444de99621

### Auto generated by `cargo zng l10n`

info =
    .clean = Eragiketak huts egin du, aldaketa guztiak bertan behera utzi dira.
    .corrupted = Eragiketak huts egin du, instalazioa hondatuta dago.

message =
    .install-clean = Instalazio-eragiketak huts egin du, {$app} ez da instalatu.
    .install-corrupted = Instalazio-eragiketak huts egin du, {$app} partzialki baino ez da instalatu.
    .repair-clean = Konponketa-eragiketak huts egin du, {$app} instalazioa ez da konpondu.
    .repair-corrupted = Konponketa-eragiketak huts egin du, {$app} partzialki baino ez da konpondu.
    .uninstall-clean = Desinstalazio-eragiketak huts egin du, {$app} instalatuta geratu da.
    .uninstall-corrupted = Desinstalazio-eragiketak huts egin du, {$app} partzialki baino ez da desinstalatu.
    .update-clean = Eguneratze-eragiketak huts egin du, {$app} ez da eguneratu. Instalaturik dagoen {$current_version} bertsioak bere horretan jarraitzen du eta erabiltzen jarrai daiteke.
    .update-corrupted = Eguneratze-eragiketak huts egin du, {$app} partzialki baino ez da eguneratu.

title =
    .install = Instalazioak huts egin du
    .repair = Konponketak huts egin du
    .uninstall = Desinstalazioak huts egin du
    .update = Eguneratzeak huts egin du