### Machine translated by `cargo zng l10n`, 86bb0abb6293e164ae596c4745cba0db2da828923ef8061ed99c7bf5ccfa9ddd

### Auto generated by `cargo zng l10n`

default-info =
    .create-shortcut = Sort-bidea sortu
    .extract-files = Fitxategiak erauzi
    .register-uninstaller = Desinstalatzailea erregistratu
    .remove-files = Fitxategiak kendu
    .remove-shortcut = Sort-bidea kendu
    .unregister-uninstaller = Desinstalatzailea erregistrotik kendu

info =
    .install = Mesedez, itxaron {$app} zure ordenagailuan instalatzen den bitartean.
    .repair = Mesedez, itxaron {$app} zure ordenagailuan konpontzen den bitartean.
    .uninstall = Mesedez, itxaron {$app} zure ordenagailutik desinstalatzen den bitartean.
    .update = Mesedez, itxaron {$app} zure ordenagailuan eguneratzen den bitartean.

title =
    .install = Instalatzen
    .repair = Konpontzen
    .uninstall = Desinstalatzen
    .update = Eguneratzen