### Machine translated by `cargo zng l10n`, ab0682936292139ef046e822c139586a33986c3522951ecb20715ef0c900db4b

### Auto generated by `cargo zng l10n`

FOCUS_ALT_CMD =
    .info = 聚焦备选范围
    .name = 备选聚焦

FOCUS_DOWN_CMD =
    .info = 聚焦下方最近的可聚焦元素
    .name = 向下聚焦

FOCUS_ENTER_CMD =
    .info = 聚焦子级可聚焦元素
    .name = 进入聚焦

FOCUS_EXIT_CMD =
    .info = 聚焦父级可聚焦元素，或返回焦点
    .name = 退出聚焦

FOCUS_LEFT_CMD =
    .info = 聚焦左侧最近的可聚焦元素
    .name = 向左聚焦

FOCUS_NEXT_CMD =
    .info = 聚焦下一个可聚焦元素
    .name = 下一个聚焦

FOCUS_PREV_CMD =
    .info = 聚焦上一个可聚焦元素
    .name = 上一个聚焦

FOCUS_RIGHT_CMD =
    .info = 聚焦右侧最近的可聚焦元素
    .name = 向右聚焦

FOCUS_UP_CMD =
    .info = 聚焦上方最近的可聚焦元素
    .name = 向上聚焦