### Machine translated by `cargo zng l10n`, 3e9db6ab8a9dbbac14d31c68f744c15e88fd79703c907e34ad6ccc8a803d4847

### Auto generated by `cargo zng l10n`

CLOSE_CMD =
    .info = Zavřít okno
    .name = Zavřít

EXCLUSIVE_FULLSCREEN_CMD =
    .info = Přepnout okno do exkluzivního režimu celé obrazovky
    .name = Exkluzivní celá obrazovka

FULLSCREEN_CMD =
    .info = Přepnout okno do režimu celé obrazovky
    .name = Celá obrazovka

MAXIMIZE_CMD =
    .info = Maximalizovat okno
    .name = Maximalizovat

MINIMIZE_CMD =
    .info = Minimalizovat okno
    .name = Minimalizovat

RESTORE_CMD =
    .info = Obnovit okno do předchozího stavu (před minimalizací) nebo do normálního stavu
    .name = Obnovit