### Machine translated by `cargo zng l10n`, f7e78c417f90217d5c21cbcda6fabb6faeab7fde745f69268d7dce1a1f8f3772

### Auto generated by `cargo zng l10n`

try_open_link =
    .copy-path = Yolu Kopyala
    .copy-url = URL'yi Kopyala
    .open-url = Tarayıcıda Aç
    .reveal-path = Dosya Yöneticisinde Göster
    .reveal-path-macos = Finder'da Göster
    .reveal-path-windows = Dosya Gezgini'nde Göster