### Machine translated by `cargo zng l10n`, 8c9c95d8cf28b2cb9c70f9781ccec7824f959908ffe3f862c4b327a081d61caf

### Auto generated by `cargo zng l10n`

INSPECT_CMD =
    .info = Prehľadajte okno
    .name = Debug Inšpektor

## Inspector Window (always en-US)

info-help = informácie o sledovanom widgete

intrinsic-help = intrinzigálny uzol

nest-group-help = gniazdová skupina

screenshot =
    .copy-error = Chyba pri kopírovaní snímky obrazovky. {$error}
    .error-dlg-title = Chyba pri snímke obrazovky
    .save-dlg-filter = Obrazové súbory
    .save-dlg-starting-name = screenshot.png
    .save-dlg-title = Uložiť snímku obrazovky
    .save-error = Chyba pri uložení snímky obrazovky. {$error}

select-widget = Vyberte widget, ktorý chcete prehrať

window =
    .title = {$inspected_window_title} - Inšpektor