### Machine translated by `cargo zng l10n`, 8c9c95d8cf28b2cb9c70f9781ccec7824f959908ffe3f862c4b327a081d61caf

### Auto generated by `cargo zng l10n`

INSPECT_CMD =
    .info = Skontrolovať okno
    .name = Inšpektor ladenia

## Inspector Window (always en-US)

info-help = informácie o sledovanom widgete

intrinsic-help = vnútorný uzol

nest-group-help = skupina vnorenia

screenshot =
    .copy-error = Chyba kopírovania snímky obrazovky. {$error}
    .error-dlg-title = Chyba snímky obrazovky
    .save-dlg-filter = Súbory obrázkov
    .save-dlg-starting-name = snimka.png
    .save-dlg-title = Uložiť snímku obrazovky
    .save-error = Chyba ukladania snímky obrazovky. {$error}

select-widget = vyberte widget na kontrolu

window =
    .title = {$inspected_window_title} - Inšpektor