### Machine translated by `cargo zng l10n`, be135842e65abb43f38e8f66e75bcc43fb249683b92f3d12466fbb444de99621

### Auto generated by `cargo zng l10n`

info =
    .clean = Operazione non riuscita, tutte le modifiche sono state annullate.
    .corrupted = Operazione non riuscita, installazione danneggiata.

message =
    .install-clean = Operazione di installazione non riuscita, {$app} non è stato installato.
    .install-corrupted = Operazione di installazione non riuscita, {$app} è stato installato solo parzialmente.
    .repair-clean = Operazione di ripristino non riuscita, l'installazione di {$app} non è stata ripristinata.
    .repair-corrupted = Operazione di ripristino non riuscita, {$app} è stato ripristinato solo parzialmente.
    .uninstall-clean = Operazione di disinstallazione non riuscita, {$app} rimane installato.
    .uninstall-corrupted = Operazione di disinstallazione non riuscita, {$app} è stato disinstallato solo parzialmente.
    .update-clean = Operazione di aggiornamento non riuscita, {$app} non è stato aggiornato. La versione corrente {$current_version} rimane installata e può ancora essere utilizzata.
    .update-corrupted = Operazione di aggiornamento non riuscita, {$app} è stato aggiornato solo parzialmente.

title =
    .install = Installazione non riuscita
    .repair = Ripristino non riuscito
    .uninstall = Disinstallazione non riuscita
    .update = Aggiornamento non riuscito