### Machine translated by `cargo zng l10n`, 2bbf575c7bf1ae877b1732f1d62041cb9d57d959ec1aca0f05662bbd6d20a92f

### Auto generated by `cargo zng l10n`

# tip on hover of the reset arrow button
reset = Herstel naar standaard

search =
    .no_results = Geen instellingen gevonden
    .placeholder = doorzoek instellingen ({$shortcut})

window =
    .title = {$app} - Instellingen