### Machine translated by `cargo zng l10n`, d327d74d2c9ff2a55c3eb5b1da364fb6fa40cb1f71ece551e8ec80612f2303a9

### Auto generated by `cargo zng l10n`

default-info =
    .create-shortcut = Създаване на пряк път
    .extract-files = Извличане на файлове
    .remove-files = Премахване на файлове
    .remove-shortcut = Премахване на прекия път

info =
    .install = Моля, изчакайте, докато {$app} се инсталира на вашия компютър.
    .repair = Моля, изчакайте, докато {$app} се поправи на вашия компютър.
    .uninstall = Моля, изчакайте, докато {$app} се деинсталира от вашия компютър.
    .update = Моля, изчакайте, докато {$app} се актуализира на вашия компютър.

title =
    .install = Инсталиране
    .repair = Поправяне
    .uninstall = Деинсталиране
    .update = Актуализиране