### Machine translated by `cargo zng l10n`, 86bb0abb6293e164ae596c4745cba0db2da828923ef8061ed99c7bf5ccfa9ddd

### Auto generated by `cargo zng l10n`

default-info =
    .create-shortcut = Създаване на пряк път
    .extract-files = Извличане на файлове
    .register-uninstaller = Регистриране на програма за деинсталиране
    .remove-files = Премахване на файлове
    .remove-shortcut = Премахване на пряк път
    .unregister-uninstaller = Отписване на програма за деинсталиране

info =
    .install = Моля, изчакайте, докато {$app} се инсталира на вашия компютър.
    .repair = Моля, изчакайте, докато {$app} се поправя на вашия компютър.
    .uninstall = Моля, изчакайте, докато {$app} се деинсталира от вашия компютър.
    .update = Моля, изчакайте, докато {$app} се актуализира на вашия компютър.

title =
    .install = Инсталиране
    .repair = Поправяне
    .uninstall = Деинсталиране
    .update = Актуализиране