### Machine translated by `cargo zng l10n`, f7e78c417f90217d5c21cbcda6fabb6faeab7fde745f69268d7dce1a1f8f3772

### Auto generated by `cargo zng l10n`

try_open_link =
    .copy-path = Kopiraj pot
    .copy-url = Kopiraj URL
    .open-url = Odpri v brskalniku
    .reveal-path = Prikaži v upravitelju datotek
    .reveal-path-macos = Prikaži v Finderju
    .reveal-path-windows = Prikaži v Raziskovalcu datotek