### Machine translated by `cargo zng l10n`, 3e9db6ab8a9dbbac14d31c68f744c15e88fd79703c907e34ad6ccc8a803d4847

### Auto generated by `cargo zng l10n`

CLOSE_CMD =
    .info = Chiudi la finestra
    .name = Chiudi

EXCLUSIVE_FULLSCREEN_CMD =
    .info = Attiva/disattiva la modalità a schermo intero esclusivo sulla finestra
    .name = Schermo intero esclusivo

FULLSCREEN_CMD =
    .info = Attiva/disattiva la modalità a schermo intero sulla finestra
    .name = Schermo intero

MAXIMIZE_CMD =
    .info = Ingrandisci la finestra
    .name = Ingrandisci

MINIMIZE_CMD =
    .info = Riduci a icona la finestra
    .name = Riduci a icona

RESTORE_CMD =
    .info = Ripristina la finestra al suo stato precedente non ridotto a icona o allo stato normale
    .name = Ripristina