### Machine translated by `cargo zng l10n`, 2590ac79b0c8ba2dd798f143391a757cb81e66b377d998a90be9a820e78ad328

### Auto generated by `cargo zng l10n`

BACK_CMD =
    .name = Назад

BEGIN_CMD =
    .name = Начни

CANCEL_CMD =
    .name = Откажи

FINISH_CMD =
    .name = Завърши

NEXT_CMD =
    .name = Следващ