### Machine translated by `cargo zng l10n`, ca15a8ce25cc0c158873c10a67ae3b8a2387847209565e6c26c99f1cba2d77eb

### Auto generated by `cargo zng l10n`

accept =
    .false = Saya tidak menyetujui perjanjian ini
    .true = Saya menyetujui perjanjian ini

info =
    .install = Harap tinjau ketentuan lisensi sebelum menginstal {$app}
    .update = Harap tinjau ketentuan lisensi sebelum memperbarui {$app}

message = Anda harus menyetujui ketentuan perjanjian ini sebelum melanjutkan.
    .requires_scroll = Anda harus membaca dan menyetujui ketentuan perjanjian ini sebelum melanjutkan.

title = Perjanjian Lisensi