### Machine translated by `cargo zng l10n`, 86bb0abb6293e164ae596c4745cba0db2da828923ef8061ed99c7bf5ccfa9ddd

### Auto generated by `cargo zng l10n`

default-info =
    .create-shortcut = Buat pintasan
    .extract-files = Ekstrak berkas
    .register-uninstaller = Daftarkan uninstaller
    .remove-files = Hapus berkas
    .remove-shortcut = Hapus pintasan
    .unregister-uninstaller = Hapus pendaftaran uninstaller

info =
    .install = Harap tunggu sementara {$app} diinstal pada komputer Anda.
    .repair = Harap tunggu sementara {$app} diperbaiki pada komputer Anda.
    .uninstall = Harap tunggu sementara {$app} dihapus dari komputer Anda.
    .update = Harap tunggu sementara {$app} diperbarui pada komputer Anda.

title =
    .install = Menginstal
    .repair = Memperbaiki
    .uninstall = Menghapus
    .update = Memperbarui