### Machine translated by `cargo zng l10n`, d71191013144b142e5eaea12b0fca3409e50c6d718fac39611285128494e9ee4

### Auto generated by `cargo zng l10n`

## Bộ Xử lý Lỗi Gỡ lỗi

window =
    .title = {$app} - Ứng dụng bị lỗi

## Panels

# save-copy-starting-name:
#     default file name
minidump =
    .open-error = Không thể mở minidump.\n{$error}
        {$error}
    .remove-error = Không thể xóa minidump.\n{$error}
        {$error}
    .save-copy-filter-name = Minidump
    .save-copy-starting-name = minidump
    .save-copy-title = Lưu Bản Sao
    .save-error = Không thể lưu bản sao minidump.\n{$error}
        {$error}
    .title = Minidump

panic =
    .title = Sự cố

stderr =
    .title = Stderr

stdout =
    .title = Stdout

summary =
    .text = Timestamp: {$timestamp}
        Exit Code: {$exit_code}
        Signal: {$signal}
        Stderr: {$stderr_len} bytes
        Stdout: {$stdout_len} bytes
        Panic: {$is_panic}
        Minidump: {$minidump_path}
        
        Args: {$args}
        OS: {$os}
    .title = Tóm Tắt

widget =
    .title = Widget