### Machine translated by `cargo zng l10n`, 8c9c95d8cf28b2cb9c70f9781ccec7824f959908ffe3f862c4b327a081d61caf

### Auto generated by `cargo zng l10n`

INSPECT_CMD =
    .info = Akna kontrollimine
    .name = Silumisinspektor

## Inspector Window (always en-US)

info-help = jälgitava vidina teave

intrinsic-help = sisemine sõlm

nest-group-help = pesastatud grupp

screenshot =
    .copy-error = Ekraanipildi kopeerimise viga. {$error}
    .error-dlg-title = Ekraanipildi viga
    .save-dlg-filter = Pildifailid
    .save-dlg-starting-name = ekraanipilt.png
    .save-dlg-title = Salvesta ekraanipilt
    .save-error = Ekraanipildi salvestamise viga. {$error}

select-widget = vali kontrollimiseks vidin

window =
    .title = {$inspected_window_title} - Inspektor